### ISSUE TITLE
Strange behavior with neuroglancer.set_static_content_source

### ISSUE THREAD

**Issue by perlman** [google/neuroglancer#110]
Hi,

We ran into an issue using neuroglancer.set_static_content_source where the served neuroglancer does not work correctly (auth errors with brainmaps and other oddities).

Our intent was to use neuroglancer-python without having to locally compile neuroglancer.

This works:
`python -i python/examples/example.py
`
This does not (state not loaded, popup to add data source):
`python -i python/examples/example.py --static-content-url https://neuroglancer-demo.appspot.com/
`

@schlegelp also notes that the example of using `npm run dev-server` withneuroglancer.set_static_content_source(url='http://localhost:8080')` also starts in a broken state.

I have poked around a bit with the Chrome developer tools but did not see anything obvious.

Thanks,
Eric

**Comment by jbms** [comment]
A different version of the client must be built for the python integration.

You can use https://neuroglancer-demo.appspot.com/python  as the static-content-url or npm run dev-server-python.

**Comment by schlegelp** [comment]
That works, thanks a lot!

**Comment by perlman** [comment]
Aha! Thanks for the explanation!
