### ISSUE TITLE
Image layer not rendering when running dev-server

### ISSUE THREAD

**Issue by manuel-castro** [google/neuroglancer#118]
After pulling from master and running npm install on https://github.com/google/neuroglancer/commit/ecdbc0d6f15d23357ca0af698697b93ff98d3e2f, when I add an image layer (such as precomputed://gs://neuroglancer-public-data/kasthuri2011/image), it does not render. However, the layer widget shows the 8bit uints when I move my cursor, so the data appears to have loaded. It was working fine in the recent commit https://github.com/google/neuroglancer/commit/a65045a41dd36a1ecd984cdfd4696ec3ef6a5d5f, so it seems to be caused by something in the 6 commits in between.

**Comment by jbms** [comment]
Thanks for pointing this out.  This is fixed by d63b28ff807b712dc46d5e7d071758493fd0acdb.
