### ISSUE TITLE
Creating many annotations/selecting many segments causes screen to "move up" in Chrome 74

### ISSUE THREAD

**Issue by manuel-castro** [google/neuroglancer#137]
It seems that Chrome version 74 has made some CSS changes that reintroduces the bug that obscures the top of the UI when many annotations/segments are selected 

[Example](https://neuroglancer-demo.appspot.com/#!%7B%22layers%22:%5B%7B%22source%22:%22precomputed://gs://neuroglancer-public-data/kasthuri2011/image%22%2C%22type%22:%22image%22%2C%22name%22:%22original-image%22%2C%22visible%22:false%7D%2C%7B%22source%22:%22precomputed://gs://neuroglancer-public-data/kasthuri2011/image_color_corrected%22%2C%22type%22:%22image%22%2C%22name%22:%22corrected-image%22%7D%2C%7B%22source%22:%22precomputed://gs://neuroglancer-public-data/kasthuri2011/ground_truth%22%2C%22type%22:%22segmentation%22%2C%22selectedAlpha%22:0.63%2C%22notSelectedAlpha%22:0.14%2C%22segments%22:%5B%2213%22%2C%2215%22%2C%222282%22%2C%223189%22%2C%223207%22%2C%223208%22%2C%223224%22%2C%223228%22%2C%223710%22%2C%223758%22%2C%224027%22%2C%22444%22%2C%224651%22%2C%224901%22%2C%224965%22%5D%2C%22name%22:%22ground_truth%22%7D%2C%7B%22tool%22:%22annotatePoint%22%2C%22selectedAnnotation%22:%7B%22id%22:%22bd11a97305479e5b687fb950232dd45a4aaac14e%22%7D%2C%22type%22:%22annotation%22%2C%22annotations%22:%5B%7B%22point%22:%5B5254.99462890625%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%224f55e2f2154f56531b109a35e47179381cfd8759%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%224bdd2ef8382696fe68b872c6c74711f8a2fa4323%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%2230ba5c590e23714604c007f75a6529f166598405%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%228dbbbce4cfe211a562440f23ed2d0bf36453a73f%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%2288881b7d9591c8f5a2e12f1ede24c74e6cfb6bff%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%2244717f05ec7143b947f20f36b3dadde9e0fdc025%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%2294b1a5af065d07430a87d6d1fe6ea7029e826fa1%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22319c3921cf8404bcd4651e45e6a411fc27224a96%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%2236007de51f9c0de0cdc868ef2b9a12ce3b5f7460%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22ea31ecd55629bc7531a5e9de63e981ac9cc5430d%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%228533dc95a99440afc10b8fe6ae490ff3a385a058%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%229efc26243f89aa48f0994830c35942873cd6068f%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22b17ae5d98c54e604b863413dc895187b82c7e338%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22d1e607ba75e96d96a88f45f93f6648886a5c119b%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%2213eae4f090a4e3170afbaa6a6aba438165c9d534%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22886f2340d9f061f9d9202361bfcc50854b1244ed%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22d722c4ea7e68590d929f305805fc82805d992f5b%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%2273a0f17621c392e7fa98f5e1ce78ca92c7d3695f%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%226c7ddb49988aaed2b6a636ed4037593b26541a87%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22ae835137a26f00a0a098f81d58e3bb72470fd398%22%7D%2C%7B%22point%22:%5B5254.9951171875%2C8357.798828125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22812707aeb51e9924cd1bd992b88d01d63d191f02%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8374.21484375%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%224f818646d034ceb61fce5bd935c3b43261ce20fd%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8374.21484375%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22a91c7ea2950ca2ef470e5b296ae4f84a52f8ed64%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8344.1171875%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22285db0874d7693676d5a04d29c461a5a7cba4749%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8344.1171875%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22104c9d67673a0e49285b0e2f0e08cbf5f1e84220%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8315.9013671875%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22674667bf1166d84fbf5323f21398e09c64b206ef%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8315.9013671875%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22501fda1b5f7975cdbf3241848debed267c0a56a9%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8285.8037109375%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%227b83aafa784d26f82db3b50e65e766bd7cdfa0ec%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8285.8037109375%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%221acdeb82a9e6bf49863a2c7a498538cfbcf429a3%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8257.587890625%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%229f8ab2bee850a3d02a93eea1ce3745bc956e8d3d%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8257.587890625%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%2268009490b871469d681f7655c88ef4b3d1c4d642%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8227.490234375%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%227bc4017b9b5d44f2b6eee6a08dc84ea2782ffc7b%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8227.490234375%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%2254c0e3962c27987e26daa8eb7aedead2f7efd894%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8199.2734375%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22279222156f3b380d4428186fc149560127bdd175%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8199.2734375%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22fe7cd11f578e9652b278aa40c1466c0745aaa722%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8169.17578125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22bcf07d009fa2ed3c90802b6f8bea192576771533%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8169.17578125%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%2226c8a64b2d6487dac0b00a2dcc5aac23cf432890%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8140.9599609375%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%229c61c011795162659790f25f1b245208c67e27de%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8140.9599609375%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22034f8bd70d6194bac187f4c2c30c1341321976fd%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8112.7431640625%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22b44f0a00e868a8aafee0d9c73ca4c4d3593a0342%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8112.74365234375%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%2203b59c5d750a2546813e3e5bccae77df27da9ba1%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8082.64599609375%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22e93c7822b7f5ba6dddcb11b4e87c2eec84107018%22%7D%2C%7B%22point%22:%5B5766.65185546875%2C8082.64599609375%2C1198.0423583984375%5D%2C%22type%22:%22point%22%2C%22id%22:%22bd11a97305479e5b687fb950232dd45a4aaac14e%22%7D%5D%2C%22voxelSize%22:%5B6%2C6%2C30%5D%2C%22name%22:%22annotation%22%7D%5D%2C%22navigation%22:%7B%22pose%22:%7B%22position%22:%7B%22voxelSize%22:%5B6%2C6%2C30%5D%2C%22voxelCoordinates%22:%5B5523.99072265625%2C8538.9384765625%2C1198.0423583984375%5D%7D%7D%2C%22zoomFactor%22:22.573112129999547%7D%2C%22perspectiveOrientation%22:%5B-0.0040475670248270035%2C-0.9566215872764587%2C-0.22688281536102295%2C-0.18271005153656006%5D%2C%22perspectiveZoom%22:340.35867907175077%2C%22selectedLayer%22:%7B%22layer%22:%22annotation%22%2C%22visible%22:true%7D%2C%22layout%22:%224panel%22%7D)

**Comment by jingpengw** [comment]
just encounter this bug too. a long list of segment id can reproduce this issue too.

**Comment by jbms** [comment]
Thanks for reporting this issue.  This is now fixed.
