### ISSUE TITLE
neuroglancer viewer slice view breaks on Firefox 67 (current) and 68 (beta)

### ISSUE THREAD

**Issue by xgui3783** [google/neuroglancer#138]
Dear all, newest Firefox (windows, macos and ubuntu 16 + 18) update seem to have broken the sliceview in neuroglancer. In console, errors were logged as follows:

```
Error: WebGL warning: drawArrays: Program has no frag output at location 1, but destination draw buffer has an attached image.
```
at this line: https://github.com/google/neuroglancer/blob/742c58deb08fa31ad2350cb51f4b17b285a76648/src/neuroglancer/sliceview/frontend.ts#L438

[this line](https://searchfox.org/mozilla-central/source/dom/canvas/WebGLContextDraw.cpp#329) seems to be the line that throws the error, edit: introduced by [this](https://hg.mozilla.org/mozilla-central/rev/c5f938f573945791c3327e6bd661501417ed45d1) commit.

I apologise that my webgl foo is not strong enough to provide a fix, and thus can only research on some background.

**Comment by jbms** [comment]
Thanks for reporting this.  It is now fixed.
