### ISSUE TITLE
Failed at the neuroglancer@0.0.0-beta.0 dev-server script.

### ISSUE THREAD

**Issue by ArieSeirack** [google/neuroglancer#142]
I encountered this problem when I used the command
<pre>npm run dev-server</pre>
And the following is the output on the terminal:
<pre>&gt; neuroglancer@0.0.0-beta.0 dev-server /home/aries/NG/neuroglancer
&gt; webpack-dev-server --config ./config/webpack.config.js

Skipping &quot;*&quot; -&gt; [&quot;*&quot;]
{ neuroglancer: <font color="#4E9A06">&apos;/home/aries/NG/neuroglancer/src/neuroglancer&apos;</font> }
(node:16315) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
<font color="#3465A4">ℹ</font> <font color="#555753">｢wds｣</font>: Project is running at <font color="#729FCF"><b>http://localhost:8080/</b></font>
<font color="#3465A4">ℹ</font> <font color="#555753">｢wds｣</font>: webpack output is served from <font color="#729FCF"><b>/</b></font>
<font color="#3465A4">ℹ</font> <font color="#555753">｢wds｣</font>: Content not from webpack is served from <font color="#729FCF"><b>/home/aries/NG/neuroglancer</b></font>
(node:16315) DeprecationWarning: Resolver: The callback argument was splitted into resolveContext and callback.
(node:16315) DeprecationWarning: Resolver#doResolve: The type arguments (string) is now a hook argument (Hook). Pass a reference to the hook instead.

#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0x7ffe98157e00Illegal instruction (core dumped)
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> ELIFECYCLE
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">errno</font> 132
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> neuroglancer@0.0.0-beta.0 dev-server: `webpack-dev-server --config ./config/webpack.config.js`
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Exit status 132
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Failed at the neuroglancer@0.0.0-beta.0 dev-server script.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> This is probably not a problem with npm. There is likely additional logging output above.

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>     /home/aries/.npm/_logs/2019-07-09T08_29_24_745Z-debug.log</pre>

I do not know why this error happen. 
Firstly, there was a problem says the ts-loader may not be compatible with the typescript@3.4.5, so I installed another version of ts-loader. And the following is my current package.json.
<pre>
{
  "name": "neuroglancer",
  "description": "Visualization tool for 3-D volumetric data.",
  "license": "Apache-2.0",
  "version": "0.0.0-beta.0",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/google/neuroglancer.git"
  },
  "engines": {
    "node": ">=8"
  },
  "scripts": {
    "generate-code": "node ./config/generate_code.js",
    "build-min": "webpack --config ./config/webpack.config.js --env=min",
    "build": "webpack --config ./config/webpack.config.js --env=dev",
    "build-python": "webpack --config ./config/webpack.config.js --env=python-dev",
    "build-python-min": "webpack --config ./config/webpack.config.js --env=python-min",
    "build:watch": "webpack --config ./config/webpack.config.js --watch",
    "dev-server": "webpack-dev-server --config ./config/webpack.config.js",
    "dev-server-python": "webpack-dev-server --config ./config/webpack.config.js --env=python-dev",
    "test": "karma start ./config/karma.conf.js --single-run",
    "test:watch": "karma start ./config/karma.conf.js --no-single-run",
    "benchmark": "karma start ./config/karma.benchmark.js --single-run",
    "benchmark:watch": "karma start ./config/karma.benchmark.js --no-single-run",
    "gulp": "gulp"
  },
  "devDependencies": {
    "@types/jasmine": "^3.3.12",
    "benchmark": "^2.1.4",
    "clang-format": "^1.2.4",
    "copy-webpack-plugin": "^5.0.2",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "gulp": "^4.0.0",
    "gulp-clang-format": "^1.0.27",
    "gulp-tslint": "^8.1.4",
    "jasmine-core": "^3.4.0",
    "karma": "^4.1.0",
    "karma-benchmark": "^1.0.1",
    "karma-benchmark-reporter": "^0.1.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "^1.1.2",
    "karma-jasmine": "^2.0.1",
    "karma-mocha-reporter": "^2.2.5",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^4.0.2",
    "minimist": "^1.2.0",
    "nunjucks": "^3.2.0",
    "tslint": "^5.15.0",
    "tslint-eslint-rules": "^5.4.0",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": ">=3.2.1"
  },
  "dependencies": {
    "@tensorflow/tfjs": "0.14.2",
    "@types/codemirror": "0.0.72",
    "@types/gl-matrix": "^2.4.5",
    "@types/lodash": "^4.14.123",
    "@types/pako": "^1.0.1",
    "@types/sockjs-client": "^1.1.1",
    "@types/text-encoding": "0.0.35",
    "@types/webgl2": "^0.0.4",
    "@types/webpack-env": "^1.13.9",
    "acorn": "^6.1.1",
    "codemirror": "^5.45.0",
    "css-loader": "^2.1.1",
    "gl-matrix": "^3.0.0",
    "glsl-editor": "^1.0.0",
    "glsl-strip-comments-loader": "^1.1.0",
    "html-webpack-plugin": "^3.2.0",
    "lodash": "^4.17.11",
    "mini-css-extract-plugin": "^0.7.0",
    "nifti-reader-js": "^0.5.4",
    "pako": "^1.0.10",
    "raw-loader": "^2.0.0",
    "resize-observer-polyfill": "^1.5.1",
    "sockjs-client": "^1.3.0",
    "style-loader": "^0.23.1",
    "ts-loader": "^3.5.0",
    "typescript": "^3.4.5",
    "url-loader": "^1.1.2",
    "webpack": "^4.35.0"
  }
}
</pre>

**Comment by xgui3783** [comment]
just tested master branch @ 4ac770f2d3e651c05a71979000e4d02f19359835  with a dockerized node image, after
```
$ git clone https://github.com/google/neuroglancer
$ cd neuroglancer
$ npm i && npm run dev-server
```
neuroglancer runs the dev server (eventually).

The following warnings did get printed, but does not seem to affect the tranpilation process:
```
ts-loader: Using /neuroglancer/config/typescript_compiler_shim.js@3.4.5. This version may or may not be compatible with ts-loader.
ts-loader: Using /neuroglancer/config/typescript_compiler_shim.js@3.4.5. This version may or may not be compatible with ts-loader.
ts-loader: Using /neuroglancer/config/typescript_compiler_shim.js@3.4.5. This version may or may not be compatible with ts-loader.
```

maybe revert the changes you made, and try again?

**Comment by ArieSeirack** [comment]
> just tested master branch @ [4ac770f](https://github.com/google/neuroglancer/commit/4ac770f2d3e651c05a71979000e4d02f19359835) with a dockerized node image, after
> 
> ```
> $ git clone https://github.com/google/neuroglancer
> $ cd neuroglancer
> $ npm i && npm run dev-server
> ```
> 
> neuroglancer runs the dev server (eventually).
> 
> The following warnings did get printed, but does not seem to affect the tranpilation process:
> 
> ```
> ts-loader: Using /neuroglancer/config/typescript_compiler_shim.js@3.4.5. This version may or may not be compatible with ts-loader.
> ts-loader: Using /neuroglancer/config/typescript_compiler_shim.js@3.4.5. This version may or may not be compatible with ts-loader.
> ts-loader: Using /neuroglancer/config/typescript_compiler_shim.js@3.4.5. This version may or may not be compatible with ts-loader.
> ```
> 
> maybe revert the changes you made, and try again?

Yes, it works.
After reinstalling everything from nvm to neuroglancer, I can run it on my computer.
Maybe I just wanted to solve the problem about ts-loader previously and thus installed the version of typescripts which would did not fit with neuroglancer.
