### ISSUE TITLE
browser freezes when changing viewer state settings through the python integration with the layout option panel visible

### ISSUE THREAD

**Issue by moenigin** [google/neuroglancer#146]
using the python integration changes to the viewer like:
state = deepcopy(viewer.state)
state.layers[layer].selectedAlpha = val
viewer.set_state(state)
or
state.layers[layer].segments = segments
viewer.set_state(state)
cause the browser to freeze when viewer.state.selected_layer.visible==True

**Comment by jbms** [comment]
I believe this is fixed now, can you confirm?

**Comment by moenigin** [comment]
Yes this seems to work now! Tested it on toggling opacity and updating segment display where I encountered the issue before. Thanks a lot for fixing this!
