### ISSUE TITLE
change defaultViewerOptions w/ webpack

### ISSUE THREAD

**Issue by falkben** [google/neuroglancer#147]
I am attempting to override `defaultViewerOptions` in [`viewer.js`](https://github.com/google/neuroglancer/blob/master/src/neuroglancer/viewer.ts#L147-L150) in deployment using a webpack command.  Going off the suggestion in this issue [comment](https://github.com/google/neuroglancer/pull/107#issuecomment-426507492), I'm trying:  

`npm run build -- --define viewer.defaultViewerOptions="{showLayerDialog: false, resetStateWhenEmpty: true}"`

where the only difference is showLayerDialog set to `false` but this webpack command seems to *have no effect.*

I've tried also changing `defaultViewerOptions` in viewer.ts to be a `var` instead of a `const`, thinking that maybe webpack couldn't override the const.  I am hoping this is just something simple I'm missing about webpack -- thanks for your help.

Note, this is really simple, but if I can get this working, I'm hoping to return to the JSON url [PR](https://github.com/google/neuroglancer/pull/107) and convert it to a build option using a similar webpack override.

**Comment by jbms** [comment]
I fully support making this use case work.  Note, though, that Webpack define is not module (or possibly even scope) aware, as far as I know.  It basically just replaces all instances of the key, as they appear exactly in the code, with the replacement code on the right.  I'm also not sure what it does to an existing definition within the code.

So you should be able to do what you want, but you may need to do it slightly differently or make some other changes to how those default options are defined in the code.

**Comment by xgui3783** [comment]
I have made a somewhat example with this commit: https://github.com/xgui3783/neuroglancer/commit/9453eb1d640b88f723be2f24428239e086edd6ab
, which I believe is in the spirit of the referenced comment. and with the commit, the below script successfully runs neuroglancer with `showLayerDialog` as false 

```
npm run dev-server -- --define OVERWRITE_DEFAULT_VIEWER_OPTIONS="'showLayerDialog: false,resetStateWhenEmpty: true'"
```
I have also unsuccessfully tried to replace raw string (assignment of `defaultViewerOptions`). For that, you may need https://www.npmjs.com/package/string-replace-loader or https://www.npmjs.com/package/string-replace-webpack-plugin

**Comment by falkben** [comment]
Cool, that worked! Thanks. Seems like a more natural place to put the declare would be just at the top of `viewer.ts`?

**Comment by falkben** [comment]
See PR https://github.com/google/neuroglancer/pull/148
