### ISSUE TITLE
Firefox 69 reports invalid regex flag when running dev-server

### ISSUE THREAD

**Issue by j6k4m8** [google/neuroglancer#162]
## Repro steps:
* Clone current master (September 18, 2019)
* `yarn`
* `yarn run dev-server`

## Expected:
Web service runs

## Actual:
Firefox js console reports:
```
SyntaxError: invalid regular expression flag s main.bundle.js:67949:87
```

The `s` flag [is definitely a valid regex flag](https://javascript.info/regexp-introduction#flags), so I'm not sure why it's choking here. Chrome works fine, and if I remove the `s`, Firefox works fine as well.

Code pointer:
https://github.com/google/neuroglancer/blob/80c2abf72327bbf240486c7b2d2452afc1305974/src/neuroglancer/webgl/shader_ui_controls.ts#L58

**Comment by jbms** [comment]
Thanks for reporting this.  Looks like the s flag is not actually supported
by Firefox, so I'll have to use a workaround instead.

**Comment by jbms** [comment]
I believe this is fixed now.
