### ISSUE TITLE
#uicontrol not working

### ISSUE THREAD

**Issue by chrisroat** [google/neuroglancer#168]
Using the [demo](https://neuroglancer-demo.appspot.com/#!%7B"layers":%5B%7B"source":"precomputed://gs://neuroglancer-public-data/kasthuri2011/image"%2C"crossSectionRenderScale":0.835863629425607%2C"type":"image"%2C"opacity":0.64%2C"shader":"#uicontrol%20float%20brightness%20slider%28min=-1%2C%20max=1%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20emitGrayscale%28toNormalized%28getDataValue%28%29%29%20+%20brightness%29%3B%5Cn%7D%5Cn"%2C"name":"original-image"%7D%5D%2C"navigation":%7B"pose":%7B"position":%7B"voxelSize":%5B6%2C6%2C30%5D%2C"voxelCoordinates":%5B5590.55419921875%2C8720.7275390625%2C1097.0750732421875%5D%7D%7D%2C"zoomFactor":45.146224259999094%7D%2C"perspectiveOrientation":%5B-0.00007811884279362857%2C-0.8536661863327026%2C-0.393139511346817%2C-0.341607004404068%5D%2C"perspectiveZoom":340.35867907175077%2C"selectedLayer":%7B"layer":"original-image"%2C"visible":true%2C"size":599%7D%2C"layout":"4panel"%7D) website and my own dev server, I've found the `#uicontrol` directive mentioned on the [Image Layer Rendering](https://github.com/google/neuroglancer/blob/ebb893928bc00ee61508f2c6ce23e01fe0e650c9/src/neuroglancer/sliceview/image_layer_rendering.md) page doesn't seem to be supported when updating the shader.

<img width="659" alt="Screen Shot 2019-10-17 at 8 12 55 PM" src="https://user-images.githubusercontent.com/1053153/67063162-94d5e400-f11a-11e9-9a2e-3ed427e39796.png">

**Comment by xgui3783** [comment]
Hmm, it's possible that the demo version is not the latest build? UI
control commit seems pretty recent.

**Comment by chrisroat** [comment]
Ah, you are likely correct.  When I tested on my dev server, I just type "#uicontrol" and got the same error.  

The error goes away when the full #uicontrol line is entered.  A better error might be "syntax error" if the directive is correct, but the usage is incomplete/wrong.
