### ISSUE TITLE
#uicontrol not working -- shaders won't update

### ISSUE THREAD

**Issue by perlman** [google/neuroglancer#177]
I am trying to use the #uicontrol controls without much luck. The shaders stop being updated as soon as I add any #uicontrol element, even if it is not being referenced in the shader.

For example, starting with this shader, I can change 1.0 to 0.5, and it takes effect immediately:
```
void main() {
  emitGrayscale(1.0* toNormalized(getDataValue()));
}
```

If I add a single UI control, the shader stops updating. For example, if I paste this shader in over the previous one, I get a slider, but the channel remains visible.

```
#uicontrol float scale slider(min=0.0, max=1.0)
void main() {
  emitGrayscale(0.0* toNormalized(getDataValue()));
}
```

If I then remove the #uicontrol, the images goes dark immediately (as expected):
```
void main() {
  emitGrayscale(0.0* toNormalized(getDataValue()));
}
```

There are no errors on the console with either Chrome 78.0.3904.87 and FIreFox 70.0.1 (both on MacOS) using master.

**Comment by jbms** [comment]
Thanks for reporting this.  This is fixed by 7e67b4bcf010420e2c07d11cbcbe08f3b029c964.
