### ISSUE TITLE
Missing annotation details.

### ISSUE THREAD

**Issue by neomorphic** [google/neuroglancer#178]
Commit 8de8f9033dbb75bff82d3a21e5c2d8e25eb0b6d3 seems to have introduced a bug that pushes the annotation details component off the bottom of the browser window. Please see the attached before and after images. I would be happy to help debug, but I don't have an example that shows me what the commit was intended to fix. If you have that, I will be happy to investigate.

![Screen Shot 2019-11-15 at 11 15 29 AM](https://user-images.githubusercontent.com/10181/68958290-ce415400-0799-11ea-9b47-eb7a2b5886db.png)
![Screen Shot 2019-11-15 at 11 15 38 AM](https://user-images.githubusercontent.com/10181/68958294-d00b1780-0799-11ea-9796-3095f3e0a92f.png)

**Comment by jbms** [comment]
Thanks for reporting this issue.  That commit was intended to fix layout problems when the overall browser height was shrunk to the point that the side panel content would not all fit.  Previously, that would result in the rendered panels overflowing off the bottom of the bottom.  However, I only intended those style changes to affect the actual side panel "tabs", not realizing that the same class was also used for the details pane.
