### ISSUE TITLE
cached n5 data

### ISSUE THREAD

**Issue by d-v-b** [google/neuroglancer#181]
When using neuroglancer to view n5 data (in my case, served from the local filesystem), neuroglancer apparently maintains a cached version of the data -- i.e., when I delete the n5 files on disk, I can still view them in neuroglancer. Is there some configuration setting that prevents  this caching? It makes debugging very difficult if my changes to the n5 data on disk are not propagated to the viewer. Removing + recreating the image layer doesn't fix this, nor does clearing the browser cache.

**Comment by jbms** [comment]
Neuroglancer maintains its own cache in memory, but that is cleared by reloading the page (i.e. using your browser's Reload command).  There isn't currently a way to clear the cache from the UI, but the browser reload command is usually adequate for this purpose.  If that doesn't work, then there could be an issue with the cache headers sent by the server, but I'm guessing that is not the problem.

**Comment by d-v-b** [comment]
A page refresh solved the problem, thanks!
