### ISSUE TITLE
Displaying pixel values on mouse-over

### ISSUE THREAD

**Issue by chrisroat** [google/neuroglancer#184]
This could be related to the previous problem, but the pixel values are not showing for all channels when I mouse-over a pixel.  It is only showing a single channel.  (Unless I missed a new setting.)

Related to displaying pixel values, is there some way to fix the size of the boxes that display pixels?  With a lot of data sources with many channels, there can be a lot of movement do to the boxes changing sizes and the row of boxes wrapping.

I really appreciate your efforts on this project.

**Comment by jbms** [comment]
Thanks for reporting this.  This has been resolved for some months now.
