### ISSUE TITLE
pip install fails on Ubuntu 19.10

### ISSUE THREAD

**Issue by manuel-castro** [google/neuroglancer#191]
On a fresh Virtual environment in Python 3.7.5, pip install fails with the following message:
```
/tmp/pip-install-2xzoq38a/neuroglancer/ext/src/_neuroglancer.cc:9:10: fatal error: Python.h: No such file or directory
        9 | #include "Python.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by manuel-castro** [comment]
gcc version is 9.2.1

**Comment by jbms** [comment]
I think you may need to install the Python headers, e.g. the libpython-dev package.

**Comment by manuel-castro** [comment]
I forgot about this issue. I believe installing the python headers did fix this for me.
