### ISSUE TITLE
text labels for segmentation layer

### ISSUE THREAD

**Issue by d-v-b** [google/neuroglancer#199]
Is it possible to construct a segmentation layer with a mapping that assigns a name to each unique value in the underlying data?

**Comment by jbms** [comment]
Yes, via a segment property map defined using the precomputed format:

https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/segment_properties.md

See example here:
https://hemibrain-dot-neuroglancer-demo.appspot.com/#!gs://neuroglancer-janelia-flyem-hemibrain/v1.0/neuroglancer_demo_states/base.json

Note: The segmentation data itself does not need to be in the neuroglancer precomputed format, you can just add the segment property map as an additional data source.

**Comment by jbms** [comment]
Note: Ignore the "indexed" property type, that isn't implemented yet.

**Comment by jbms** [comment]
Depending on your use case, it might also make sense to define a new segment property map data source type, e.g. a DVID-backed one.

**Comment by d-v-b** [comment]
Thanks for the information, I'm not sure I grok it all yet. For context, my datasets are n5 arrays stored on s3. I will have between 0 and 60 text labels to map to the same number of integer values in the segmented volume. 

Are you saying that I would need to define a segment property map as a datasource backed by a new JSON file that contains the mapping between uint64 values in one of my segmented volumes? (I know the FlyEM team, so I can ask them about this if you think they can demonstrate this to me)

**Comment by jbms** [comment]
Yes, create a JSON file like:

https://neuroglancer-janelia-flyem-hemibrain.storage.googleapis.com/v1.0/rois/segment_properties/info

Then make sure it can be retrieved via a URL like:
https://whatever/path/info

(the filename must be `info`)

then add as a data source:

precomputed://https://whatever

If there is some convention for defining such maps as additional attributes within the n5 attributes.json file, then it would be easy enough to add support to Neuroglancer for that as well (then the map could be used automatically when you add the n5 data source).

**Comment by austinhoag** [comment]
@jbms what is your suggested method for hosting the segment properties JSON file? I only know about hosting precomputed datasets with cloudvolume, but since this info file is not of the right format for cloudvolume, then that is not an option.

**Comment by jbms** [comment]
You will have to write your own code to generate it, but that should be easy since the format is pretty simple.  If you are using Google Cloud Storage, you can upload it using gsutil or with one the Python libraries (e.g. boto or https://cloud.google.com/storage/docs/reference/libraries).

**Comment by austinhoag** [comment]
I wrote my own code to host the info file locally using flask, but Neuroglancer gives me a CORS error:
`Fetching "http://localhost:5005/info" resulted in HTTP error 0: Network or CORS error.` I verified that `curl http://localhost:5005/info` does give me the json body. I find the CORS error strange because I can successfully use cloudvolumes in Neuroglancer that are hosted locally and without https.

**Comment by jbms** [comment]
Using a local web server is fine, but you will need to set it up to send back the appropriate CORS headers.  I'm not sure specifically how to set that up with flask (though I did find this https://flask-cors.readthedocs.io/en/latest/).  As an example, you can use cors_webserver.py in the neuroglancer repository, or the node http-server package with the --cors option.

**Comment by austinhoag** [comment]
OK that worked in the sense that I no longer get a CORS error and can load in localhost:5000 as a layer with no errors. However, I don't see any segment property information showing up in my segmentation layer under the "Seg." tab. I have tried the example info file you referenced above and another one, but still no luck. I figured the problem with the example info file was that there was no "string" type property, so I added one in my example but that did not help. Is there an extra step required that I am missing? Here is the example info file I have tried in addition to the one referenced above: 
`{"@type": "neuroglancer_segment_properties", "inline": {"ids": ["1"], "properties": [{"id": "string", "type": "string", "values": ["AB(L)"]},{"id": "label", "type": "label", "values": ["AB(L)"]},{"id": "description", "type": "description", "values": ["AB(L)"]}]}}`

**Comment by austinhoag** [comment]
@d-v-b did you end up getting this working with a separate info JSON file defining the segment properties?

**Comment by manoaman** [comment]
> Yes, via a segment property map defined using the precomputed format:
> 
> https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/segment_properties.md
> 
> See example here:
> https://hemibrain-dot-neuroglancer-demo.appspot.com/#!gs://neuroglancer-janelia-flyem-hemibrain/v1.0/neuroglancer_demo_states/base.json
> 
> Note: The segmentation data itself does not need to be in the neuroglancer precomputed format, you can just add the segment property map as an additional data source.

Is there a template or an accessible example of `base.json` for segmentation properties?  I suppose gs://neuroglancer-janelia-flyem-hemibrain/v1.0/neuroglancer_demo_states/base.json is not accessible?

**Comment by jbms** [comment]
The base.json file is accessible, but it is just a Neuroglancer state:
https://storage.googleapis.com/neuroglancer-janelia-flyem-hemibrain/v1.0/neuroglancer_demo_states/base.json

Add a segment_properties member to the the `info` file for the segmentation:
http://storage.googleapis.com/neuroglancer-janelia-flyem-hemibrain/v1.0/rois/info

The value is the name of the sub-directory.

Then create the info file in the sub-directory specified by the segment_property key:

http://storage.googleapis.com/neuroglancer-janelia-flyem-hemibrain/v1.0/rois/segment_properties/info

**Comment by jbms** [comment]
@austinhoag I missed your comment earlier, but the additional step required for the segment properties to show up in the data source list is to reference it from your top-level info file via a "segment_properties" member.  See example in prior message.  You can also directly add the segment_properties as an additional data source to the layer, using the "+" button at the button of the Sources tab.

**Comment by manoaman** [comment]
> The base.json file is accessible, but it is just a Neuroglancer state:
> https://storage.googleapis.com/neuroglancer-janelia-flyem-hemibrain/v1.0/neuroglancer_demo_states/base.json
> 
> Add a segment_properties member to the the `info` file for the segmentation:
> http://storage.googleapis.com/neuroglancer-janelia-flyem-hemibrain/v1.0/rois/info
> 
> The value is the name of the sub-directory.
> 
> Then create the info file in the sub-directory specified by the segment_property key:
> 
> http://storage.googleapis.com/neuroglancer-janelia-flyem-hemibrain/v1.0/rois/segment_properties/info

@jbms I can't seem to load up "segment_properties" even after I created the sub-directory and info file.  And I have doubts where I'm placing the "segment_name_map": "names", "segment_property": "segment_properties" since they disappear after I apply the change to json on Neuroglancer.  (When I load this sub directory as a main source, I do see segmentation ids in the tab without the actual data.)  Would you be able to point out what I'm doing wrong here?  Thanks, -m

```
{
  "dimensions": {
    "x": [
      0.000025,
      "m"
    ],
    "y": [
      0.000025,
      "m"
    ],
    "z": [
      0.000025,
      "m"
    ]
  },
  "position": [
    240.36245727539062,
    170.15975952148438,
    0.5
  ],
  "crossSectionScale": 1.055028746424448,
  "crossSectionDepth": -5,
  "projectionOrientation": [
    0.20196738839149475,
    0.7169978022575378,
    -0.618348240852356,
    -0.25053688883781433
  ],
  "projectionScale": 82.81277574512146,
  "layers": [
    {
      "type": "segmentation",
      "source": [
        "precomputed://http://localhost:8888/precomputed/test_data",
        "mesh"
      ],
      "tab": "segments",
      "name": "segmented mesh",
      "segment_name_map": "names",      ----> (disappears)
      "segment_property": "segment_properties"   ----> (disappears)
    }
  ],
  "showSlices": false,
  "gpuMemoryLimit": 4000000000,
  "systemMemoryLimit": 4000000000,
  "selectedLayer": {
    "layer": "segmented mesh",
    "visible": true,
    "size": 290
  },
  "layout": "4panel",
  "statistics": {
    "size": 309
  }
}
```

**Comment by jbms** [comment]
segment_name_map is a remnant for an earlier version of the support in Neuroglancer.  Don't use that, just use "segment_properties".

segment_properties is not a property to be specified in the Neuroglancer JSON state (what you've posted above).  It is a property to set in the `info` file.   However, if you have your segment_properties info file available at:

http://localhost:8888/precomputed/test_data/segment_properties/info

Then if you don't want to add the segment_properties property to your `test_data/info` file, you can instead add:

precomputed://http://localhost:8888/precomputed/test_data/segment_properties

as an additional data source to the same layer in the Neuroglancer JSON state:

```json
...
  "layers": [
    {
      "type": "segmentation",
      "source": [
        "precomputed://http://localhost:8888/precomputed/test_data",
        "precomputed://http://localhost:8888/precomputed/test_data/segment_properties",
      ],
      "tab": "segments",
      "name": "segmented mesh",
    }
  ],
...
```

You can also add additional data sources in the UI:
![image](https://user-images.githubusercontent.com/4211946/101702688-319dc400-3a36-11eb-8187-2c65ec9234ae.png)

**Comment by manoaman** [comment]
> segment_name_map is a remnant for an earlier version of the support in Neuroglancer. Don't use that, just use "segment_properties".
> 
> segment_properties is not a property to be specified in the Neuroglancer JSON state (what you've posted above). It is a property to set in the `info` file. However, if you have your segment_properties info file available at:
> 
> http://localhost:8888/precomputed/test_data/segment_properties/info
> 
> Then if you don't want to add the segment_properties property to your `test_data/info` file, you can instead add:
> 
> precomputed://http://localhost:8888/precomputed/test_data/segment_properties
> 
> as an additional data source to the same layer in the Neuroglancer JSON state:
> 
> ```json
> ...
>   "layers": [
>     {
>       "type": "segmentation",
>       "source": [
>         "precomputed://http://localhost:8888/precomputed/test_data",
>         "precomputed://http://localhost:8888/precomputed/test_data/segment_properties",
>       ],
>       "tab": "segments",
>       "name": "segmented mesh",
>     }
>   ],
> ...
> ```
> 
> You can also add additional data sources in the UI:
> ![image](https://user-images.githubusercontent.com/4211946/101702688-319dc400-3a36-11eb-8187-2c65ec9234ae.png)

That works great!  Thanks @jbms Could I also ask how to open and use the bottom "select" UI?  I suppose it is to select coordinates in the viewer and pin to the dashboard?  I have not figured out the "Annotations" tab yet so I suppose it might be used for just picking a point versus cropping a volume in "Annotations" tab?

Thank you always for your help @jbms 
-m

<img width="392" alt="Screen Shot 2020-12-09 at 4 40 16 PM" src="https://user-images.githubusercontent.com/47464840/101706345-b93b0100-3a3d-11eb-8913-7480051cd11f.png">

**Comment by jbms** [comment]
Control right-click opens that panel.

**Comment by manoaman** [comment]
Agh, I see. I had to use a mouse instead of the track pad.  My track pad on mac keeps getting the following warning and I wasn't sure how to activate this.  Could I activate annotation tool without mouse?  But mouse right click seem to ok.  Thank you @jbms 

<img width="739" alt="Screen Shot 2020-12-10 at 9 17 38 AM" src="https://user-images.githubusercontent.com/47464840/101806479-de288600-3ac8-11eb-92b7-77222a3340c8.png">

**Comment by jbms** [comment]
Thanks for pointing out the issue with using control+rightclick on macOS.  I think the issue is that macOS converts rightclick to control+click and vice versa in some cases, because historically Apple shipped machines with just a single button mouse in order to accommodate users without multiple fingers, or something like that.  It appears that control+rightclick is getting translated to just control+leftclick, which is the annotate action.  I will have to look into an alternative binding that works on macOS.  Or perhaps you can check if there is already a way to trigger control+rightclick from the touchpad?

**Comment by manoaman** [comment]
I figured "control + two fingers" on the trackpad and that seem to pop up the GUI so I suppose that could work?

**Comment by manoaman** [comment]
Sorry, I had to ask this @jbms Does segment_properties support `color` attribute to assign fixed color code on each segmentation?  `l` key works great to reassign colors on each mesh but I was wondering if that is already supported.

Thanks, -m

https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/segment_properties.md

**Comment by jbms** [comment]
To be clear, control + two finger click already works on your trackpad?  If I get around to writing documentation, I'll include that.

Currently setting colors via precomputed segment_properties is not supported, but that would certainly make sense as a feature if you were interested in implementing it.  At the moment you can only assign colors using the `segmentColors` property of a segmentation layer in the Neuroglancer JSON state.

**Comment by manoaman** [comment]
yes, I've given a try and control + two finger click does work on my trackpad.
