### ISSUE TITLE
Questions on shaderControls feature

### ISSUE THREAD

**Issue by manoaman** [google/neuroglancer#205]
Hello,

I was trying to enable shader controls as demonstrated in this link but can't seem to figure out how to enable it.  Adding "shaderControls" to JSON does not seem to changes in brightness/contrast/max/min values applied to the layer specified.  How do I enable this feature and have GUI appear on Neuroglancer?  It would be great if you can point me to a document or snippet of code to enable this feature.

Thanks,

https://ara.viz.neurodata.io/#!%7B%22dimensions%22:%7B%22x%22:%5B0.00001%2C%22m%22%5D%2C%22y%22:%5B0.00001%2C%22m%22%5D%2C%22z%22:%5B0.00001%2C%22m%22%5D%7D%2C%22position%22:%5B564.9874267578125%2C389.4210510253906%2C550.264404296875%5D%2C%22crossSectionScale%22:1.822118800390506%2C%22projectionOrientation%22:%5B0.08078791946172714%2C0.8759221434593201%2C0.06809715181589127%2C-0.47074031829833984%5D%2C%22projectionScale%22:2048%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22precomputed://https://open-neurodata.s3.amazonaws.com/ara_2016/sagittal_25um/nissl_25um%22%7D%2C%22shaderControls%22:%7B%22color%22:%22#ef3030%22%2C%22min%22:0.39%2C%22max%22:0.17%2C%22brightness%22:0.3%2C%22contrast%22:-0.3%7D%2C%22opacity%22:0.03%2C%22blend%22:%22additive%22%2C%22name%22:%22nissl_25um%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22precomputed://https://open-neurodata.s3.amazonaws.com/ara_2016/sagittal_25um/average_25um%22%7D%2C%22shaderControls%22:%7B%22max%22:0.007%7D%2C%22opacity%22:1%2C%22blend%22:%22additive%22%2C%22name%22:%22average_25um%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%7B%22url%22:%22precomputed://https://open-neurodata.s3.amazonaws.com/ara_2016/sagittal_25um/annotation_25um_2017%22%7D%2C%22selectedAlpha%22:0.3%2C%22skeletonRendering%22:%7B%22mode2d%22:%22lines_and_points%22%2C%22mode3d%22:%22lines%22%7D%2C%22name%22:%22annotation_25um_2017%22%2C%22visible%22:false%7D%5D%2C%22selectedLayer%22:%7B%22layer%22:%22nissl_25um%22%2C%22visible%22:true%7D%2C%22layout%22:%224panel%22%7D

**Comment by jbms** [comment]
The reason the layer appears gray in your link is that the opacity is set to 0.03 --- if you increase it you will be able to see the data.

It does work for me to modify the shader controls in the JSON state --- perhaps the opacity was the only problem?

**Comment by manoaman** [comment]
Hi jbms,

Thanks for responding and I should've made more clear in the original question.  Yes, the shader control works on a provided link.  However, I couldn't figure out when I ran it locally with Docker.  How do I open this GUI panel from Neuroglancer?  I can't seem to find a document on displaying Source/Rendering/Annotations tab.  Which part of the code controls this part?  thanks

![Screen Shot 2020-03-09 at 4 45 49 PM](https://user-images.githubusercontent.com/47464840/76266794-e431c380-6225-11ea-83dc-71f9c7359374.png)

**Comment by xgui3783** [comment]
I believe you can open a layer specific control by either
- ctrl + click
- right click
the desired layer in the layer panel

**Comment by manoaman** [comment]
Thanks xgui3783, that did the trick.
