### ISSUE TITLE
Add all segments key binding

### ISSUE THREAD

**Issue by austinhoag** [google/neuroglancer#217]
I am trying to add a key binding to execute the action: add all segments in a given segmentation volume to the list of selected segments. The default is no selected segments and often users of my client want all segments to be rendered by default. I Have added a new case to `handleAction()` in `src/neuroglancer/segmentation_user_layer.ts` and have successfully registered the action so it logs to console when I hit the key it is bound to. I know how to add a segment, i.e. `this.displayState.rootSegments.add()`, but my problem is I cannot figure out how to get a list of all of the segments available in the volume to feed to that function. It seems the displaystate only keeps track of the current selected segments and does not store all of the possible segments. Is the list of all possible segments available within segmentation_user_layer.ts already?

**Comment by jbms** [comment]
In general the list of all segment IDs is simply not available.  Most of the data sources supported by neuroglancer do not provide that information, and for large volumes there could be billions of segment IDs, making it infeasible to select all of them anyway.

However, if there is an associated segment properties data source (https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/segment_properties.md) specifying a list of named segments (don't try to use the indexed properties, those are not actually supported yet), then that list of segments is available and you could add a key binding to select all of them.

**Comment by austinhoag** [comment]
I was able to figure out a way to do this in our fork: https://github.com/BrainCOGS/neuroglancer/commit/c2f4839595d4c5398b523d859082ee22a6a50330. I am not sure a pull request would be particularly helpful. In order for this key binding to work it requires one to be using atlas metadata (basically just labels for segments), which is specific to our fork. If there is something out of our fork that would be useful to be merged, I am happy to put together the necessary pull requests.

**Comment by austinhoag** [comment]
I was able to figure out a way to do this in our fork: https://github.com/BrainCOGS/neuroglancer/commit/c2f4839595d4c5398b523d859082ee22a6a50330. I am not sure a pull request would be particularly helpful. In order for this key binding to work it requires one to be using atlas metadata (basically just labels for segments), which is specific to our fork. If there is something out of our fork that would be useful to be merged, I am happy to put together the necessary pull requests.
