### ISSUE TITLE
Grid layout for python interface?

### ISSUE THREAD

**Issue by austinhoag** [google/neuroglancer#219]
I really like the row layout and column layout features of the python interface. I have not been able to figure out if it is possible to make a grid layout. For example, where I have two rows but the bottom row is split into two columns. My first thought was to try to combine them, but it looks like this is not possible because the children of a StackLayout (i.e. one of the rows) cannot be StackLayout objects (i.e. a column_layout) themselves. Is there a way around this?

**Comment by jbms** [comment]
A grid layout is indeed possible by adding a StackLayout as a child.  I added an example here:

https://github.com/google/neuroglancer/blob/master/python/examples/example_grid_layout.py
