### ISSUE TITLE
Are segment equivalences an appropriate application for this feature? 

### ISSUE THREAD

**Issue by austinhoag** [google/neuroglancer#222]
Can someone explain what segment equivalences is designed to accomplish?  I think knowing this may help guide me in the right direction.

What I am trying to do: I have an directed graph of segments defined by the Allen Mouse Brain Atlas: http://api.brain-map.org/api/v2/structure_graph_download/1.json. I also have a segmentation volume that represents these brain regions (where the "id" key in the JSON is the segment id) at a particular level in this graph that is quite fine grained. Often, it would be useful to view this volume at a different rank in the graph, for example viewing larger brain regions as a whole and not their very detailed child regions. Leaving this up to the user would be powerful for my application.

I am aware of the segment equivalences object in `src/neuroglancer/segmentation_user_layer.ts` and wondered if I could leverage this to do what I want. My first attempt has been to create a key binding (via the Python API because my graph object is easily accessible in python) to merge all child segments of a given (selected) parent with the parent id, effectively decreasing the rank of the ontology (for that branch in the graph only) by 1. Likewise I would like to add a key binding to unmerge a parent to its child segments, increasing the rank of the graph by 1. I have access to the graph in Python and I know how to get the segment id that is under the cursor, so it is a matter of telling Neuroglancer which segments are equivalent.

I started by experimenting with the Python API and found that I can somewhat control the segment equivalences list, e.g. to merge segment ID 59 with 599, I would use the following:
```python
with viewer.txn() as s:
    s.layers['atlas'].layer.equivalences = [(599,59)]
``` 
However, the first thing I noticed is the merge is unidirectional, i.e. the arrow that is displayed for the segment id in the neuroglancer layer item div always points from the smaller id number to the larger (59->599 in my example). For my feature, these equivalences need to be bidirectional because the parent id is not necessarily larger than the child id. 

This suggests to me that the segment equivalences object is not necessarily designed to do what I want. I have gone into the disjoint sets code a bit to try to see if I can hack it to do what I want, but ran into some more problems when trying to add more segments.

**Comment by jbms** [comment]
Segment equivalences were added to support agglomeration, e.g. to correct false splits using various workflows based on the Python integration.  It is based on a disjoint sets-type equivalence class model, rather than a hierarchy.  As you noticed, the equivalence class is identified by the minimum segment id that it contains.

A hierarchy would certainly also be useful, but there isn't really any specific support for that at the moment.  You may be able to nonetheless make the existing equivalences functionality work for you.  For example, you could ensure the parent ids are always lower than their children ids.
