### ISSUE TITLE
Making precomputed annotation layer

### ISSUE THREAD

**Issue by austinhoag** [google/neuroglancer#227]
For segmentation and image layers, I use cloudvolume to convert my data to precomputed format so that Neuroglancer can read it. Cloudvolume does not support conversion for annotation layers, so I am trying to find another way to do this. It is not clear to me what the precomputed layer folder would look like, i.e. the file format for the annotations and the format of the info file. I see that annotation layers can be saved in precomputed format, e.g.: `precomputed://gs://neuroglancer-janelia-flyem-hemibrain/v1.0/synapses`, but I don't know how to see the contents without cloudvolume: 
```python
from cloudvolume import CloudVolume
vol = CloudVolume('https://storage.googleapis.com/neuroglancer-janelia-flyem-hemibrain/v1.0/synapses')
```
but I get an error when I do this:
```python
KeyError: 'scales'
```
The cloudvolume maintainer has made it clear to me that annotation layers are not supported, so I am not surprised to see this.

**Comment by jbms** [comment]
Unfortunately, the only software we have at the moment for generating this format is based on a Google-internal C++ framework similar to Cloud Dataflow, and therefore can't suitable for open source release.

To view the raw data, you can simply use gsutil, e.g.:

gsutil ls gs://neuroglancer-janelia-flyem-hemibrain/v1.0/synapses

You can also refer to the documentation here:

https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md

**Comment by austinhoag** [comment]
Thanks for the info. I am interested in trying this simply for the reason that loading in point annotations via the python API or a CSV upload results in a very laggy viewer. I am using annotations to label cell centers, and I have order 10^5 cells. These cells can be independent points, not related in any way. Do you have any sense whether loading in these annotations via an annotation layer will change the responsiveness of the viewer? 

I am having a hard time understanding the hemibrane synapses annotation layer, even with access to the file contents of that layer directory. For example, it is not clear to me what these shard files are or how they are made. I see a broken link in the annotations.md doc regarding them: https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/sharding.md

**Comment by jbms** [comment]
Storing annotations in the Neuroglancer JSON state directly as you have
been doing, while convenient for a small number of annotations, is
unfortunately not very efficient for a large number of annotations.

The precomputed annotation format is multi-scale, and spatially indexed,
and should be able to handle essentially arbitrarily many annotations.  We
have used it with hundreds of millions of annotations, for example.  There
is a limit to how many points Neuroglancer can actually render at once with
a reasonable frame rate, but that is in the hundreds of thousands.

The correct link to the sharded format is here:
https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/sharded.md

For your use case, though, with only 10^5 points, you can avoid most of the
complexity of the precomputed annotation format and just write a single
chunk in non-sharded format.

In the end, you will have a directory tree with just two files, mirroring
the format and names of the following two files:

gs://neuroglancer-janelia-flyem-hemibrain/v1.0/synapses/info
gs://neuroglancer-janelia-flyem-hemibrain/v1.0/synapses/spatial0/0_0_0

You will write all of your annotations to the 0_0_0 file in the binary
format described here:
https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md#multiple-annotation-encoding

The info file you can strip down to just the following:

{
   "@type" : "neuroglancer_annotations_v1",
   "annotation_type" : "POINT",
   "by_id" : {
      "key" : "by_id"
   },
   "dimensions" : {
      "x" : [ 8e-09, "m" ],
      "y" : [ 8e-09, "m" ],
      "z" : [ 8e-09, "m" ]
   },
   "lower_bound" : [ 0, 0, 0 ],
   "properties" : [],
   "relationships" : [],
   "spatial" : [
      {
         "chunk_size" : [ 34422, 37820, 41362 ],
         "grid_shape" : [ 1, 1, 1 ],
         "key" : "spatial0",
         "limit" : 10000
      }
   ],
   "upper_bound" : [ 34422, 37820, 41362 ]
}

You should change chunk_size and upper_bound to equal the size in voxels of
your dataset, and adjust "dimensions" for your dataset.  This won't allow
indexing by annotation id or by associated segment id --- if you want that,
you will have to write additional files.  But this will be enough to
display the points in Neuroglancer.

**Comment by austinhoag** [comment]
OK, thank you that is incredibly helpful. I am trying the simple example you suggested.

I am unsure about how to encode a point position vector in binary format. For the `count` variable, I plan to do something like the following (in a simple example where I only have 2 point annotations that I want to add). Correct me if this is not going to work -- I have little experience writing binary files. The example is in python.  

```python
count=2
count_bytes=count.to_bytes(64,byteorder='little',signed=False)
```
But for the position vector, should I convert a tuple or list to bytes, or something else?

**Comment by jbms** [comment]
You can use the python struct module for encoding.

For example: struct.pack('<Q', 2)  to encode the number 2 as uint64le.

For float32le, struct.pack('<f', 0.5)

**Comment by austinhoag** [comment]
I see. I can now get annotations to show up and the viewer is indeed much more responsive than when storing the annotations in the JSON state even with 10^5 annotations. 

The code I used is:

```python
with open('0_0_0','wb') as outfile:
    total_count=len(coordinates) # coordinates is a list of tuples (x,y,z) 
    buf = struct.pack('<Q',total_count)
    for (x,y,z) in coordinates:
        pt_buf = struct.pack('<3f',x,y,z)
        buf+=pt_buf
    # write the ids at the end of the buffer as increasing integers 
    id_buf = struct.pack('<%sQ' % len(coordinates), *range(len(coordinates)))
    buf+=id_buf
    outfile.write(buf)
```

One thing that is unexpected is the spatial distribution of annotations does not match the spatial distribution of my coordinates in the z dimension only. x and y look fine. Here is a screenshot from loading in the precomputed layer via the binary `0_0_0` file I wrote with the above code:
![annotations_badspatial](https://user-images.githubusercontent.com/42473349/86152650-83791000-bace-11ea-9956-e015f4686b5b.png)

This is what the distribution of annotations looks like (and what the true distribution is) if I load them in via the JSON state: 
![annotations_goodspatial](https://user-images.githubusercontent.com/42473349/86152533-5167ae00-bace-11ea-942e-4fe1056cb345.png)

I can "fix" this by making the Spacing (cross section) and Spacing (projection) less than a certain value in the widget within the "Annotations" tab. I don't understand what these spacing values mean and why their default is making my annotations squished in the z dimension. 

For reference my info file is:
```
{
   "@type" : "neuroglancer_annotations_v1",
   "annotation_type" : "POINT",
   "by_id" : {
      "key" : "by_id"
   },
   "dimensions" : {
      "x" : [ 5e-06, "m" ],
      "y" : [ 5e-06, "m" ],
      "z" : [ 1e-05, "m" ]
   },
   "lower_bound" : [ 0, 0, 0 ],
   "properties" : [],
   "relationships" : [],
   "spatial" : [
      {
         "chunk_size" : [ 2160, 2560, 687 ],
         "grid_shape" : [ 1, 1, 1 ],
         "key" : "spatial0",
         "limit" : 10000
      }
   ],
   "upper_bound" : [ 2160, 2560, 687 ]
}
```
Where `2160,2560,687` is the volume size of the image layer and `dimensions` matches the `resolution` key of the image layer, i.e. 5x5x10 microns.

**Comment by jbms** [comment]
Neuroglancer "subsamples" by showing only a prefix of the list of
annotations according to the spacing setting.  If you set "limit" to 1 in
the info file, you won't get subsampling by default.  If you want the
subsampling to do something reasonable, then you can randomly shuffle the
order in which you write the annotations.

**Comment by austinhoag** [comment]
Got it, thanks for the help!

**Comment by donglaiw** [comment]
@jbms In addition to coordinates, is it possible to add the `props` attribute in the `0_0_0` binary file, so that it can store two types of points in one file (e.g., one for pre- and one for post-synapse)? Or how to implement this feature?

Thanks!

**Comment by jbms** [comment]
Yes you can encode properties as well, just refer to the format documentation.

I normally use a line segment annotation for synapses.  You can style the endpoints separately.

**Comment by donglaiw** [comment]
Got it. Thanks!

**Comment by spikeliu** [comment]
I have a question of how to arrange multiple properties in the annotation encoding (spatail index). Say I have 3 properties for POINT annotations, "cell_size" (float32), "cell_type" (uint16, range from 1 to 20) and "point_color" (rgba, for debugging, r=1, g=2, b=3, a=255). When I put the "cell_color" in the last position of the _**properties**_ entry in the json file, and use the following code for each point (padding a 2 bytes of zeros at last),
`struct.pack('<4fH4BH', x, y, z, cell_size, cell_type, r, g, b, a, 0)`
everthing goes well as shown below (as all alpha=255, the "cell_color" property becomes rgb style). 
![image](https://user-images.githubusercontent.com/5734885/132128143-5a743bac-3ba1-4c75-b890-6ec460eb5a2a.png)

But when I put rgba in the second postion in the _**properties**_ specification of the json file, and use the following code (the last **2B** can also be **H**),
`struct.pack('<4f4BH2B', x, y, z, cell_size, r, g, b, a, cell_type, 0, 0)`
the properties becomes weird shown in the figure below.
![image](https://user-images.githubusercontent.com/5734885/132127578-26f4f5d1-46ad-4e78-a3d0-9cd5cdaa9ede.png)
"cell_size" is normal, but "cell_color" and "cell_type" are not, channel r and g disappear, and b=3 becomes r channel, a=255 becomes g channel and "cell_type" becomes the b channel. I also try b_arr = pack('<2B', 1, 2) then unpack it as unpack('<H', b_arr), it is **513**, which is the actual "cell_type" show in the figure.
So, I wonder if a property type is rgba, does it have to be at last position of the corresponding array in the json specification. Or is there any detail I missed in the documentation?

**Comment by spikeliu** [comment]
Also, I think the color bar above is not correct too. For example, as in the first figure above, #010203 is very close to black, but #0203ff (ff is the alpha=255 channel) is close to the blue color as shown.

**Comment by jbms** [comment]
Regarding the color bar, thanks for reporting that issue, there was a bug in the display of RGBA colors, which is now fixed.

The issue with the property order is that the order in which the properties must be encoded is not the same as the order in which the properties are specified in the `info` file, as described here:
https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md#single-annotation-encoding

In order to minimize the padding bytes required, properties that require 4 byte alignment (uint32, int32, float32) are encoded first, followed by properties that require 2 byte alignment (uint16, int16), followed by properties that require 1 byte alignment (uint8, int8, rgb, rgba).  For a given alignment, the properties are encoded in which the properties are specified in the `info` file.

So in your case, the encoding will be same regardless of the order in which the properties are specified in the `info` file.

**Comment by austinhoag** [comment]
Hi Jeremy,

I have been using precomputed layers with a single spatial index successfully thanks to your help earlier in this thread. I have started getting requests to load millions or tens of millions of annotations in a single precomputed layer. Without spatial indexing this is starting to get slow, so I am looking at the documentation to create multiple spatial indexes.  https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md#spatial-index

I think I understand the basic idea here. I do have a few questions though. 

1. It's not explicitly said in your instructions, but I am assuming that for each cell (aka "chunk") at each spatial index, you write out a file in the spatial folder for that index, using 0-indexing for the cell numbers. For example if I am on spatial level 1 and have grid_shape=[2,1,1] I would have two chunks: [0,0,0] and [0,1,1] and those would be written out as: `spatial1/0_0_0` and `spatial1/1_0_0`. Is that correct?
2. I'm also not sure about what the order of the annotations needs to be in each of these chunk files. In your instructions referenced above you say the order should be bit-reserved morton code (not sure what that is). But at the end of this section: https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md#multiple-annotation-encoding you say to order them randomly. Can you clarify? 
3. When picking the subsets of annotations in each cell, your instructions state:

"Compute a subset emitted(level, cell) of remaining_annotations(0, cell) where each annotation is chosen uniformly at random with probability min(1, limit / maxCount(level))"

Let's say for example we have 10^6 annotations and we're calculating the subset emitted for level 0 for which we only have one cell 0_0_0. maxCount(level=0) = 10^6 since that is the total number of cells in this volume. And say we're using a limit of 10^4. The probability of selecting each annotation is then 10^4/10^6 = 0.01. Is this equivalent to just picking 10^4 of the total 10^6 annotations at random? I guess this `min()` function ensures that the limit is enforced since you'll never fill a cell with more than 10^4 annotations. And in the case where maxCount() is less than the limit you will pick all of annotations. Is that right?

**Comment by jbms** [comment]
1. There are two formats supported: unsharded and sharded:
https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md#unsharded-spatial-index
https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md#unsharded-spatial-index
For unsharded the format is indeed as you have described.
2. They should be ordered randomly; the bit-reversed morton code was an initial experiment I tried to produce a more spatially-distributed set of annotations, but it turned out to be a bad idea since it distorted the distribution.  I have corrected the documentation in the annotations.md file.  Thanks for pointing this out.
3. If you have just a single cell (e.g. at spatial0 level), it is indeed the same as just picking 10^4 annotations at random to include in the first level, and retain the remaining for the later levels.  However, once you have more than one cell, you need to retain the same proportion of annotations in all cells, in order to avoid distorting the distribution.  For example, suppose at level 1 you have two grid cells in total, and there might happen to be 10^5 annotations in cell 0 but only 10^4 annotations in cell 1.  To achieve the desired limit of 10^4 annotations, you need to subsample only 10% of the annotations in each cell, such that you end up with 10^4 annotations selected for cell 0 and 10^3 annotations selected for cell 1.  When displayed in Neuroglancer, cell 0 will show 10x as many annotations as cell 1, which will correctly preserve the distribution.  If instead you just picked 10^4 annotations for each cell, then the same number of annotations would be shown in both cells, giving the appearance that the density is the same in both cells.

**Comment by jbms** [comment]
Note: In principle it would be possible to sample with different ratios in each cell, so that every cell gets to its limit if possible, and then record the sampling ratio that was used for each cell, so that Neuroglancer can take it into account.  However, that is not supported by the current format, so instead we must use a uniform sampling rate.

**Comment by austinhoag** [comment]
That makes sense, thanks for the prompt reply.

**Comment by austinhoag** [comment]
I was able to generate a spatially indexed precomputed layer from ~10^6 point annotations. I used limit=10^4. It does load very fast in Neuroglancer in comparison to using only a single spatial index, so that's good. However, the subsampling seems significantly higher in the multi-spatial index layer, i.e. there are way fewer points displayed at any given zoom level. The screenshot below shows the single spatial index layer (yellow points) with limit=10^4 and the multi-spatial index layer (red points) also with limit=10^4.
![Screenshot from 2021-09-10 09-56-25](https://user-images.githubusercontent.com/42473349/132865162-0e02b281-60cb-4512-81f4-858a48128373.png)


Is this expected? I am in particular concerned that when zoomed in the multi-spatial index does not show that many points -- the user needs to be able to see ALL of the annotations when zoomed way in since the primary use case is validating detected cells. I also tried a limit=1 multi-spatial index layer (as you suggested earlier in the thread for no subsampling in the single-index layer case) and it shows even fewer points overall. It is possible I implemented the spatial indexing algorithm incorrectly.

**Comment by JoeStrout** [comment]
Thank you for this helpful thread.  I'm trying to implement writing of annotation collections now, and I'm confused by this bit:

> Neuroglancer "subsamples" by showing only a prefix of the list of annotations according to the spacing setting.  If you set "limit" to 1 in the info file, you won't get subsampling by default.

How is the size of the prefix (subsample) shown determined?  Experimentally, with the same 100 line annotations in my 0_0_0 index, I find:

	Limit = 10000  →  all 100 lines shown
	Limit = 50000  →  64 lines shown
	Limit = 100000  →  32 lines shown
	Limit = 200000  →  16 lines shown
	Limit = 400000 →  8 lines shown

I imagine it's doing some calculation of the total number of lines it might see by multiplying "limit" by the number of chunks, and trying to pick a reasonable prefix (subsample) size.  But when there's only one chunk, I would expect that calculation to come out to some constant value, like 1000 annotations.  I can't understand why the lines shown is actually shrinking with increasing limit, or why it's OK to lie about the limit value (documented as "the maximum number of annotations per grid cell") in order to avoid this subsampling.

**Comment by jbms** [comment]
Note: It is clear now that the subsampling is somewhat confusing and we probably need to somehow improve how it is handled to be less confusing.

The idea is that the "Resolution" setting in the UI specifies a limit on the density (in screen space) of annotations that is desired.  Neuroglancer then tries to ensure that this limit is met within the *densest* chunk, the one with `limit` annotations --- other areas may be less dense.

Based on the current camera parameters and the assumption that annotations are uniformly distributed with each chunk, Neuroglancer determines the desired density of annotations, then multiplies this density by the chunk volume at the current spatial index level (initially the top-most/coarsest level).  The fraction of annotations to subsample is given by `desired_number_of_annotations / limit` (clamped to not exceed 1).  Note that by setting limit to 1, this will always equal 1, i.e. no subsampling.  Then we subtract the density obtained from this spatial index level from the desired density, and if the desired density is still greater than 0 (can only occur if we didn't do any subsampling at this level), continue with the next spatial index level, until either there is no finer spatial index level or the desired density is reached.
