### ISSUE TITLE
n5 + uint64

### ISSUE THREAD

**Issue by d-v-b** [google/neuroglancer#228]
Using n5, uint64 volumes seem to be unviewable, but uint32 works. 

```python
from numcodecs import GZip
import numpy as np
import zarr
testdata = np.random.randint(0, 255, (64,64,64), dtype='uint32')

# this dataset renders properly in neuroglancer
arr_uint32 = zarr.open('test.n5', path='/uint32', mode='w', shape=testdata.shape, dtype=testdata.dtype,compressor=GZip(-1))
arr_uint32[:] = testdata

# this dataset does not get rendered properly, and the pixel intensities are inaccurately reported when mousing over the volume
arr_uint64 = zarr.open('test.n5', path='/uint64', mode='w', shape=testdata.shape, dtype='uint64',compressor=GZip(-1))
arr_uint64[:] = testdata.astype('uint64')
```

Is there anything special I should be doing to get uint64 volumes working properly?

**Comment by jbms** [comment]
Thanks for reporting this issue.  It should be fixed now.

**Comment by d-v-b** [comment]
Thanks for getting this fixed so fast. Is the demo up at appspot kept up to date with master?

**Comment by jbms** [comment]
I did update neuroglancer-demo.appspot.com and you should find that hovering the mouse shows the correct values, but note that the uint64 data not rendering is a separate issue:

you have to specify a custom shader for uint64 data.

E.g.

```glsl
void main() {
  emitGrayscale(float(getDataValue().value[0]) / 255.0);
}
```
