### ISSUE TITLE
selected layer segmentation tab in screenshot

### ISSUE THREAD

**Issue by austinhoag** [google/neuroglancer#233]
I am interested in including the right side panel in a screenshot. This seems to be disabled. It is possible to toggle its visibility? I am taking the screenshot with the python API (pip version: 2.8) using: `neuroglancer.ScreenshotSaver()`. Specfically:
```python
viewer = neuroglancer.Viewer()
ss = ng.ScreenshotSaver(viewer, '.')
with viewer.txn() as s:
    ss.capture()
```

 I have ensured that the right panel is visible in the browser window before I issue the `capture()` method in python. It is the side panel for a segmentation layer and I have the "Seg." tab selected with a few segments selected so that I can see their segment properties. The right panel is acting like a key for the selected segments that are displayed in the viewer.

I thought it might be due to a property of the `viewer.config_state` being switched before the screenshot is taken, like what happens in this block: https://github.com/google/neuroglancer/blob/3db0fa6b46d72aeac0ea71412d8ab62ead328efb/python/neuroglancer/viewer_base.py#L107

but I don't see any parameter in `config_state` for controlling this. It looks like the side panel can be activated via something like: 
```python
with viewer.txn() as s:
    s.selected_layer.layer = 'segmentation_layer_name' 
    s.selected_layer.visible = True
    s.selected_layer.size = 400
```
But whether I use the code above or open the right panel manually I still get the same result. 

The screenshot that gets taken just has the background color where the side panel should be. I can provide my screenshot if this is not reproducible on your end.

**Comment by jbms** [comment]
The screenshot function in the Python API only captures what is rendered by WebGL to the canvas element, so the UI elements are excluded.

If you want to automate capturing a screenshot with the UI elements as well, you could use selenium to control the browser and capture a screenshot using it's screenshot function.  See the neuroglancer.webdriver module, which provides some basic support for running neuroglancer via selenium.

**Comment by austinhoag** [comment]
Great, thanks that works.
