### ISSUE TITLE
Exporting local annotations to CSV

### ISSUE THREAD

**Issue by austinhoag** [google/neuroglancer#236]
I am interested in adding a button in the annotation side panel to export local annotations to a CSV file that the user can download locally. This is something the Seung lab fork has accomplished: https://github.com/seung-lab/neuroglancer/pull/272/files, but I haven't been able to port this functionality over to this fork just yet due to some differences. 

I want the button to appear under the annotation toolbox div, so I added the new button div to the `AnnotationLayerView` class constructor right after the toolbox div in `src/neuroglancer/ui/annotations.ts`:
```
// your existing code
const toolbox = document.createElement('div');
toolbox.className = 'neuroglancer-annotation-toolbox';
// my new code
const exportToCSVButton = document.createElement('button');
exportToCSVButton.id = 'exportToCSVButton';
exportToCSVButton.textContent = 'Export to CSV';
exportToCSVButton.addEventListener('click', () => {
    this.exportToCSV();
      });
```
In my `exportToCSV()` function I am having trouble accessing the annotations like what is done in the Seung Lab's fork to write the CSV file with content. For example:
```
private exportToCSV() {
  let csvString = 'Coordinates,Tags,Description,Segment IDs\n';
  for (const annotation of this.annotationLayer.source) {
      // add the annotation properties to csvString
     ... 
  }
  ....
}
```
does not work because the annotation layer structure is different between the two forks. I have tried to find an equivalent way of doing this but I think I am getting a little lost in states and source objects, and I figure there is a more direct way I am failing to see. What is the best way to get the annotation objects such that I can access their properties like position, linked segments, etc...?

**Comment by austinhoag** [comment]
I was able to get access to the annotation objects via:
```
 for (const [state, ] of self.attachedAnnotationStates) {
      for (const annotation of state.source) {
          ...
      }
      ...
}

```

**Comment by austinhoag** [comment]
I would also like to include the segment property names in this csv file (something the Seung Lab's fork does not use), if they are provided. I am having trouble accessing the segment name given the ID in my function `private exportToCSV()` in `src/neuroglancer/ui/annotations.ts`. I see that elsewhere in this file you reference the segmentLabelMap: https://github.com/google/neuroglancer/blob/master/src/neuroglancer/ui/annotations.ts#L1419. However, it's not clear to me how I would gain access to the segmentationDisplayState (which is needed to get the label map) from within the `AnnotationLayerView` class, i.e. where my  `exportToCSV()` function needs to be defined. Is this possible?

**Comment by jbms** [comment]
AnnotationLayerView:

displayState member (type AnnotationDisplayState) -> relationshipStates -> get(relationshipName) -> segmentationState -> value -> segmentLabelMap

**Comment by austinhoag** [comment]
Hmm, I don't follow what you mean there. Using the latter part of those relationships, I was able to access the segmentLabelMap attribute, but it is coming back as undefined. I made sure the segmentation layer has a segment properties file loaded and I can see the property names in the viewer. 
```
let annotationLayer = this.annotationStates.states[0];
const {relationships} = annotationLayer.source;
for (let i = 0, count = relationships.length; i < count; ++i) {
  const relationship = relationships[i];
  let segmentationState = 
    annotationLayer.displayState.relationshipStates.get(relationship).segmentationState
  console.log(segmentationState.value?.segmentLabelMap); // returns undefined
}
```
There is only one loop iteration when I do this and the relationship is "segments"

**Comment by jbms** [comment]
Works for me when the "annotation" layer is linked with the "segmentation" layer via the "segments" relationship:

annotationLayerView.displayState.relationshipStates.get("segments").segmentationState.value.segmentLabelMap.value

http://localhost:8081/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B8e-9%2C%22m%22%5D%7D%2C%22position%22:%5B14894.728515625%2C20126.095703125%2C20566.439453125%5D%2C%22crossSectionScale%22:2.8863709892679594%2C%22projectionScale%22:68248.6782991376%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/emdata/clahe_yz/jpeg%22%2C%22tab%22:%22source%22%2C%22name%22:%22image%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/v1.1/segmentation%22%2C%22tab%22:%22source%22%2C%22name%22:%22segmentation%22%7D%2C%7B%22type%22:%22annotation%22%2C%22source%22:%7B%22url%22:%22local://annotations%22%2C%22transform%22:%7B%22outputDimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B8e-9%2C%22m%22%5D%7D%7D%7D%2C%22tool%22:%22annotatePoint%22%2C%22annotations%22:%5B%5D%2C%22ignoreNullSegmentFilter%22:false%2C%22linkedSegmentationLayer%22:%7B%22segments%22:%22segmentation%22%7D%2C%22filterBySegmentation%22:%5B%22segments%22%5D%2C%22name%22:%22annotation%22%7D%5D%2C%22selectedLayer%22:%7B%22layer%22:%22annotation%22%2C%22visible%22:true%7D%2C%22layout%22:%224panel%22%7D

If the "annotation" layer is not linked to the "segmentation" layer via the "segments" relationship, then segmentationState.value is undefined.

**Comment by austinhoag** [comment]
Oh strange I thought I had linked the layer in that example but I guess I had not. It works now if I ensure that the annotation layer is linked to the segmentation layer. 

Thanks!
