### ISSUE TITLE
Combining channels in n5/Zarr

### ISSUE THREAD

**Issue by perlman** [google/neuroglancer#238]
I am working with Zarr images stored in a format approximating the upcoming [ome-zarr](https://github.com/ome/omero-ms-zarr/blob/master/spec.md) spec.

The data are being stored in (t, c, z, y, x) order. The transformation matrix works well for mapping into proper x,y,z coordinates for viewing in neuroglancer.

My quick & dirty hack was to deal with the channels was to create 3 data sources, each with a channel offset and corresponding shader. [Here is an example](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22d0%22:%5B1%2C%22%22%5D%2C%22d1%22:%5B1%2C%22%22%5D%2C%22d2%22:%5B1%2C%22%22%5D%2C%22d3%22:%5B1%2C%22%22%5D%2C%22d4%22:%5B1%2C%22%22%5D%7D%2C%22position%22:%5B1392.93896484375%2C524.7988891601562%2C0.5%2C2.5%2C0.5%5D%2C%22crossSectionScale%22:1.5732241069496449%2C%22projectionOrientation%22:%5B-0.00270150532014668%2C0.0012271798914298415%2C0.00000331524756802537%2C0.9999955892562866%5D%2C%22projectionScale%22:8192%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr://https://www.yikes.com/~eric/test/hello.zarr/0/0%22%2C%22transform%22:%7B%22matrix%22:%5B%5B0%2C0%2C0%2C0%2C1%2C0%5D%2C%5B0%2C0%2C0%2C1%2C0%2C0%5D%2C%5B0%2C0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%2C0%5D%2C%5B1%2C0%2C0%2C0%2C0%2C0%5D%5D%2C%22outputDimensions%22:%7B%22d0%22:%5B1%2C%22%22%5D%2C%22d1%22:%5B1%2C%22%22%5D%2C%22d2%22:%5B1%2C%22%22%5D%2C%22d3%22:%5B1%2C%22%22%5D%2C%22d4%22:%5B1%2C%22%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22opacity%22:1%2C%22blend%22:%22additive%22%2C%22shader%22:%22void%20main%28%29%20%7B%20emitRGB%28vec3%28toNormalized%28getDataValue%28%29%29%2C%200.0%2C%200.0%29%29%3B%20%7D%22%2C%22name%22:%22r%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr://https://www.yikes.com/~eric/test/hello.zarr/0/0%22%2C%22transform%22:%7B%22matrix%22:%5B%5B0%2C0%2C0%2C0%2C1%2C0%5D%2C%5B0%2C0%2C0%2C1%2C0%2C0%5D%2C%5B0%2C0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%2C1%5D%2C%5B1%2C0%2C0%2C0%2C0%2C0%5D%5D%2C%22outputDimensions%22:%7B%22d0%22:%5B1%2C%22%22%5D%2C%22d1%22:%5B1%2C%22%22%5D%2C%22d2%22:%5B1%2C%22%22%5D%2C%22d3%22:%5B1%2C%22%22%5D%2C%22d4%22:%5B1%2C%22%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22opacity%22:1%2C%22blend%22:%22additive%22%2C%22shader%22:%22void%20main%28%29%20%7B%20emitRGB%28vec3%280.0%2C%20toNormalized%28getDataValue%28%29%29%2C%200.0%29%29%3B%20%7D%22%2C%22name%22:%22g%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr://https://www.yikes.com/~eric/test/hello.zarr/0/0%22%2C%22transform%22:%7B%22matrix%22:%5B%5B0%2C0%2C0%2C0%2C1%2C0%5D%2C%5B0%2C0%2C0%2C1%2C0%2C0%5D%2C%5B0%2C0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%2C2%5D%2C%5B1%2C0%2C0%2C0%2C0%2C0%5D%5D%2C%22outputDimensions%22:%7B%22d0%22:%5B1%2C%22%22%5D%2C%22d1%22:%5B1%2C%22%22%5D%2C%22d2%22:%5B1%2C%22%22%5D%2C%22d3%22:%5B1%2C%22%22%5D%2C%22d4%22:%5B1%2C%22%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22opacity%22:1%2C%22blend%22:%22additive%22%2C%22shader%22:%22void%20main%28%29%20%7B%20emitRGB%28vec3%280.0%2C%200.0%2C%20toNormalized%28getDataValue%28%29%29%29%29%3B%20%7D%22%2C%22name%22:%22b%22%7D%5D%2C%22crossSectionBackgroundColor%22:%22#000000%22%2C%22layout%22:%22xy%22%7D).

I tried to do this as subsources, but could not figure out how to get a shader to differentiate the sources (e.g. `getDataValue(N)`)

Is there a better method to map one of the dimensions to be the special 'channel' dimension used in shaders?

**Comment by jbms** [comment]
You can treat a dimension as a "channel" dimension by renaming it to end in "^", i.e. "c^".  However, Neuroglancer currently only supports that if the dimension is unchunked, i.e. the chunk size is equal to the full extent of the dimension; for your example dataset, the extent of the "c" dimension is 4 but the chunk size is 1, so it can't be displayed.

Potentially this limitation could be removed, though.

[Example showing error](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22d0%22:%5B1%2C%22%22%5D%2C%22d1%22:%5B1%2C%22%22%5D%2C%22d2%22:%5B1%2C%22%22%5D%2C%22d4%22:%5B1%2C%22%22%5D%7D%2C%22position%22:%5B1392.93896484375%2C524.7988891601562%2C0.5%2C0.5%5D%2C%22crossSectionScale%22:1.5732241069496449%2C%22projectionOrientation%22:%5B-0.00270150532014668%2C0.0012271798914298415%2C0.00000331524756802537%2C0.9999955892562866%5D%2C%22projectionScale%22:8192%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr://https://www.yikes.com/~eric/test/hello.zarr/0/0%22%2C%22transform%22:%7B%22matrix%22:%5B%5B0%2C0%2C0%2C0%2C1%2C0%5D%2C%5B0%2C0%2C0%2C1%2C0%2C0%5D%2C%5B0%2C0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%2C0%5D%2C%5B1%2C0%2C0%2C0%2C0%2C0%5D%5D%2C%22outputDimensions%22:%7B%22d0%22:%5B1%2C%22%22%5D%2C%22d1%22:%5B1%2C%22%22%5D%2C%22d2%22:%5B1%2C%22%22%5D%2C%22c%5E%22:%5B1%2C%22%22%5D%2C%22d4%22:%5B1%2C%22%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22opacity%22:1%2C%22blend%22:%22additive%22%2C%22shader%22:%22void%20main%28%29%20%7B%20emitRGB%28vec3%28toNormalized%28getDataValue%28%29%29%2C%200.0%2C%200.0%29%29%3B%20%7D%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22r%22%7D%5D%2C%22selectedLayer%22:%7B%22layer%22:%22r%22%2C%22visible%22:true%7D%2C%22crossSectionBackgroundColor%22:%22#000000%22%2C%22layout%22:%22xy%22%7D)

**Comment by perlman** [comment]
I had success using `c^` on a new image with a chunk size including the full extent of channels & using an `emitRGB(...)` shader. Thanks!

(This would be a nice feature for directly viewing images generated by [omero-cli-zarr](https://github.com/ome/omero-cli-zarr), but it's probably not worth the effort until the `ome-zarr` spec is stable.)
