### ISSUE TITLE
Neuroglancer system requirement

### ISSUE THREAD

**Issue by AbsolemPillar** [google/neuroglancer#244]
is there a specific hardware system requirement for using Neuroglancer on a mac?

thanks,

**Comment by jbms** [comment]
It requires WebGL2 support in your browser (see e.g. https://webglreport.com) and note that it only works with Chrome or Firefox.  In general I would expect it to work on Macs from the last 5 years at least.  Are you running into a particular problem?

**Comment by AbsolemPillar** [comment]
thank you, no I'm not running into any particular problem. planning to get a mac but I couldn't find the system requirement just want make i have enough hardware to run the Neuroglancer. many thank you for your help.
