### ISSUE TITLE
#uicontrol sliders not rendering properly under FireFox

### ISSUE THREAD

**Issue by perlman** [google/neuroglancer#245]
The range part of the slider is not currently showing up under FireFox 80 on MacOS. This is purely cosmetic. The controls continue to function.

[example](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1%2C%22%22%5D%2C%22y%22:%5B1%2C%22%22%5D%2C%22z%22:%5B1%2C%22%22%5D%2C%22c%22:%5B1%2C%22%22%5D%2C%22t%22:%5B1%2C%22%22%5D%7D%2C%22position%22:%5B134.74122619628906%2C142.1988067626953%2C120.5%2C0.5%2C0.5%5D%2C%22crossSectionScale%22:0.5220927770163193%2C%22projectionOrientation%22:%5B-0.024500180035829544%2C-0.42064404487609863%2C-0.00928647443652153%2C0.906847357749939%5D%2C%22projectionScale%22:551.2009490847719%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr://https://idr-s3.openmicroscopy.org/idr/outreach/55204.zarr/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B0%2C0%2C0%2C0%2C1%2C0%5D%2C%5B0%2C0%2C0%2C1%2C0%2C0%5D%2C%5B0%2C0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%2C0%5D%2C%5B1%2C0%2C0%2C0%2C0%2C0%5D%5D%2C%22outputDimensions%22:%7B%22x%22:%5B1%2C%22%22%5D%2C%22y%22:%5B1%2C%22%22%5D%2C%22z%22:%5B1%2C%22%22%5D%2C%22c%22:%5B1%2C%22%22%5D%2C%22t%22:%5B1%2C%22%22%5D%7D%7D%7D%2C%22opacity%22:1%2C%22shader%22:%22#uicontrol%20vec3%20color%20color%28default=%5C%22white%5C%22%29%5Cn#uicontrol%20float%20min%20slider%28min=0%2C%20max=1.0%2C%20default=1.0%29%5Cn#uicontrol%20float%20max%20slider%28min=0%2C%20max=1.0%2C%20default=1.0%29%5Cn%5Cnfloat%20scale%28float%20x%29%20%7B%5Cn%20%20return%20%28x%20-%20min%29%20/%20%28max%20-%20min%29%3B%5Cn%7D%5Cnvoid%20main%28%29%20%7B%5Cn%20%20emitRGB%28%5Cn%20%20%20%20color%20%2A%20vec3%28%5Cn%20%20%20%20%20%20scale%28toNormalized%28getDataValue%28%29%29%29%2C%5Cn%20%20%20%20%20%20scale%28toNormalized%28getDataValue%28%29%29%29%2C%5Cn%20%20%20%20%20%20scale%28toNormalized%28getDataValue%28%29%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%3B%5Cn%7D%22%2C%22shaderControls%22:%7B%22min%22:0%2C%22max%22:0.04%7D%2C%22crossSectionRenderScale%22:0.6754693741238369%2C%22name%22:%2255204.zarr%22%7D%5D%2C%22selectedLayer%22:%7B%22layer%22:%2255204.zarr%22%2C%22visible%22:true%2C%22size%22:697%7D%2C%22layout%22:%224panel%22%7D)

FireFox:
![image](https://user-images.githubusercontent.com/671841/93220296-4d951080-f73a-11ea-8b4b-dd49ef1608ce.png)

Chrome:
![image](https://user-images.githubusercontent.com/671841/93220318-571e7880-f73a-11ea-8acb-d36a38e9039a.png)

**Comment by jbms** [comment]
I don't see the same issue in Firefox 80 on Linux.  There isn't much styling applied to those sliders:

![slider-css](https://user-images.githubusercontent.com/4211946/93244411-8afb9d00-f73e-11ea-96f0-da1d008defc3.png)

I don't have a Mac to easily look into this --- perhaps you can try adjusting the styles and see what fixes it?

Perhaps the issue is that the slider bar is black on Mac OS and therefore can't be seen against the black background?

**Comment by perlman** [comment]
The slider bar appears to be a transparent gray, visible by changing the black background to white.
I will play around with styles to see if I can find something less drastic.

This occurs with FireFox 81 as well, and in both dark & light modes.
