### ISSUE TITLE
Use the same colorSeed for all visible layers when recoloring

### ISSUE THREAD

**Issue by stuarteberg** [google/neuroglancer#249]
With the convenient "recolor" shortcut (`l`), I don't have to tolerate unlucky color maps when I'm inspecting adjacent objects.

Sometimes I've loaded two layers whose IDs are meant to correspond.  That is, I want label 123 in layer A to have the same color as label 123 in layer B.  But the "recolor" shortcut chooses a new `colorSeed` for every visible layer, causing the color maps for layers A and B to become out-of-sync.

It would be nice if only a single new `colorSeed` were chosen and applied to all visible layers uniformly.  That way, matching label IDs in different layers will always have matching colors.

Just to illustrate the point, here are some screenshots showing two different layers with corresponding label IDs.

<details>

<summary>Screenshots</summary>

Layer A:

<img width="50%" height="50%" alt="image" src="https://user-images.githubusercontent.com/1655821/94460986-834ce700-0187-11eb-849d-ddb2eae311a4.png">

Layer B:

<img width="50%" height="50%" alt="image" src="https://user-images.githubusercontent.com/1655821/94460949-76c88e80-0187-11eb-8325-655afc7b017b.png">

Composite view looks good:

<img width="50%" height="50%" alt="image" src="https://user-images.githubusercontent.com/1655821/94461010-8cd64f00-0187-11eb-961d-8b4c330649cc.png">

But after recoloring, the colors no longer correspond:

<img width="50%" height="50%" alt="image" src="https://user-images.githubusercontent.com/1655821/94461078-a4add300-0187-11eb-8662-0381b2e264d4.png">

</details>

**Comment by jbms** [comment]
I think your proposed solution makes sense, as a simple change that would solve the problem and not break anything.  Alternatively there could be an explicit mechanism for linking the color seeds and/or selected segments of one layer to another, but that would be a lot more complicated.

**Comment by moenigin** [comment]
It has been very helpful for me to have objects with the same id from different layers colored differently. E.g. to compare different skeleton versions and/or overlaying them with the volume segmentation. It would be cool if this was still an option...

**Comment by stuarteberg** [comment]
In the current implementation, all layers start with the default color seed, so they start with matching colors.  Then, if you hit the "recolor" shortcut, all visible layers end up with different color seeds (and non-visible layers retain the default color seed).  I guess that's what you're doing.

Under the proposed solution, the color seeds would be kept in-sync for *currently visible layers only*.  So, to bring one (and only one) layer's color seed out-of-sync with respect to the other layers, you would have to temporarily hide the other layers before hitting the "recolor" shortcut.

**Comment by moenigin** [comment]
that sounds good! thanks!

**Comment by stuarteberg** [comment]
In 0dc46773f98b4358e9310dadbf4b4bf7c0807056, Jeremy implemented the idea he described above:

>there could be an explicit mechanism for linking the color seeds and/or selected segments of one layer to another

It works great!  Closing this issue.
