### ISSUE TITLE
incompatible with python3.8?

### ISSUE THREAD

**Issue by moenigin** [google/neuroglancer#253]
Hi,

I created a new conda env and installed only neuroglancer using pip and tried to run this:
```
import neuroglancer
import webbrowser
from threading import Event

keep_server_alive = Event()
viewer = neuroglancer.Viewer()

with viewer.txn() as s:
    s.layers['raw'] = neuroglancer.ImageLayer(
        source='brainmaps://280984173682:adultob:raw')
    s.layers['seg'] = neuroglancer.SegmentationLayer(
        source='brainmaps://487208920048:adultob:seg_v2_9nm_484558417fb_18nm_fb_107004781_otfa:200614_prj487208920048_graph_postapr'
    )
    s.layout = 'xy-3d'
    s.showSlices = False

if __name__ == '__main__':
    webbrowser.open_new(viewer.get_viewer_url())
    keep_server_alive.wait()
```

which resulted in this error:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Utilities\Anaconda\envs\cls_neurons\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Utilities\Anaconda\envs\cls_neurons\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Utilities\Anaconda\envs\cls_neurons\lib\site-packages\neuroglancer\server.py", line 306, in start_server
    global_server = Server(ioloop=ioloop, **global_server_args)
  File "C:\Utilities\Anaconda\envs\cls_neurons\lib\site-packages\neuroglancer\server.py", line 100, in __init__
    http_server.add_sockets(sockets)
  File "C:\Utilities\Anaconda\envs\cls_neurons\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Utilities\Anaconda\envs\cls_neurons\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Utilities\Anaconda\envs\cls_neurons\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Utilities\Anaconda\envs\cls_neurons\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

The same thing runs without error when forcing python to 3,7.

Also is there a more elegant solution to keep the server alive other than using and event? And I think moving to the command line interface might have introduced some errors to the examples.
Thanks!

**Comment by moenigin** [comment]
This seems to be a [Windows](https://bugs.python.org/issue37373) issue? I am fine with 3.7. But if this the case it might be worth allerting other Windows users.

**Comment by jbms** [comment]
The NotImplementedError appears to be the one described here under "Platforms":
https://www.tornadoweb.org/en/stable/index.html#installation

It probably makes sense to add code to Neuroglancer to set the event loop when the server is started on Windows.

Can you tell me which examples seem to be broken?

The solution you have with the event seems like a reasonable way to keep the server alive, and it allows you to quit the server by triggering the event.

**Comment by moenigin** [comment]
https://github.com/google/neuroglancer/blob/master/python/examples/example_action.py
https://github.com/google/neuroglancer/blob/master/python/examples/example_row_layout.py
https://github.com/google/neuroglancer/blob/master/python/examples/example_grid_layout.py

I think these would need argparse imported. Also, I don't really know how to run them without adding an event.wait...

**Comment by jbms** [comment]
To run the examples, you can use `python -i`, as per the instructions here: https://github.com/google/neuroglancer/blob/master/python/README.md#example

**Comment by moenigin** [comment]
Oh yes! Thanks!! And sorry for being so unfocused…
