### ISSUE TITLE
Pointing N5 Data to Meshes

### ISSUE THREAD

**Issue by davidackerman** [google/neuroglancer#254]
Hello,

I have n5 datasets and meshes for those datasets. I was wondering, how do I associate the meshes with the n5 data as is done in the precomputed format? I have done it with something like [n5ng](https://github.com/perlman/n5ng), but is there a way to do it without any external file?

Thanks!
David

**Comment by jbms** [comment]
Currently that isn't supported.  I wasn't aware of an n5 mesh format/attribute for specifying meshes.  Is there an existing format or do you want to define a new format?

**Comment by davidackerman** [comment]
Thanks for the fast response! I have uint64 segmentation data in n5 format and have been generating the associated meshes in the legacy neuroglancer mesh format. Does that work, or is something else required to work with the n5 data?

**Comment by jbms** [comment]
You can just specify the meshes as an additional data source on the same layer.  If you want to have them automatically associated, you will need some new n5 attribute, like neuroglancerPrecomputed which could be a string or array of strings specifying associated precomputed data.

**Comment by davidackerman** [comment]
Thank you! That worked in that I can now load meshes, but the ids displayed for the n5 do not match the ids in the actual n5 file (and in turn the meshes generated for the n5 file). You can see that in the attached image where the actual id is `139900096001` (as it is for the mesh) but the 2D views of the n5 show it as `10570526672849731616` (which doesn't exist in the n5). Is this an issue on my end?
![image](https://user-images.githubusercontent.com/19193291/95606455-5bcc0900-0a28-11eb-982e-8b2995484a1e.png)

**Comment by jbms** [comment]
I'm not able to reproduce this issue with the ids.  I used the following code to create an n5 dataset, and it displays in neuroglancer properly:

```python
import tensorstore as ts

dataset = ts.open(
    {
        'driver': 'n5',
        'kvstore': {
            'driver': 'file',
            'path': '/tmp/n5-uint64'
        },
        'metadata': {
            'dataType': 'uint64',
            'compression': {
                'type': 'raw'
            },
            'dimensions': [10, 10, 10],
            'blockSize': [10, 10, 10]
        }
    }, create=True).result()
dataset[...] = 139900096001

```

**Comment by davidackerman** [comment]
You are correct, sorry! I had been using an outdated neuroglancer, but now it works properly. Thank you!
