### ISSUE TITLE
Help with locating the raw data passed from Python to Typescript

### ISSUE THREAD

**Issue by xxzhongUofM** [google/neuroglancer#260]
I currently use python to open a tif file and view it on the localhost, but I want to alter the data inside typescript on the dev-server side. I looked through the code a bit and I think it seems to use WebGL to draw onto the HTML canvas. However, I can't pinpoint the exact place where typescript reads the raw python data. Is there a specific file in which all the data transfer occurs?

**Comment by jbms** [comment]
Data transfer happens here:
https://github.com/google/neuroglancer/blob/f38d6c915f8750fe9bea142438ea3dcf623c645c/src/neuroglancer/datasource/python/backend.ts#L58

You may find it is easier to alter the data on the Python side, though.

**Comment by xxzhongUofM** [comment]
It does seem to be easier to edit the data on the Python side since Typescript has to read from npz files. However, I'm not sure if I can edit this in Python. I want to show the original image file but also an edited version (e.g. maximum projection) on the 2-panel view. From my understanding, Python writes the numpy image arrays into npz files first, then typescript does processing with the npz files. If I want to pass another numpy image into Neuroglancer, I would need to attach it to a separate layer, and then show layer 1 on the left side and layer 2 on the right side. I guess my question boils down these two: 

Is it possible to load multiple images on the same layer?

If they have to be on separate layers, in the 2-panel view, is it possible to show two separate layers at once without them overlapping (only layer 1 on left side and only layer 2 on right side)?

**Comment by jbms** [comment]
Neuroglancer provides a lot of flexibility for displaying data, but the documentation is unfortunately lacking and the controls are not always obvious.

By default, Neuroglancer starts out with a single "layer group" with a "data layout" of "4panel", meaning 3 cross-section views and one 3d projection view.  You can add as many layers as you like to a layer group.  In the cross-section views, they are blended together according to the opacity settings, and the blend mode in the case of image layers.

You can also have multiple independent layer groups, tiled in rows/columns or a combination thereof, in whichever way you like. 
 In the UI, you can create another layer group by dragging a layer "tab" from the layer bar at the top to the top, left, right, or bottom of the region of the screen corresponding to an existing layer group (i.e. the only one).  The region of the screen corresponding to the layer group consists of the layer bar itself as well as the panels for its "data layout".   So when there is just a single layer group, you can drag the layer tab to the top of the layer bar, or to the left/right/bottom of the browser window.

You can also configure this from the Python API: https://github.com/google/neuroglancer/blob/master/python/examples/example_grid_layout.py

If you drag normally, the same layer will be shared by both layer groups, meaning its enabled state and any other settings are shared.  If you shift+drag, the layer will be copied.  If you control+drag, the layer will be moved.  Note that you can also drag layers between multiple separate Neuroglancer browser windows.

You can set the "data layout" for each layer group independently.

By default the position, orientation, etc. is linked between layer groups.  You can control that by right clicking on empty space in the layer bar itself.  (These controls are only available if you have at least 2 layer groups.)

**Comment by jbms** [comment]
It is also possible for a single layer to have multiple volumetric data sources, provided they have the same data type, in which case all of the settings are shared, but I don't think that is what you want.

**Comment by xxzhongUofM** [comment]
Great, this is exactly what I was looking for. Thank you!
