### ISSUE TITLE
Cannot select an annotation from the side panel

### ISSUE THREAD

**Issue by tingzhao** [google/neuroglancer#263]
Neuroglancer used to allow selecting an annotation by clicking on its table item in the side panel. It seems the function is no longer there and nothing will happen when an annotation item is clicked. Is this function removed on purpose?

**Comment by jbms** [comment]
You can now use control+rightclick to do that, for consistency with the rendered data panels as well.

I agree that control+rightclick is a bit harder to discover, though.
