### ISSUE TITLE
Adding label ids for skeletons

### ISSUE THREAD

**Issue by SridharJagannathan** [google/neuroglancer#264]
I'm trying to add type info (a string) of skeletons right next to the skeleton id like below:
![Screenshot 2020-11-19 at 15 28 57](https://user-images.githubusercontent.com/13106358/99687064-22050e00-2a7c-11eb-8bca-dc4052ab8bee.png)
You can see that it is possible with segments like below (`ADL01a`) as label info:
![Screenshot 2020-11-19 at 15 31 06](https://user-images.githubusercontent.com/13106358/99687174-4234cd00-2a7c-11eb-8b19-745102b5c053.png)

I understand from the [description](https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/skeletons.md) that such an option is not yet made available for skeletons, it would be useful in my opinion to add the same.

Also it seems if If i remove the tick box option in the skeleton (first figure - 2 visible in total), the id simply disappears from the window, can you please tell me how i can keep them in the window without them being ticked (so the tick would simply let them appear/disappear). This option is present in the second figure. I guess this is similar to the first point that i made regarding label

**Comment by jbms** [comment]
If you list the ids in the "Enter ID" text field at the top, they will remain around.  Granted, that isn't the most convenient option.

You can actually specify segment_properties in the skeleton info file --- I just didn't have that documented.
