### ISSUE TITLE
Code for multi-resolution mesh generation?

### ISSUE THREAD

**Issue by davidackerman** [google/neuroglancer#266]
I have been using Neuroglancer with the legacy single-resolution mesh format. It has been extremely helpful, but the large meshes I have would benefit from the multi-resolution format. Do you know of any examples or code repositories for generating the multi-resolution meshes? I have seen the multi-resolution mesh documentation, but haven't been able to find any sources for creating them. Thanks!

**Comment by jbms** [comment]
Unfortunately we only have a Google-internal pipeline for generating the multi-resolution mesh format, and I'm not aware of any other implementations.  I would like to open source it, but it is based on a Google-internal C++ pipeline framework (similar to Cloud Dataflow, but in C++), for which there is no direct open source replacement that I'm aware of, which makes it a bit challenging.

**Comment by davidackerman** [comment]
Thanks for letting me know! I am attempting to write something myself that will generate them. I can currently create meshes at different resolutions which are subdivided, in Draco format and concatenated. But I am still having trouble and was wondering if you could clarify some things:

1. Does `lod` = 0 correspond to the lowest resolution mesh (ie. higher `lod` corresponds to higher resolution)?

2. Where does `lod_scales` and `lod_scale_multiplier` get used?

2. I assume that the higher resolution meshes should be divided into the most chunks so that it could be loaded in smaller pieces. But then presumably the lower resolution meshes should also be divided into small chunks so that its own chunks would be cleanly replaced by the higher res chunks. Is this correct?

3. Since the fragment position is calculated based on `chunk_shape * 2**lod`, does this imply that higher `lod` scales have larger but fewer meshes?

**Comment by jbms** [comment]
Awesome.  If you are able to make this code open source, I'm sure it would be very useful to others as well.

1. lod = 0 is the finest mesh (highest resolution)

2. lod_scales and lod_scale_multiplier are used by Neuroglancer to decide which mesh resolution to use depending on the "Resolution" control setting and the projection matrix for the current view.

3. Yes.  lod=0 is divided into the smallest chunks (the chunk size is given by the chunk_shape in the info file).  Each successive lod uses a chunk shape twice as large as the previous in each dimension.  However, for lod>0, each chunk mesh must be constructed in such a way that it can be partitioned into 8 sub-chunks.  That is what allows replacing part of a low-resolution mesh with a high-resolution mesh.

https://github.com/google/neuroglancer/blob/4a2ab59b0b4d2fee75acecbaab48a4b771a4f7dc/src/neuroglancer/mesh/draco/neuroglancer_draco.cc#L80

4. Yes, higher lod scales (i.e. coarser resolution) have fewer chunks, each of which corresponds to a larger spatial region.

**Comment by davidackerman** [comment]
Thank you. As a test, I am trying to load a single resolution level split into 8 fragments. The fragments are acquired by splitting a .obj mesh by 2 in each dimension, converting the meshes to Draco and concatenating. The fragments are displaying, but they are offset with respect to where they should be (see attached). I assume this is due to the fact that the Draco meshes are shifted such that their lowest coordinates are aligned with the lower bounds of the corresponding bounding box? So if the fragments themselves have different dimensions, they won't be aligned. If this is the case, is there a way to shift the meshes properly? I have seen it mentioned [here](https://github.com/google/draco/issues/506) but haven't quite figured out how to set such options.

![image](https://user-images.githubusercontent.com/19193291/101297671-24939180-37f8-11eb-8817-f0378bc23d8a.png)

**Comment by jbms** [comment]
For the neuroglancer precomputed multiscale mesh format, the vertex positions are quantized, but that must be done prior to encoding with draco --- it is not done using Draco's vertex quantization.  This is the relevant part of our pipeline, which you might find helpful as a reference:

```c++

// Function object that quantizes an input `std::array<float, 3>` vertex
// position to the specified number of bits.
//
// \tparam VertexCoord Unsigned integer type used for representing quantized
//     vertex coordinates.
template <typename VertexCoord>
struct Quantizer {
  // Constructs a quantizer.
  //
  // \param fragment_origin Minimum input vertex position to represent.
  // \param fragment_shape The inclusive maximum vertex position to represent
  //     is `fragment_origin + fragment_shape`.
  // \param input_origin The offset to add to input vertices before quantizing
  //     them within the `[fragment_origin, fragment_origin+fragment_shape]`
  //     range.
  // \param num_quantization_bits The number of bits to use for quantization.
  //     A value of `0` for coordinate `i` corresponds to `fragment_origin[i]`,
  //     while a value of `2**num_quantization_bits-1` corresponds to
  //     `fragment_origin[i]+fragment_shape[i]`.  Should be less than or equal
  //     to the number of bits in `VertexCoord`.
  Quantizer(const Vector3d& fragment_origin, const Vector3d& fragment_shape,
            const Vector3d& input_origin, int num_quantization_bits) {
    for (int i = 0; i < 3; ++i) {
      upper_bound[i] =
          static_cast<float>(std::numeric_limits<VertexCoord>::max() >>
                             (sizeof(VertexCoord) * 8 - num_quantization_bits));
      scale[i] = upper_bound[i] / static_cast<float>(fragment_shape[i]);
      // Add 0.5 to round to nearest rather than round down.
      offset[i] = input_origin[i] - fragment_origin[i] + 0.5 / scale[i];
    }
  }

  // Maps an input vertex position `v_pos`.
  std::array<VertexCoord, 3> operator()(const std::array<float, 3>& v_pos) {
    std::array<VertexCoord, 3> output;
    for (int i = 0; i < 3; ++i) {
      output[i] = static_cast<VertexCoord>(std::min(
          upper_bound[i], std::max(0.0f, (v_pos[i] + offset[i]) * scale[i])));
    }
    return output;
  }

  std::array<float, 3> offset;
  std::array<float, 3> scale;
  std::array<float, 3> upper_bound;
};

// Combines multiple meshes into a single mesh, quantizes vertices according to
// the specified quantization options, and returns the Draco encoded result.
//
// \param meshes The list of meshes to combine.
// \param fragment_origin The minimum input vertex position to represent.
// \param fragment_shape The inclusive maximum vertex position to represent is
//     `fragment_origin+fragment_shape`.
// \param num_quantization_bits The number of bits to use for quantization.
std::string ConvertToDracoMeshWithPreQuantization(
    absl::Span<const InternalMesh> meshes, const Vector3d& fragment_origin,
    const Vector3d& fragment_shape, int num_quantization_bits) {
  draco::TriangleSoupMeshBuilder mb;
  size_t num_triangles = 0;
  for (const auto& mesh : meshes) {
    num_triangles += mesh.triangles.size();
  }
  mb.Start(num_triangles);
  // Draco always stores integer attributes as int32, so there is no point in
  // using a smaller integer type as the intermediate representation.
  using VertexCoord = std::uint32_t;
  int position_att_id =
      mb.AddAttribute(draco::GeometryAttribute::POSITION, 3, draco::DT_UINT32);
  size_t tri_i = 0;
  for (const auto& mesh : meshes) {
    Quantizer<VertexCoord> quantizer(fragment_origin, fragment_shape,
                                     mesh.origin, num_quantization_bits);
    for (const auto& triangle : mesh.triangles) {
      std::array<std::array<VertexCoord, 3>, 3> points;
      for (int i = 0; i < 3; ++i) {
        points[i] = quantizer(mesh.vertex_positions[triangle[i]]);
      }
      mb.SetAttributeValuesForFace(position_att_id, draco::FaceIndex(tri_i),
                                   &points[0], &points[1], &points[2]);
      ++tri_i;
    }
  }
  if (tri_i == 0) {
    return std::string();
  }
  std::unique_ptr<draco::Mesh> draco_mesh = mb.Finalize();
  CHECK(draco_mesh);

  draco::EncoderBuffer eb;
  draco::Encoder encoder;
  encoder.SetEncodingMethod(draco::MESH_EDGEBREAKER_ENCODING);
  encoder.SetAttributePredictionScheme(draco::GeometryAttribute::POSITION,
                                       draco::MESH_PREDICTION_PARALLELOGRAM);
  auto draco_status = encoder.EncodeMeshToBuffer(*draco_mesh, &eb);
  CHECK(draco_status.ok()) << draco_status.error_msg_string();
  return std::string(eb.data(), eb.size());
}
```

**Comment by davidackerman** [comment]
Thanks again! The locations now look correct for a single resolution split into 8 chunks, but I am having an issue with them loading, as in they don't all seem to load at once. If I keep refreshing Neuroglancer, I can get different chunks to load but it doesn't seem like they all will load at one time. I am using cors_webserver with [an added HTTP range request](https://pypi.org/project/rangehttpserver/). Is this part of the issue, or is this expected behavior with only one resolution? See below for snapshots of the same view when refreshed:
![image](https://user-images.githubusercontent.com/19193291/101509695-08523a80-3947-11eb-961e-4c8e2239814b.png)
![image](https://user-images.githubusercontent.com/19193291/101509729-12743900-3947-11eb-9f2c-cbb14da23183.png)
![image](https://user-images.githubusercontent.com/19193291/101509758-1d2ece00-3947-11eb-883c-e3e169fd806a.png)

**Comment by jbms** [comment]
It should work to have a single mesh resolution.  The possible reasons why all fragments aren't loading are:
- problem with your manifest, such that Neuroglancer thinks there is more than 1 lod, or something like that.  The "Render" tab may indicate something about this.
- mesh fragments  (after draco decoding) are really large and don't fit within the memory limit specified (1GB by default).  The chunk statistics panel may indicate something about this.  (Press backslash or right click on top bar next to position and show chunk statistics.)
- some unknown bug in Neuroglancer

**Comment by xgui3783** [comment]
@davidackerman would be very interested if you have something working (converting high res mesh to neuroglancer multiresolutioned meshes)

We have a tool that converts meshes of various formats to ng precomputed format, but only in legacy single solution format. We are looking at implementing something that can (hopefullly) autogenerate multi res format. If you already have tool/script that takes input(s) and outputs multi resolutioned ng format, it would be great to not duplicate efforts?

**Comment by davidackerman** [comment]
@xgui3783 I will definitely keep you updated if I get it to a stable, more finalized state. Right now it is only at a rough, proof of principle stage where I take meshes that have been generated at different resolutions, create the corresponding fragments, and write out the necessary files. It seems that https://github.com/google/neuroglancer/issues/272 may be a good place to look also.

**Comment by davidackerman** [comment]
The following repo is my attempt. Does not deal with production of the meshes themselves, but assuming you have meshes at different resolutions it creates precomputed multiresolution mesh format.
https://github.com/davidackerman/multiresolutionMeshes
