### ISSUE TITLE
Adding annotations to specific skeletons

### ISSUE THREAD

**Issue by SridharJagannathan** [google/neuroglancer#267]
I'm trying to add annotations to segments that are located in  a specific layer like below:

![Screenshot 2020-11-28 at 09 47 39](https://user-images.githubusercontent.com/13106358/100499127-f7dbdc00-315e-11eb-927e-3d115302757c.png)

For e.g. I want to add synapses associated with the layer `skeletons` and specific segids like 40637
I noticed that in the [example](https://github.com/google/neuroglancer/blob/e6bebde18a02e50ae7951ae929e6e531bbe738c0/python/tests/annotation_properties_test.py#L67) it is present as `segments` in `neuroglancer.PointAnnotation` api.
However, I don't seem to find any documentation related to that, for e.g. in this case, lets say I want to annotate a point (0,0,0) in the layer `synapse` and associate that with segid 40637 present in the layer `skeleton`, how would I go about it?
Is it like 
```
s.layers.append(
            name="synapse",
            layer=neuroglancer.LocalAnnotationLayer(
                dimensions=s.dimensions,
                annotation_relationships=['synapse'],
                linked_segmentation_layer={'synapse': 'skeletons'},
                filter_by_segmentation=['synapse'],
                ignore_null_segment_filter=False,
                annotation_properties=[
                    neuroglancer.AnnotationPropertySpec(
                        id='color',
                        type='rgb',
                        default='red',
                    )
                ],
                annotations=[
                    neuroglancer.PointAnnotation(
                        id='1',
                        point=[0, 0, 0],
                        segments=[[40637]],
                        props=['#0f0'],
                    )
```

**Comment by jbms** [comment]
Unfortunately there is not much documentation, but your code snippet looks correct?  Does it not work?

**Comment by SridharJagannathan** [comment]
Thank you for the comment, you are indeed right the snippet does work, I made a mistake with the dimensions. I have now managed to plot the neurons with synapses. 
![Screenshot 2020-12-01 at 23 51 37](https://user-images.githubusercontent.com/13106358/100810369-44aa0600-3430-11eb-90fb-11cf417a71bd.png)

My question now is that since i'm plotting many point annotations, the browser simply is very slow and freezes frequently. I noticed that all the points are specifically listed along with their x,y,z coordinates. However when i plot the buchmann synapses like `precomputed://gs://neuroglancer-20191211_fafbv14_buhmann2019_li20190805` I don't see any such x,y,z locations and the interface is much faster. 
![Screenshot 2020-12-01 at 23 55 40](https://user-images.githubusercontent.com/13106358/100810624-c8fc8900-3430-11eb-8070-85dd2952df78.png)

Can you please let me know how I can achieve a representation like buchmann layer with the pointannotation api?

**Comment by jbms** [comment]
Prior to this commit (https://github.com/google/neuroglancer/commit/1b9c7d3fd218b231f5c32388e69f92d6b06edafc) the display of the annotation side panel itself significantly slowed down neuroglancer if there were thousands of annotations.  If you haven't already updated past that version, you may find it makes a significant difference.

Nonetheless you will still be limited to a few thousand annotations when using a local annotation layer.

The fafb synapses use the precomputed annotation format (https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md).  Unfortunately the tool that we use at google to generate that format relies on an internal c++ pipeline framework and can't easily be open sourced.  You can find a prior discussion of the format here:

https://github.com/google/neuroglancer/issues/227

**Comment by SridharJagannathan** [comment]
Thanks again, it was super useful, I have managed to use the precomputed format for annotations now.. :)

![Screenshot 2020-12-03 at 21 59 51](https://user-images.githubusercontent.com/13106358/101093785-418b5300-35b3-11eb-82a3-371dad9aaa33.png)



However, now if i want to link the segment ids to specific annotations, can you please tell me how to go about that, usually with pointannotation api, I would provide something like 
```
annotation_relationships=['post_synapses'],
linked_segmentation_layer={'post_synapses': 'skeletons'},
filter_by_segmentation=['post_synapses'],
```

**Comment by jbms** [comment]
For the precomputed format, you need to define a relationship in the info file, similar to how you would do it for a local annotation layer, but then you also need to write a related object id index:

https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md#related-object-id-index

in order to allow Neuroglancer to retrieve annotations by id.

**Comment by SridharJagannathan** [comment]
I'm a little bit confused by the documentation. For e.g.:
Per my understanding:
First I create a file under `spatial0/0_0_0` that contains:
```
synapselocs = synapses[['x', 'y', 'z']].values/1000

# implementation based on logic suggested by https://github.com/google/neuroglancer/issues/227
with open(synapsefile, 'wb') as outputbytefile:
     total_synapses = len(synapselocs) 
     buffer = struct.pack('<Q', total_synapses)
     for (x, y, z) in synapselocs:
            synapsepoint = struct.pack('<3f', x, y, z)
            buffer += synapsepoint
      synapseid_buffer = struct.pack('<%sQ' % len(synapselocs), *range(len(synapselocs)))
      buffer += synapseid_buffer
      outputbytefile.write(buffer)
```
This is able to display the annotations.
Now to create a related object id index, I created a file under `presynapses_cell/0`
```
with open(relsynapseidfile, 'wb') as outputbytefile:
        total_synapses = len(synapselocs)
        buffer = struct.pack('<Q', total_synapses)
        for relsynidx in range(len(synapselocs)):
            buffer += struct.pack('<Q', relsynidx)
            buffer += struct.pack('<Q', 40637)
        outputbytefile.write(buffer)
```
Here, I'm trying to annotate all points with the skeleton id `40637`
However, when I choose the segment filter `skeleton` the points seem to disappear.
In the info file, I have provided:
```
synapseinfo["relationships"] = [{"id": "presynapses_cell", "key": "presynapses_cell"}]
```
I think I'm making a mistake in creating the related object id index file, can you please guide me here?

**Comment by jbms** [comment]
The annotations for skeleton id 40637 should be written to presynapses_cell/40637.  That file should contain the annotations in exactly the same format as the spatial0/0_0_0 file.  In particular, you don't write the id 40637 anywhere in that file.  Only the by_id index (if you choose to write it) contains the list of related segment ids.

**Comment by SridharJagannathan** [comment]
Thanks it works like a charm now.. 👍  Just one question before I close this, I have now stopped creating the `spatial0/0_0_0` file and however I try to keep the info file like below.. Do you think this is Ok?
```
"spatial": [
            {
               ...
                "key": "spatial0",
                "limit": 10000
            }
        ],
```
