### ISSUE TITLE
404: Not Found when running the example.py

### ISSUE THREAD

**Issue by hash-ir** [google/neuroglancer#270]
I have created a conda environment and installed neuroglancer in editable mode using `pip install -e .` When I run example.py under `python/examples`, I see a "404: Not Found" error in Chrome. I have launched it in Firefox as well but have the same problem.

**Comment by jbms** [comment]
This error happens when the client bundle is not built.  With recent versions of Neuroglancer that should happen automatically, but if for some reason it is not, you can do it manually with:

```
python setup.py bundle_client
```

or

```
npm install
npm run build-python-min
```

**Comment by hash-ir** [comment]
@jbms That solved the problem, thanks
