### ISSUE TITLE
Zarr source offsets

### ISSUE THREAD

**Issue by sheridana** [google/neuroglancer#273]
Is there a way to specify layer offsets when serving directly from Zarr? Local volume and precomputed format both take a voxel_offset but the Zarr source seems to create the [coordinate space](https://github.com/google/neuroglancer/blob/fd9d87941a939c120a754716184c869fc430dad4/src/neuroglancer/datasource/zarr/frontend.ts#L130) from the metadata rank and shape - the former being the number of dimensions. When loading a zarr via python the offsets work as expected:

<img width="696" alt="Screen Shot 2021-01-04 at 1 43 30 PM" src="https://user-images.githubusercontent.com/29460471/103582698-3ddd3b80-4e93-11eb-8ee3-c69c5c3f4c86.png">

But when directly loading the zarr (using neuroglancer-demo.appspot), both layers assume a 0,0,0 offset:

<img width="697" alt="Screen Shot 2021-01-04 at 1 43 42 PM" src="https://user-images.githubusercontent.com/29460471/103582809-6fee9d80-4e93-11eb-9738-6beebe3ea346.png">
 
Is there a specific field needed in the attrs? Alternatively, could the voxel offset be incorporated similar to the [precomputed format](https://github.com/google/neuroglancer/blob/fd9d87941a939c120a754716184c869fc430dad4/src/neuroglancer/datasource/precomputed/frontend.ts#L102)? Ideal scenario is for this to work directly with the live demo using arbitrary layer offsets as specified by the .zattrs json.

**Comment by jbms** [comment]
You can specify an offset within the Neuroglancer state itself via the coordinate transform -- see the "Source" tab in the layer side panel.  If there is some semi-standard zarr attribute that could be used for this purpose, then Neuroglancer could support it.  Or one could be invented, though I'd prefer not to do that since it may create compatibility issues.

**Comment by sheridana** [comment]
I think it's fine to just use the source tab to set the translation in this case. Also, Neuroglancer now loads channels as a separate scrollable dimension (previously it loaded all channels implicitly which allowed for channel control with an RGB shader). Is there a way around this in v2?

**Comment by jbms** [comment]
If you rename the desired dimension to end in "^", e.g. "c^", then that dimension is treated as a "channel dimension" and is available to the shader via `getDataValue(i)`.

**Comment by sheridana** [comment]
Perfect, thanks a lot!
