### ISSUE TITLE
2-d EM data not visible

### ISSUE THREAD

**Issue by SridharJagannathan** [google/neuroglancer#276]
Hi @jbms 
I'm currently building a tool : [pyroglancer](https://github.com/SridharJagannathan/pyroglancer) that basically lets people display local neurons, meshes, volumes, synapses etc in precomputed format.
While I was trying to test the bug fix #275 using the development version in github, I noticed that something is broken with the 2-d EM data viewer. On digging further i noticed that the issue starts appearing from v2.17 onwards.
To illustrate see below:

**with v2.16:**

![v1 16](https://user-images.githubusercontent.com/13106358/104851019-451c3480-58ea-11eb-8974-293460e268f5.png)

**with v2.17:**

![v1 17](https://user-images.githubusercontent.com/13106358/104851020-477e8e80-58ea-11eb-8606-ea36b5b2cee2.png)

It seems the EM data just seems to not appear from any version above 2.17 onwards.

The layer is 
```
 "type": "image",
  "source": "precomputed://gs://neuroglancer-fafb-data/fafb_v14/fafb_v14_clahe",
  "name": "fafb_v14_clahe"

```

**Comment by jbms** [comment]
Thanks for reporting this, it is now fixed.
