### ISSUE TITLE
define get_skeleton() in SkeletonSource for custom data

### ISSUE THREAD

**Issue by hash-ir** [google/neuroglancer#277]
I am running a skeleton example on custom data inspired by [example_skeleton.py](https://github.com/google/neuroglancer/blob/master/python/examples/example_skeletons.py). I implemented the `get_skeleton()` method of `SkeletonSource` but I didn't find its use anywhere in the example. I want to know how I can forward my custom skeleton data to the viewer source?

In the skeleton [example](https://github.com/google/neuroglancer/blob/ac06c8049666fd640e171acd39a432c7aa1da419/python/examples/example_skeletons.py#L45), the dummy segmentation data is provided in a `LocalVolume` and a `SkeletonSource` object is just instantiated without using the `get_skeleton()` method.
```python
with viewer.txn() as s:
    s.layers.append(
        name='a',
        layer=neuroglancer.SegmentationLayer(
            source=[
                neuroglancer.LocalVolume(
                    data=segmentation, # here
                    dimensions=dimensions,
                ),
                SkeletonSource(dimensions), # here
            ],
            skeleton_shader='void main() { emitRGB(colormapJet(affinity)); }',
            selected_alpha=0,
            not_selected_alpha=0,
            segments=[395750],
        ))
```

**Comment by jbms** [comment]
Turns out the skeleton example was broken --- I just fixed it.

`get_skeleton` is called by the Python Neuroglancer code when the client requests a skeleton --- your own code doesn't need to call it directly.
