### ISSUE TITLE
Annotations no longer displaying after Ubuntu upgrade

### ISSUE THREAD

**Issue by austinhoag** [google/neuroglancer#278]
I recently upgraded to Ubuntu 18.04 and I am seeing a bunch of weird behavior using your client (all clients, actually), all related to WebGL. I'm guessing it's just a missing driver, but I'm not sure how to debug that.

The behavior I can reproduce most easily is that manually added annotations do not show up in a new annotation layer. They are added in the annotation list but do not show up visually. In the rendering tab of the annotation layer I see this error:

![ng-webgl-annotation-error](https://user-images.githubusercontent.com/42473349/105073372-00f97300-5a55-11eb-8138-242bd4a0ac90.png)

The console does not report any errors. Here is what I see at `chrome://gpu`: 

![chrome-gpu-config](https://user-images.githubusercontent.com/42473349/105073620-4b7aef80-5a55-11eb-94cb-4ff262af000c.png)

I'm not sure which of these Neuroglancer uses. Does that look suspect?

**Comment by jbms** [comment]
If Chrome determines that your GPU cannot be used, it falls back to its built-in software rendering system called SwiftShader.  You can check the WebGL2 tab of webglreport.com to see if swiftshader is listed.  Unfortunately SwiftShader has some bugs in its WebGL2 support that prevent Neuroglancer from working properly --- in many cases WebGL will crash completely (shows up as a context lost error in the console), but those shader errors you see are another problem I have observed.

I would suggest that you figure out how to get GPU rendering to work again on your system.  Even if Swiftshader worked, it would still be slow.  I can't really say exactly how to get your GPU drivers working, but reinstalling the drivers may help.

**Comment by jbms** [comment]
You can also see if Firefox works.

**Comment by austinhoag** [comment]
Thanks for the tips. Reinstalling GPU drivers and then rebooting did the trick. Firefox was not working either. For anyone who runs into this problem in the future, chrome://gpu is a good diagnostic. After the fix, this is what that page displays:

![chrome-gpu-config_postfix](https://user-images.githubusercontent.com/42473349/105095608-e682c200-5a73-11eb-9acf-1edbf152bced.png)
