### ISSUE TITLE
Adding labels for annotated points in precomputed format

### ISSUE THREAD

**Issue by SridharJagannathan** [google/neuroglancer#280]
Hi @jbms ,
I'm trying to add labels to annotated points so they can be displayed in the right side gui. 
The code that I use for generating pts binary file is as follows:
```
pointlocs = points[['x', 'y', 'z']].values/1000
  with open(pointsfile, 'wb') as outputbytefile:
      total_points = len(pointlocs)
      buffer = struct.pack('<Q', total_points)
      for (x, y, z) in pointlocs:
          x = x*pointsscale[0]
          y = y*pointsscale[1]
          z = z*pointsscale[2]
          annotpoint = struct.pack('<3f', x, y, z)
          buffer += annotpoint
      pointid_buffer = struct.pack('<%sQ' % len(pointlocs), *range(len(pointlocs)))
      buffer += pointid_buffer
      outputbytefile.write(buffer)

```

The info file is as follows:
```
   pointinfo = {
        '@type': 'neuroglancer_annotations_v1',
        "annotation_type": "POINT",
        "by_id": {
            "key": "by_id"
        },
        "dimensions": {
            "x": [dimensions['x'].scale, dimensions['x'].unit],
            "y": [dimensions['y'].scale, dimensions['y'].unit],
            "z": [dimensions['z'].scale, dimensions['z'].unit]
        },
        "lower_bound": [0, 0, 0],
        "properties": [],
        "relationships": [],
        "spatial": [
            {
                "chunk_size": [137216, 264192, 4400],
                "grid_shape": [1, 1, 1],
                "key": "spatial0",
                "limit": 10000
            }
        ],
        "upper_bound": [137216, 264192, 4400]
    }
```

However from the documentation I was not sure how to assign ids to each of these points and how to add the labels and other info like radius to them. Can you please guide me on this?

**Comment by jefferis** [comment]
For the ids I've seen this in the past on the js side:

https://github.com/google/neuroglancer/blob/2ca59d40e9aae8ad3dac6ac262d9d8a52124b599/src/neuroglancer/annotation/index.ts#L907-L909

https://github.com/google/neuroglancer/blob/8ff58354757f6701a6bc9d4e45a611743facae6b/src/neuroglancer/util/random.ts#L19-L28

**Comment by jbms** [comment]
Adding other numeric or color properties is done by specifying a non-empty "properties" list --- see the documentation here: https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md#info-json-file-format

However, in order to display points in the "Selection details" panel, you need to write a "by_id" version of the data as well.

Additionally, currently text-type properties are not supported.  It would not be too hard to add support for them, though.

If you instead use an in-JSON state local annotation layer, you can add a text description property, but of course that doesn't accommodate a large number of annotations.

**Comment by SridharJagannathan** [comment]
Thanks @jefferis , I was mainly looking at the formatting of how to add the id file like how @jbms was suggesting.
@jbms I have tried to implement this, however I can only see the pts in the viewer but do not see that in the `selection details` panel. 
For e.g. here
First I try and write two points like:
```
points = pd.DataFrame([[123072, 47001, 3375], [120000, 17001, 3000]], columns=['x', 'y', 'z'])
```

Next, I use the code in my previous comment to write a file in `precomputed/landmarks/spatial0/0_0_0`

> ```
> pointlocs = points[['x', 'y', 'z']].values/1000
>   with open(pointsfile, 'wb') as outputbytefile:
>       total_points = len(pointlocs)
>       buffer = struct.pack('<Q', total_points)
>       for (x, y, z) in pointlocs:
>           x = x*pointsscale[0]
>           y = y*pointsscale[1]
>           z = z*pointsscale[2]
>           annotpoint = struct.pack('<3f', x, y, z)
>           buffer += annotpoint
>       pointid_buffer = struct.pack('<%sQ' % len(pointlocs), *range(len(pointlocs)))
>       buffer += pointid_buffer
>       outputbytefile.write(buffer)
> ```

Next, I try to write a `by_id` files in `precomputed/landmarks/by_id/0`, `precomputed/landmarks/by_id/1` using the single annotation format in the docs like below:
```
    for idfileidx in range(len(pointlocs)):
        filename = str(idfileidx)
        idfile = os.path.join(idfilepath, filename)
        print(idfile)
        with open(idfile, 'wb') as outputbytefile:
            x = pointlocs[idfileidx][0]*pointsscale[0]
            y = pointlocs[idfileidx][1]*pointsscale[1]
            z = pointlocs[idfileidx][2]*pointsscale[2]
            annotpoint = struct.pack('<3f', x, y, z)
            outputbytefile.write(buffer)
```
Can you please tell me where I'm getting this wrong? Also if possible, how would i change a property say `color` per id here?
Thank you again for your response.

**Comment by jbms** [comment]
Can you share either a complete script for generating your test data, or the output you generated, so that I can investigate it more easily?

**Comment by jbms** [comment]
For setting a color property, you can add an entry like: {"id": "color", "type": "rgb"} to the properties array in the info file.   Then after writing the x y z coordinates (for both the spatial index and by_id index), additionally write 4 more bytes, r, g, b as uint8 values, then a 0 byte for padding.

**Comment by jbms** [comment]
Then to actually use that property as the displayed color, you can modify the shader to reference `prop_color()`.

**Comment by SridharJagannathan** [comment]
This folder contains the output data in the precomputed format, the test data is actually the 
`points = pd.DataFrame([[123072, 47001, 3375], [120000, 17001, 3000]], columns=['x', 'y', 'z'])`
[landmarks.zip](https://github.com/google/neuroglancer/files/5876824/landmarks.zip)

**Comment by jbms** [comment]
Looks like the bug is that when writing the to the id files, you are writing `buffer` (from the previous loop) instead of `annotpoint`.  You can see in the Javascript developer console:

Error retrieving chunk 0: Error: Expected 12 bytes, but received: 48

**Comment by SridharJagannathan** [comment]
Thanks. You are right about the incorrect object, I fixed the same and the error in the console disappeared as you can see below, however the info still doesn't seem to appear on the right side panel? 

![Screenshot 2021-01-27 at 00 38 55](https://user-images.githubusercontent.com/13106358/105925498-2d565600-6038-11eb-8416-c9eaaf6b1a50.png)

**Comment by jbms** [comment]
To show the selection detail panel, you have to Control+rightclick on one of the annotations.

For precomputed annotations, neuroglancer does not support a list view showing all of the annotations.

**Comment by SridharJagannathan** [comment]
Thank you, I wasn't aware of this, I was assuming they would show up in the same format as the `in-JSON` state. Perhaps I will shift my implementation to the in-JSON state for a smaller number of landmark points.

**Comment by SridharJagannathan** [comment]
Closing this, as I have implemented both the `precomputed` and `in-JSON` state (for description etc).
