### ISSUE TITLE
Skeletons not Rendering

### ISSUE THREAD

**Issue by william-silversmith** [google/neuroglancer#285]
Hi Jeremy,

Using both Firefox and Chrome on Mac OS Big Sur using the new arm64 platform, it seems that skeletons are not rendering. For some reason they render on the older version of Neuroglancer that my lab is using. I noticed that given integer attributes are now supported a fairly large update must have taken place. Is there anything obvious that I should try before looking at the code?

[Example not working link.](https://fafb-dot-neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-8%2C%22m%22%5D%7D%2C%22position%22:%5B122437.9375%2C40644.58203125%2C3858.396240234375%5D%2C%22crossSectionScale%22:2.1875%2C%22projectionOrientation%22:%5B0.22004826366901398%2C-0.3443352282047272%2C0.7209692001342773%2C0.5596565008163452%5D%2C%22projectionScale%22:7395.841199402878%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-fafb-data/fafb_v14/fafb_v14_orig%22%2C%22tab%22:%22source%22%2C%22name%22:%22fafb_v14%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-fafb-data/fafb_v14/fafb_v14_clahe%22%2C%22tab%22:%22source%22%2C%22name%22:%22fafb_v14_clahe%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%7B%22url%22:%22precomputed://gs://fafb-ffn1-20200412/segmentation%22%2C%22subsources%22:%7B%22default%22:true%2C%22bounds%22:true%2C%22mesh%22:true%2C%22skeletons%22:true%7D%2C%22enableDefaultSubsources%22:false%7D%2C%22tab%22:%22source%22%2C%22meshSilhouetteRendering%22:3%2C%22segments%22:%5B%225122861455%22%2C%22710435991%22%5D%2C%22name%22:%22fafb-ffn1-20200412%22%7D%2C%7B%22type%22:%22annotation%22%2C%22source%22:%22precomputed://gs://neuroglancer-20191211_fafbv14_buhmann2019_li20190805%22%2C%22annotationColor%22:%22#cecd11%22%2C%22shader%22:%22#uicontrol%20vec3%20preColor%20color%28default=%5C%22blue%5C%22%29%5Cn#uicontrol%20vec3%20postColor%20color%28default=%5C%22red%5C%22%29%5Cn#uicontrol%20float%20scorethr%20slider%28min=0%2C%20max=1000%29%5Cn#uicontrol%20int%20showautapse%20slider%28min=0%2C%20max=1%29%5Cn%5Cnvoid%20main%28%29%20%7B%5Cn%20%20setColor%28defaultColor%28%29%29%3B%5Cn%20%20setEndpointMarkerColor%28%5Cn%20%20%20%20vec4%28preColor%2C%200.5%29%2C%5Cn%20%20%20%20vec4%28postColor%2C%200.5%29%29%3B%5Cn%20%20setEndpointMarkerSize%285.0%2C%205.0%29%3B%5Cn%20%20setLineWidth%282.0%29%3B%5Cn%20%20if%20%28int%28prop_autapse%28%29%29%20%3E%20showautapse%29%20discard%3B%5Cn%20%20if%20%28prop_score%28%29%3Cscorethr%29%20discard%3B%5Cn%7D%5Cn%5Cn%22%2C%22shaderControls%22:%7B%22scorethr%22:80%7D%2C%22linkedSegmentationLayer%22:%7B%22pre_segment%22:%22fafb-ffn1-20200412%22%2C%22post_segment%22:%22fafb-ffn1-20200412%22%7D%2C%22filterBySegmentation%22:%5B%22post_segment%22%2C%22pre_segment%22%5D%2C%22name%22:%22synapses_buhmann2019%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22n5://gs://fafb-v14-synaptic-clefts-heinrich-et-al-2018-n5/synapses_dt_reblocked%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%5D%2C%5B0%2C0%2C1%2C1%5D%5D%2C%22outputDimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-8%2C%22m%22%5D%7D%7D%7D%2C%22opacity%22:0.73%2C%22shader%22:%22void%20main%28%29%20%7BemitRGBA%28vec4%280.0%2C0.0%2C1.0%2CtoNormalized%28getDataValue%28%29%29%29%29%3B%7D%22%2C%22name%22:%22clefts_Heinrich_etal%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-fafb-data/elmr-data/FAFBNP.surf/mesh#type=mesh%22%2C%22tab%22:%22segments%22%2C%22segments%22:%5B%221%22%2C%2210%22%2C%2211%22%2C%2212%22%2C%2213%22%2C%2214%22%2C%2215%22%2C%2216%22%2C%2217%22%2C%2218%22%2C%2219%22%2C%222%22%2C%2220%22%2C%2221%22%2C%2222%22%2C%2223%22%2C%2224%22%2C%2225%22%2C%2226%22%2C%2227%22%2C%2228%22%2C%2229%22%2C%223%22%2C%2230%22%2C%2231%22%2C%2232%22%2C%2233%22%2C%2234%22%2C%2235%22%2C%2236%22%2C%2237%22%2C%2238%22%2C%2239%22%2C%224%22%2C%2240%22%2C%2241%22%2C%2242%22%2C%2243%22%2C%2244%22%2C%2245%22%2C%2246%22%2C%2247%22%2C%2248%22%2C%2249%22%2C%225%22%2C%2250%22%2C%2251%22%2C%2252%22%2C%2253%22%2C%2254%22%2C%2255%22%2C%2256%22%2C%2257%22%2C%2258%22%2C%2259%22%2C%226%22%2C%2260%22%2C%2261%22%2C%2262%22%2C%2263%22%2C%2264%22%2C%2265%22%2C%2266%22%2C%2267%22%2C%2268%22%2C%2269%22%2C%227%22%2C%2270%22%2C%2271%22%2C%2272%22%2C%2273%22%2C%2274%22%2C%2275%22%2C%228%22%2C%229%22%5D%2C%22name%22:%22neuropil-regions-surface%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22mesh%22%2C%22source%22:%22vtk://https://storage.googleapis.com/neuroglancer-fafb-data/elmr-data/FAFB.surf.vtk.gz%22%2C%22shader%22:%22void%20main%28%29%20%7B%5Cn%20%20emitRGBA%28vec4%281.0%2C%201.0%2C%201.0%2C%200.05%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%29%29%3B%7D%22%2C%22name%22:%22neuropil-full-surface%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://fafb-ffn1/fafb-public-skeletons%22%2C%22saturation%22:0.56%2C%22meshSilhouetteRendering%22:10%2C%22skeletonRendering%22:%7B%22mode2d%22:%22lines%22%7D%2C%22name%22:%22public_skeletons%22%7D%5D%2C%22showAxisLines%22:false%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22layer%22:%22public_skeletons%22%2C%22visible%22:true%7D%2C%22layout%22:%22xy-3d%22%7D)

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/2517065/109077103-a2fe2200-76c9-11eb-8df3-247b069e1f38.png">
<img width="970" alt="image" src="https://user-images.githubusercontent.com/2517065/109077279-e062af80-76c9-11eb-9167-c9925674e6bb.png">

Thanks for all your hard work on this platform. ^_^

**Comment by jbms** [comment]
Thanks for reporting this.  I don't have an arm mac to test on, so it may be a bit tricky for me to reproduce, but I'll definitely want to get this fixed right away.

The skeleton rendering shares a lot of code with annotation rendering (e.g. the full volume bounding box shown in the 3d view).  Is that also not working?

As a starting point, can you run the automated test suite via `npm run test` (you have to open the link that gets printed in a browser manually to start the tests).  That will confirm that there aren't larger issues with WebGL2.

I suspect the issue may be that some GL state variable has a different default value on the arm macOS WebGL implementation.  Neuroglancer may incorrectly be relying on a behavior that is not guaranteed.  That issue has occurred in the past.  Another possibility is different handling of infinity in shader computations.

Also, if you can test with https://neuroglancer-demo.appspot.com rather than the fafb-specific version, that would be slightly better since it is more up to date, although I don't think there have been any relevant changes.

For a bug like this, my debugging strategy would probably be to modify the shader used for skeletons to first try to get anything to display , and then gradually reduce the different to pinpoint the problem.

**Comment by william-silversmith** [comment]
Thanks for the quick response Jeremy. I tested with https://neuroglancer-demo.appspot.com and it's the same. I'll try `npm run test`next.

**Comment by william-silversmith** [comment]
Test results: `✔ 291 tests completed`

**Comment by jbms** [comment]
I was able to reproduce on an M1 mac, and bisected the problem to this commit 630b043c4a34f6ee3e527b9a580a13b28035e3cf.

I still need to investigate further to see how to fix it, though.

**Comment by william-silversmith** [comment]
Thank you Jeremy! Was going to try something like this but you beat me to
it.

**Comment by jbms** [comment]
Turned out to be a pretty weird bug in the Apple M1 WebGL implementation.

**Comment by william-silversmith** [comment]
That fixed it for me! Thank you so much.

**Comment by SridharJagannathan** [comment]
@jbms I'm also using Big Sur Apple M1, however after installing the latest fix, and starting a new server like below:
```
import neuroglancer as ng
ngviewer = ng.Viewer()

```
I'm getting a 404 error

**Comment by SridharJagannathan** [comment]
Ok, It starts working now.. what I was doing in the beginning was cloning the repo and then running:
`pip install -e .` (this i guess was using the built in wheel)
but when i clone the repo and used:
`python setup.py install` (this runs the full build and compilation i guess)
