### ISSUE TITLE
How does The local dataset "FAFB-ffn1" being loaded with the source method "Local://..."  

### ISSUE THREAD

**Issue by cytheria43** [google/neuroglancer#288]
Someone had downloaded a dataset of drosophila brain called "fafb-ffn1" on my computer.And it has 7 folders like "agglomeration_positives","agglomeration_scores","object_info"."section_to_section_xcorr","segmentation","segmentation_tiffs",and "tissue_mask_argmax". I just took over these jobs and want to know where I can find the descriptions to these data and How to load them with Neuroglancer.   Some data files are end up with .data,.index and .shard

**Comment by jbms** [comment]
@chinasaur 

See description of the dataset here:
http://fafb-ffn1.storage.googleapis.com/landing.html

Most of that is in "neuroglancer_precomputed" format, which is documented here:
https://github.com/google/neuroglancer/tree/master/src/neuroglancer/datasource/precomputed

For the data that is in neuroglancer_precomputed format, if you want to view it locally, you can start a local webserver (see e.g. cors_webserver.py in this repository) and then add the data sources to Neuroglancer as, for example, `precomputed://http://localhost:8080/segmentation`.

**Comment by cytheria43** [comment]
> @chinasaur
> 
> See description of the dataset here:
> http://fafb-ffn1.storage.googleapis.com/landing.html
> 
> Most of that is in "neuroglancer_precomputed" format, which is documented here:
> https://github.com/google/neuroglancer/tree/master/src/neuroglancer/datasource/precomputed
> 
> For the data that is in neuroglancer_precomputed format, if you want to view it locally, you can start a local webserver (see e.g. cors_webserver.py in this repository) and then add the data sources to Neuroglancer as, for example, `precomputed://http://localhost:8080/segmentation`.

1.The information of that webpage is only about the description of FAFB，fafb-ffn1，public_skeleton，etc. 
I just want to know the specific meaning of the data in those folders below "fafb-ffn1",such as csv files in agglomeration_positives,  agglomeration_scores and object_info. 

![2021-03-18 11-03-00 的屏幕截图](https://user-images.githubusercontent.com/41312465/111573907-5f896600-87e6-11eb-8a28-d696e99fec33.png)
![2021-03-18 11-03-13 的屏幕截图](https://user-images.githubusercontent.com/41312465/111573912-657f4700-87e6-11eb-901c-62204dda4128.png)
![2021-03-18 11-03-24 的屏幕截图](https://user-images.githubusercontent.com/41312465/111573922-6a43fb00-87e6-11eb-93a8-faab2c0a6767.png)

2.One of  the tasks is to find the neuron connectors to reconstruct the circuit topological structure among all the neuron data finally. That's why the data meaning important for me to screen the useful data. 
Hope for your reply,thanks!

**Comment by chinasaur** [comment]
These are additional metadata for the 20190805 agglomeration, and not part of the public release. (Note the latest agglomeration is 20200412.)

The object_info gives for each object ID in the segmentation the #voxels and a bounding box (start xyz / size xyz) for where in the volume the segment can be found. The agglomeration_positives give the unagglomerated segment IDs that were joined in the agglomeration stage, as well as xyz coordinates for the decision point. The agglomeration scores give information on all agglomeration decision points, both positive and negative. These are unlikely to be useful to you unless you want to reexamine the agglomeration decisions. You would also probably require the base unagglomerated version of the segmentation, which is not currently released but which we will probably release if there is interest.

**Comment by Virgo1994** [comment]
Also puzzled about the relations between the ida,idb items in agglomeration_scores csv files and the id item in object_info 
 and agglomeration_positives csv files. 
I checked the three folder  mentioned above,  found 10 .csv files in agglomeration_positives  folder with each csv file has 1.7million rows, 100 .csv files in agglomeration_scores  folder with each csv file has 5.2million rows, 100 .csv files in object_info  folder with each csv file has 6.3million rows. 

The agglomeration_scores give information on all agglomeration decision points.   Want to know whether any two segments in the object_info procuce a agglomeration decision points. If yes, there should be 6.3million *6.3million /2 rows in the agglomeration_scores csv file, but only 5.2million  rows。if not ,how to select the 5.2million  agglomeration decision points?
