### ISSUE TITLE
Compatibility issues with precomputed meshes inside SingleMeshLayer

### ISSUE THREAD

**Issue by hash-ir** [google/neuroglancer#290]
Hi, I am trying to render precomputed meshes through `SingleMeshLayer`. I am hosting a separate server that provides the info, metadata and fragments file to neuroglancer. The files are according to the [legacy single-resolution mesh format](https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/meshes.md#legacy-single-resolution-mesh-format).

I receive an error in the frontend, specifically in the side panel source tab: 
![err](https://user-images.githubusercontent.com/45996390/111308368-e0b3f200-865a-11eb-8982-065160103606.PNG)
I want to know if there is something I am doing wrong or there is no compatibility of a precomputed mesh source inside `SingleMeshLayer`

Thank you

**Comment by jbms** [comment]
Yes, precomputed format meshes should be used with three segmentation layer type.
