### ISSUE TITLE
Precomputed mesh chunk loading

### ISSUE THREAD

**Issue by davidackerman** [google/neuroglancer#301]
I am able to generate multiresolution meshes and load them into neuroglancer. The meshes look good and the transitions seem okay at the lower resolutions, but towards the higher resolutions I notice that they don't seem to load in an order that makes sense; in some cases things far off appear to load at higher resolutions before things up close. In some cases, the things up close never load at the high detail I would expect. See attached images, where the high res mesh has loaded for the part of the object that is farther away but never loads for the part that is closer (you can see the seam between chunks). Would this be expected where lower res chunks meet? Could this be because my higher resolution meshes take up too much memory? Or could this have to do with the fact I am setting `grid_origin` and `vertex_offsets` to `[0,0,0]`, and calculate `fragment_positions` based on a given chunk's overall position in the dataset?
![image](https://user-images.githubusercontent.com/19193291/114974696-e155c900-9e50-11eb-8631-c1d9614efadc.png)
![image](https://user-images.githubusercontent.com/19193291/114974774-0813ff80-9e51-11eb-87b8-58543ad9b166.png)

**Comment by jbms** [comment]
You can see under "Resolution (mesh)" that it shows 33/33 chunks loaded on the top and 21/21 chunks loaded on the bottom, which indicates it isn't a memory limit.  It would show less than all chunks loaded if it was limited by memory.

It is hard for to know what the problem is just by looking at it.  It is possible there is a bug in Neuroglancer's level of detail selection.  Can you reproduce this problem on one of the public multiscale mesh datasets, or perhaps share your mesh?

If you adjust the Resolution (mesh) setting to be smaller than 1px (e.g. using the mouse wheel), does that eventually cause the higher resolution mesh to load?

**Comment by davidackerman** [comment]
Thanks for the prompt response! It never loads, even when setting the Resolution to smaller than 1px. You can find my multiresolution meshes here: https://drive.google.com/drive/folders/1f2uk5CjiDiNizaEuF07NQzSodKpnB7f0. Let me know if you'd like me to provide it another way. The particular one I showed was `2`, but it shows up for others, including `23` which is the largest by far. 

I haven't seen it in other datasets, but I have only really looked at the hemibrain data which I guess uses dvid.

**Comment by davidackerman** [comment]
If it helps, here is another example of higher res meshes displaying for far-off chunks, while they never load for certain chunks even if they are closer. The data is shared here: https://drive.google.com/drive/folders/1TOmyGDPF90FZ6I5gAxtj4nWhLPciihNY?usp=sharing.  And here is a [neuroglancer link](http://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B6464.78564453125%2C378.93304443359375%2C2905.093017578125%5D%2C%22crossSectionScale%22:5.485032425775548%2C%22projectionOrientation%22:%5B0.9632424712181091%2C0.22005099058151245%2C-0.08551645278930664%2C0.12817363440990448%5D%2C%22projectionScale%22:319.05225206851765%2C%22projectionDepth%22:-232.066276497698%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://http://10.150.100.248:8080/meshesForWebsite/multiresolution/HeLa2/meshes/golgi_testLoopRemoveOriginNoSmoothOrDecimate%22%2C%22tab%22:%22segments%22%2C%22meshRenderScale%22:0.2842890552926824%2C%22segments%22:%5B%221%22%2C%222%22%2C%223%22%2C%224%22%2C%225%22%2C%226%22%2C%227%22%2C%228%22%5D%2C%22segmentQuery%22:%221%202%203%204%205%206%207%208%22%2C%22name%22:%22test%22%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22layer%22:%22test%22%2C%22size%22:290%7D%2C%22crossSectionBackgroundColor%22:%22#000000%22%2C%22layout%22:%223d%22%2C%22statistics%22:%7B%22visible%22:true%7D%7D) I used for the latest screenshot in case it is useful to reproduce the issue.
![image](https://user-images.githubusercontent.com/19193291/115040328-505a0e80-9e9f-11eb-97cd-9cb30bbe31a8.png)
![image](https://user-images.githubusercontent.com/19193291/115040699-b21a7880-9e9f-11eb-8d6c-bf0bf28d6544.png)

**Comment by davidackerman** [comment]
Debugging Update: I used the code below to download all the meshes for example for lod 0 just to make sure they look ok. There should be 42 fragments at lod 0 for this object and indeed I do get that. Loading them into a mesh viewer shows what I would expect (first two images). However, neuroglancer never loads more than 27 meshes for this fragment (last image, where you can the low vs high res meshes). For reference, this mesh is id 3 [here].(https://drive.google.com/drive/folders/1TOmyGDPF90FZ6I5gAxtj4nWhLPciihNY?usp=sharing).

```python
from struct import *
import os
import numpy as np
import trimesh

def unpack_and_remove(datatype,num_elements,file_content):
    datatype = datatype*num_elements
    output = unpack(datatype, file_content[0:4*num_elements])
    file_content = file_content[4*num_elements:] 
    return np.array(output),file_content

#ile_name = "multires/1.index"
file_name = "/groups/cosem/cosem/ackermand/meshesForWebsite/multiresolution/HeLa2/meshes/golgi_testLoopRemoveOriginNoSmoothOrDecimate/3.index"
with open(file_name, mode='rb') as file:
    file_content = file.read()

chunk_shape,file_content = unpack_and_remove("f",3,file_content)
grid_origin,file_content = unpack_and_remove("f",3,file_content)
num_lods,file_content = unpack_and_remove("I",1,file_content)
lod_scales,file_content = unpack_and_remove("f",num_lods[0],file_content)
vertex_offsets,file_content = unpack_and_remove("I",num_lods[0]*3,file_content)
num_fragments_per_lod,file_content = unpack_and_remove("I",num_lods[0],file_content)

print(f"chunk_shape: {chunk_shape}")
print(f"grid_origin: {grid_origin}")
print(f"num_lods: {num_lods}")
print(f"lod_scales: {lod_scales}")
print(f"vertex_offsets: {vertex_offsets}")
print(f"num_fragments_per_lod: {num_fragments_per_lod}")

vertex_quantization_bits = 10
cum_sum_total = 0
for lod in range(num_lods[0]):
    fragment_positions,file_content = unpack_and_remove("I",num_fragments_per_lod[lod]*3,file_content)
    fragment_positions = fragment_positions.reshape((3,-1)).T
    fragment_offsets,file_content = unpack_and_remove("I",num_fragments_per_lod[lod],file_content)
    print(f"lod {lod} fragment_positions: {fragment_positions}")
    print(f"lod {lod} fragment_offsets: {fragment_offsets}")
    cum_sum = np.cumsum(np.array(fragment_offsets))+cum_sum_total
    cum_sum = np.insert(cum_sum, 0, cum_sum_total)
    cum_sum_total = cum_sum[-1] # end of previous lod
    print(f"lod {lod} fragment_cumsum: {cum_sum}")
    
    for idx,fragment_offset in enumerate(fragment_offsets):
        output_path = f"/groups/cosem/cosem/ackermand/testDownloadingMeshes/lod{lod}/{idx}"
        os.system(f"curl http://10.150.100.248:8080/meshesForWebsite/multiresolution/HeLa2/meshes/golgi_testLoopRemoveOriginNoSmoothOrDecimate/3 -H \"range: bytes={cum_sum[idx]}-{cum_sum[idx+1]}\" --output {output_path}")
        #os.system(f"curl http://10.150.100.248:8080/temp_data/multires/1 -H \"range: bytes={cum_sum[idx]}-{cum_sum[idx+1]}\" --output {output_path}")
        os.system(f"draco_decoder -i {output_path} -o {output_path}.obj")
        mesh = trimesh.load(f"{output_path}.obj")
        mesh.vertices=grid_origin+vertex_offsets[lod]+chunk_shape*(2**lod)*(fragment_positions[idx]+mesh.vertices/(2**vertex_quantization_bits))
        os.system(f"rm {output_path}.obj")
        mesh.export(f"{output_path}.obj")
```

![image](https://user-images.githubusercontent.com/19193291/115069601-ca9b8a80-9ec1-11eb-9f0e-ff04e2591373.png)
![image](https://user-images.githubusercontent.com/19193291/115070407-e4899d00-9ec2-11eb-9ecf-172015bbe6ca.png)

![image](https://user-images.githubusercontent.com/19193291/115069765-0d5d6280-9ec2-11eb-9ee1-88ccbbd9538a.png)

**Comment by jbms** [comment]
I'm still investigating, but it appears that there is a problem with the octree that Neuroglancer constructs from the index file.  I suspect it is a bug in Neuroglancer.

**Comment by jbms** [comment]
Actually the problem is that your mesh index does not sort the fragments within each level by zcurve order, as required by the format:
https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/meshes.md#multi-resolution-mesh-manifest-file-format

That results in Neuroglancer producing an incorrect octree, where many of the nodes are orphans not reachable from the root.  Neuroglancer could be modified to sort the fragments, but currently for simplicity the octree construction assumes that the fragments have the correct order.

You can see the errors if you enable the `DEBUG_MULTISCALE_INDEX = true` option in the code and rebuild.  I just added that option in this commit:
https://github.com/google/neuroglancer/commit/ac94ef6d2b6d47abfcd7d32cce0e1ac3070817bb

**Comment by davidackerman** [comment]
That did it, thanks so much! I naively was calculating Zorder using absolute fragment positions rather than their absolute positions divided by the chunk shape.
