### ISSUE TITLE
Multiresolution meshes prevent section images from loading

### ISSUE THREAD

**Issue by davidackerman** [google/neuroglancer#304]
Hello,

We have noticed that loading multiresolution meshes can inhibit the loading of image and segmentation layers. Here is an [example of a single resolution mesh view](http://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B23900.5%2C3250.5%2C13334.5%5D%2C%22crossSectionScale%22:50%2C%22projectionOrientation%22:%5B-0.2857867181301117%2C-0.2584522068500519%2C-0.043452195823192596%2C0.9217593669891357%5D%2C%22projectionScale%22:5915.6395202828%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%5B%7B%22url%22:%22n5://https://janelia-cosem.s3.amazonaws.com/jrc_hela-2/jrc_hela-2.n5/labels/er_seg%22%2C%22transform%22:%7B%22outputDimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22inputDimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B5.240000000000001e-9%2C%22m%22%5D%7D%7D%7D%2C%7B%22url%22:%22precomputed://https://janelia-cosem.s3.amazonaws.com/jrc_hela-2/neuroglancer/mesh/er_seg%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%5D%2C%5B0%2C-1%2C0%2C6400%5D%2C%5B0%2C0%2C1%2C0%5D%5D%2C%22outputDimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%7D%7D%5D%2C%22tab%22:%22segments%22%2C%22segments%22:%5B%221%22%2C%2210%22%2C%2211%22%2C%2212%22%2C%2213%22%2C%2214%22%2C%2215%22%2C%2216%22%2C%2217%22%2C%2218%22%2C%2219%22%2C%222%22%2C%2220%22%2C%2221%22%2C%2222%22%2C%2223%22%2C%2224%22%2C%223%22%2C%224%22%2C%225%22%2C%226%22%2C%227%22%2C%228%22%2C%229%22%5D%2C%22name%22:%22er_seg%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22precomputed://https://janelia-cosem.s3.amazonaws.com/jrc_hela-2/neuroglancer/em/fibsem-uint8.precomputed%22%2C%22transform%22:%7B%22outputDimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22inputDimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B5.240000000000001e-9%2C%22m%22%5D%7D%7D%7D%2C%22opacity%22:0.75%2C%22blend%22:%22additive%22%2C%22shader%22:%22#uicontrol%20invlerp%20normalized%28range=%5B105.82499999999999%2C%20182.57999999999998%5D%2C%20window=%5B0%2C%20255%5D%29%5Cn%20%20%20%20%20%20%20%20#uicontrol%20int%20invertColormap%20slider%28min=0%2C%20max=1%2C%20step=1%2C%20default=0%29%5Cn%20%20%20%20%20%20%20%20#uicontrol%20vec3%20color%20color%28default=%5C%22white%5C%22%29%5Cn%20%20%20%20%20%20%20%20float%20inverter%28float%20val%2C%20int%20invert%29%20%7Breturn%200.5%20+%20%28%282.0%20%2A%20%28-float%28invert%29%20+%200.5%29%29%20%2A%20%28val%20-%200.5%29%29%3B%7D%5Cn%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20emitRGB%28color%20%2A%20inverter%28normalized%28%29%2C%20invertColormap%29%29%3B%5Cn%20%20%20%20%20%20%20%20%7D%22%2C%22name%22:%22fibsem-uint8%22%7D%5D%2C%22selectedLayer%22:%7B%22layer%22:%22er_seg%22%2C%22visible%22:true%7D%2C%22crossSectionBackgroundColor%22:%22#000000%22%2C%22layout%22:%224panel%22%2C%22statistics%22:%7B%22visible%22:true%2C%22size%22:183%7D%7D), and here is the [same view using multiresolution meshes](http://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B23900.5%2C3250.5%2C13334.5%5D%2C%22crossSectionScale%22:50%2C%22projectionOrientation%22:%5B-0.2857867181301117%2C-0.2584522068500519%2C-0.043452195823192596%2C0.9217593669891357%5D%2C%22projectionScale%22:5915.6395202828%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%5B%7B%22url%22:%22n5://https://janelia-cosem.s3.amazonaws.com/jrc_hela-2/jrc_hela-2.n5/labels/er_seg%22%2C%22transform%22:%7B%22outputDimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22inputDimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B5.240000000000001e-9%2C%22m%22%5D%7D%7D%7D%2C%7B%22url%22:%22precomputed://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-2/neuroglancer/mesh/er_seg%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%5D%2C%5B0%2C-1%2C0%2C6400%5D%2C%5B0%2C0%2C1%2C0%5D%5D%2C%22outputDimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22inputDimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B5.24e-9%2C%22m%22%5D%7D%7D%7D%5D%2C%22tab%22:%22source%22%2C%22segments%22:%5B%221%22%2C%2210%22%2C%2211%22%2C%2212%22%2C%2213%22%2C%2214%22%2C%2215%22%2C%2216%22%2C%2217%22%2C%2218%22%2C%2219%22%2C%222%22%2C%2220%22%2C%2221%22%2C%2222%22%2C%2223%22%2C%2224%22%2C%223%22%2C%224%22%2C%225%22%2C%226%22%2C%227%22%2C%228%22%2C%229%22%5D%2C%22name%22:%22er_seg%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22precomputed://https://janelia-cosem.s3.amazonaws.com/jrc_hela-2/neuroglancer/em/fibsem-uint8.precomputed%22%2C%22transform%22:%7B%22outputDimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22inputDimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B5.240000000000001e-9%2C%22m%22%5D%7D%7D%7D%2C%22opacity%22:0.75%2C%22blend%22:%22additive%22%2C%22shader%22:%22#uicontrol%20invlerp%20normalized%28range=%5B105.82499999999999%2C%20182.57999999999998%5D%2C%20window=%5B0%2C%20255%5D%29%5Cn%20%20%20%20%20%20%20%20#uicontrol%20int%20invertColormap%20slider%28min=0%2C%20max=1%2C%20step=1%2C%20default=0%29%5Cn%20%20%20%20%20%20%20%20#uicontrol%20vec3%20color%20color%28default=%5C%22white%5C%22%29%5Cn%20%20%20%20%20%20%20%20float%20inverter%28float%20val%2C%20int%20invert%29%20%7Breturn%200.5%20+%20%28%282.0%20%2A%20%28-float%28invert%29%20+%200.5%29%29%20%2A%20%28val%20-%200.5%29%29%3B%7D%5Cn%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20emitRGB%28color%20%2A%20inverter%28normalized%28%29%2C%20invertColormap%29%29%3B%5Cn%20%20%20%20%20%20%20%20%7D%22%2C%22name%22:%22fibsem-uint8%22%7D%5D%2C%22selectedLayer%22:%7B%22layer%22:%22er_seg%22%2C%22visible%22:true%7D%2C%22crossSectionBackgroundColor%22:%22#000000%22%2C%22layout%22:%224panel%22%7D). Depending on zooming in and out, the segmentation and image layers go black:

<img width="1514" alt="Screen Shot 2021-04-27 at 9 50 34 PM" src="https://user-images.githubusercontent.com/19193291/116334185-cb2a0000-a7a2-11eb-824c-6da566d8110b.png">

but it doesn't seem to happen to single-res meshes:

<img width="1514" alt="Screen Shot 2021-04-27 at 9 50 42 PM" src="https://user-images.githubusercontent.com/19193291/116334202-d1b87780-a7a2-11eb-94fc-11387727b70d.png">

Could this be due to the size of the meshes? 

Also, is there a reason that when defining a transform for the meshes, the color bars in the Resolution slider all turn red and say "unknown" when scrolling over them?

<img width="300" alt="Screen Shot 2021-04-27 at 9 54 26 PM" src="https://user-images.githubusercontent.com/19193291/116334418-2c51d380-a7a3-11eb-9983-9ef93f091041.png">

If it is due to the size of the mesh/loading too much high res data at once, are there any recommendations for `lod_scales` and `lod_scale_mutliplier`?

Finally, is there a way to automatically have all ids in a mesh display so that they all load by default, without having to define such a property in the url or the state.json file? I know that we can select "Show all segments if none selected", but this doesn't seem to apply to meshes?

Thanks for all your help and great viewer!
David

**Comment by jbms** [comment]
You can see in the chunk statistics that your meshes are using 1GB of memory, which is the default limit.  You can increase the limit e.g. up to 2GB via the setting menu, accessible by right clicking the blank space on the top bar.   You can't make it too high, though, or you will exceed limits imposed by the browser and the page will crash.

I would suggest simplifying your meshes, e.g. using quadric error-based mesh simplification.  You can refer to the mesh generation code in the Python package for an example of that.  I suspect you could reduce the size 100x or more without significantly impacting the quality.

Currently Neuroglancer does not provide a way to load all meshes.  The closest you can do is define a segment properties file for the volume (https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/segment_properties.md).  Note: use inline properties only, indexed properties are not actually implemented yet.

If you add a segment properties datasource to a layer, or have it included automatically by referencing it from an existing precomputed volume info file via the "segment_properties" member, then the "Seg" tab in neuroglancer will list all of the segments with their labels, and there is an easy way to select all of them.

**Comment by davidackerman** [comment]
Thank you for the suggestions!

**Comment by jbms** [comment]
As for the resolution slider not showing the correct information when using a coordinate transform --- that sounds like a bug, and likely is causing too-high-resolution meshes to be loaded.  I will have to look into that.

**Comment by davidackerman** [comment]
I don't know if this is related to that potential bug, but even without adjusting the transformation for the mesh, at borders between chunks, it seems that something is left over when higher res meshes are drawn. See this [link](http://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B8063.17236328125%2C2142.739501953125%2C13820.814453125%5D%2C%22crossSectionScale%22:91.10594001952546%2C%22projectionOrientation%22:%5B-0.18497663736343384%2C-0.0475139245390892%2C0.9666544198989868%2C0.1706027239561081%5D%2C%22projectionScale%22:36.79473958727185%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%5B%7B%22url%22:%22n5://https://janelia-cosem.s3.amazonaws.com/jrc_hela-2/jrc_hela-2.n5/labels/er_seg%22%2C%22transform%22:%7B%22outputDimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22inputDimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B5.240000000000001e-9%2C%22m%22%5D%7D%7D%7D%2C%7B%22url%22:%22precomputed://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-2/neuroglancer/mesh/er_seg%22%2C%22transform%22:%7B%22outputDimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22inputDimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B5.24e-9%2C%22m%22%5D%7D%7D%7D%5D%2C%22tab%22:%22rendering%22%2C%22segments%22:%5B%221%22%2C%2210%22%2C%2211%22%2C%2212%22%2C%2213%22%2C%2214%22%2C%2215%22%2C%2216%22%2C%2217%22%2C%2218%22%2C%2219%22%2C%222%22%2C%2220%22%2C%2221%22%2C%2222%22%2C%2223%22%2C%2224%22%2C%223%22%2C%224%22%2C%225%22%2C%226%22%2C%227%22%2C%228%22%2C%229%22%5D%2C%22segmentQuery%22:%221%202%203%204%205%206%207%208%209%2010%2011%2012%2013%2014%2015%2016%2017%2018%2019%2020%2021%2022%2023%2024%22%2C%22name%22:%22er_seg%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22precomputed://https://janelia-cosem.s3.amazonaws.com/jrc_hela-2/neuroglancer/em/fibsem-uint8.precomputed%22%2C%22transform%22:%7B%22outputDimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22inputDimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B5.240000000000001e-9%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22opacity%22:0.75%2C%22blend%22:%22additive%22%2C%22shader%22:%22#uicontrol%20invlerp%20normalized%28range=%5B105.82499999999999%2C%20182.57999999999998%5D%2C%20window=%5B0%2C%20255%5D%29%5Cn%20%20%20%20%20%20%20%20#uicontrol%20int%20invertColormap%20slider%28min=0%2C%20max=1%2C%20step=1%2C%20default=0%29%5Cn%20%20%20%20%20%20%20%20#uicontrol%20vec3%20color%20color%28default=%5C%22white%5C%22%29%5Cn%20%20%20%20%20%20%20%20float%20inverter%28float%20val%2C%20int%20invert%29%20%7Breturn%200.5%20+%20%28%282.0%20%2A%20%28-float%28invert%29%20+%200.5%29%29%20%2A%20%28val%20-%200.5%29%29%3B%7D%5Cn%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20emitRGB%28color%20%2A%20inverter%28normalized%28%29%2C%20invertColormap%29%29%3B%5Cn%20%20%20%20%20%20%20%20%7D%22%2C%22name%22:%22fibsem-uint8%22%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22er_seg%22%7D%2C%22crossSectionBackgroundColor%22:%22#000000%22%2C%22layout%22:%223d%22%2C%22statistics%22:%7B%22size%22:255%2C%22visible%22:true%7D%7D). 

<img width="1536" alt="Screen Shot 2021-04-28 at 11 04 21 PM" src="https://user-images.githubusercontent.com/19193291/116497774-22e56b80-a876-11eb-91b9-31985d4e5dda.png">

**Comment by davidackerman** [comment]
@jbms the aforementioned issue regarding loading incorrect chunks seems to be somewhat consistent. A movie, and corresponding data showing this can be found [here](https://drive.google.com/drive/folders/1LpiZ54Otv0_zMM5QzNeQ6cb747STQj5_?usp=sharing), and [this](http://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B144.98440551757812%2C109.1095199584961%2C96.31974029541016%5D%2C%22crossSectionScale%22:1%2C%22projectionOrientation%22:%5B-0.15970319509506226%2C-0.3279259502887726%2C0.16977159678936005%2C0.9154982566833496%5D%2C%22projectionScale%22:3.6701106284333997%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://http://10.150.100.248:8080/temp_data/multires%22%2C%22tab%22:%22source%22%2C%22meshRenderScale%22:0.23160908972505603%2C%22segments%22:%5B%225%22%5D%2C%22segmentQuery%22:%225%22%2C%22name%22:%22multires%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22multires%22%7D%2C%22layout%22:%223d%22%2C%22statistics%22:%7B%22visible%22:true%7D%7D) is the view I used if it is helpful. As you can see, when zoomed in and with the resolution set high, I still see this extra protrusion from I presume another chunk.

**Comment by davidackerman** [comment]
I'm also noticing that the Visible Chunk values listed in the Chunk Statistics panel are showing the total chunks, rather than just the chunks for the current lod only. Is that correct? I believe this is also reflected in the visible memory. For example, in the snapshot below, I am setting it to load only the highest res which should contain 4 chunks total, but as you can see, the visible chunks is equal to the sum of the number of chunks over all 5 lods: [4, 4, 1, 1, 1]. (Currently, for simplicity, I set the grid origin and vertex offsets to 0 rather than measuring from the start of the object, hence why the first two lods here contain the same number of chunks (but of different sizes)). This is having the effect that if I make a multiresolution mesh of 6 lods, iit can show increased memory consumption compared to a mesh of 5 lods, since the more numerous lower res lods still contribute to the memory consumption even when they shouldn't be loaded. Is this a bug on my end? Could this be due to how I am defining the grid origin and vertex offsets? Or is this something in neuroglancer?

![image](https://user-images.githubusercontent.com/19193291/117239230-66068800-adfc-11eb-92af-cef7d91d1f39.png)

**Comment by jbms** [comment]
Neuroglancer manages data via a priority system --- each chunk that is visible is assigned a numerical priority.  Chunks at coarser lod are assigned a higher priority than finer lod chunks.  The priority determines the order in which chunks are downloaded, if the number of chunks to be downloaded exceeds the number of available download slots (32 by default), and if the memory limit is reached also determines which chunks are evicted first.

As you observed, this results in coarser lods always being downloaded, even if it is not actually needed because an entire finer lod has already been downloaded.  While it may be possible to implement a different policy, it would be somewhat trickier to implement, and note that there are some advantages to downloading the coarser chunks:
- The coarser mesh loads first, so that you can see a coarse view of the object faster.
- As you change the viewing position/angle, you retain the coarse mesh, which ensure the object remains visible; if the coarse mesh wasn't downloaded, then the object may disappear entirely as you zoom out until the coarser fragment is loaded.
- If the finer mesh must be evicted to make room for another object, you still have the coarse mesh to fall back on.  Otherwise it would just disappear entirely, or some more complicated mechanism would be required to decide which level of detail to load.
- In most cases, even for a single object we don't load all fragments at the finest level of detail, only a few of them.  The scenario you describe where all the finest-lod chunks are needed is assumed to be somewhat unlikely.
- The coarser lods should ideally be significantly smaller than the finer lods, so that the total added size, even if you did load all of the fragments at all lods, is fairly small, e.g. <25% extra.

**Comment by davidackerman** [comment]
Thanks for the info! I started to realize that is what was going on, but it is nice to have it confirmed and it makes sense. Does that have anything to do with the parts of chunks from different lods that I see eg. [here](https://github.com/google/neuroglancer/issues/304#issuecomment-830481370) and [here](https://github.com/google/neuroglancer/issues/304#issuecomment-828910053). In those cases It seems like only part of a lower res chunk is loaded and does not replace the higher res chunks. It seems to occur at chunk boundaries and becomes very noticeable when small chunks are used.

**Comment by jbms** [comment]
I have looked into this a bit more, though I have still not fully gotten to the bottom of it.

I added some additional mesh debugging options here, which you may find helpful:
https://github.com/google/neuroglancer/commit/dfb67037da6490c176bec431173ba34446dc86d6

If you set those two variables to true, then when you hover over a rendered mesh, the developer console will show which fragment and lod is responsible for it.

I did notice that your meshes still seem to have an invalid octree, as validated by validateOctree, which is run when `DEBUG_MULTISCALE_FRAGMENTS=true`.  It would be good to fix that first to be sure it is not the cause of the rendering issue.

**Comment by davidackerman** [comment]
Thanks for the reply! I turned on debugging and I checked again, but didn't see any issues with the octrees in the links I sent. Could you point me to which dataset you are referring? For example, I don't see an issue with the octree in the data described here https://github.com/google/neuroglancer/issues/307#issue-884339190. But I still do see the chunk loading issue there. See below for screenshot of that data with debugging turned on.
![image](https://user-images.githubusercontent.com/19193291/117731529-4389bb80-b1bc-11eb-8a76-d11d91efbc38.png)

**Comment by davidackerman** [comment]
For some reason, everything seems to be in the correct order for me in that link (and seems to be correct when I recheck the index file).

But either way, I think the octrees are correct in the most recent data, unless I am still getting something wrong about the octree ordering/debugging.

![image](https://user-images.githubusercontent.com/19193291/117854948-fc510880-b257-11eb-8ed5-e3d55ff665ed.png)
