### ISSUE TITLE
signed int segmentation

### ISSUE THREAD

**Issue by chrisroat** [google/neuroglancer#312]
Are signed ints supported for segmentation?  I do not see any errors when I try to load them, but they are not visualizing properly.  The data loads, but the display is simply a grey box.  If I mouse over the pixels, the values do appear.  Is there some extra setting I might need?

As a positive controls, I used a small 2x2x2 volume and I verified that uint64, uint32, uint16 all work.  

I have verified that int32 and int16 show these symptoms.  I am using the current HEAD of the repo for my viewer, and tried both Chrome 91 and Firefox 89 on MacOS 11.4.

**Comment by jbms** [comment]
Currently they are not supported.  Adding support to Neuroglancer for them to display, by effectively treating them as unsigned integers, would be quite simple.  Making it possible to handle negative numbers in the list of selected segments, etc. would be somewhat more complicated.

**Comment by chrisroat** [comment]
The segmenter I'm using is returning int32, which I just blindly passed along.  I have not created much data yet.  I'm happy to just convert inside my code, so there is no need to commit to an approach now.

**Comment by jbms** [comment]
Assuming there are no negative values, you can also just change the n5 or zarr data type to uint32 in the metadata file --- no need to actually rewrite the data.

**Comment by chrisroat** [comment]
I'm using precomputed format.  Would a metadata switch work for it as well?

**Comment by jbms** [comment]
Yes, that will work for precomputed format as well.

**Comment by ecc521** [comment]
Just encountered this issue as well - while it's trivial workaround, debugging can take a while, as there is no error message provided, and the values are identical to those in segmentations that work. 

I assume it would be rather trivial to add either an error message, or convert to unsigned integers (especially since changing the data type works)? If so, I can't think of a good reason not to add this.
