### ISSUE TITLE
Single-scale n5 datasets with missing or inaccessible attributes

### ISSUE THREAD

**Issue by perlman** [google/neuroglancer#313]
I have been trying to debug an issue where Neuroglancer fails to load single-scale n5 volumes. The failure seems to be related to accessing missing `attributes.json` files (e.g. 404, 403 or missing CORS). In all cases, the existing `attributes.json` *are* successfully accessed.

Neuroglancer will scan for `attributes.json` but does not attempt any data loading in the following situations:
* AWS S3 returning 403 errors instead of 404
** `n5://https://pooja-lightsheet-175.s3-us-west-1.amazonaws.com/substack/tiles.n5/substack/Cropped_Rotated_ex1_MMStack_Pos0_6.ome.tif/`
* 404 errors _not_ including CORS headers
** `n5://https://www.yikes.com/~eric/test/tiles.n5/substack/Cropped_Rotated_ex1_MMStack_Pos0_6.ome.tif/`

This *does* work:
* 404 errors including CORS headers
** Tested with [this](http://www.yikes.com/~eric/test/min.n5.tar.gz) very minimal example hosted with `http-server --cors`.
** Neuroglancer _will_ attempt to load the missing chunks (e.g. `/min.n5/substack/Cropped_Rotated_ex1_MMStack_Pos0_6.ome.tif/6/3/1`)

#229 fixed the issue multi-scale n5 volumes on S3. It's not immediately clear to me why this did not extend to single-scale as well.

**Comment by jbms** [comment]
Your first example already seemed to work (AWS S3 returning 403 errors instead of 404) but the second example did not.

**Comment by perlman** [comment]
Thanks Jeremy! I'm not sure why I thought this was something more complex... 🤦
