### ISSUE TITLE
Feature request: Set tab title via viewer state

### ISSUE THREAD

**Issue by stuarteberg** [google/neuroglancer#315]
When I have several neuroglancer tabs open, I have trouble remembering which one is which.  It would be great if I could set the title of the page via the viewer state JSON.

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/1655821/121118786-738ea380-c7e8-11eb-8c59-e8170271685a.png">

Bonus points if it appears as the first key in the JSON state, so the title can even be scanned by eye when viewing the raw URL (e.g. in an email or text file).

```
https://neuroglancer-demo.appspot.com/#!%7B%22title%22:%22central-complex%22%2C%20%22dimensions%22:...
```

**Comment by jbms** [comment]
I added this feature.  The only thing is that it seems a bit annoying to have to type in a title manually.  Ideally the title could be chosen automatically somehow from the layers --- but choosing a short title from that would be tricky, and wouldn't necessarily highlight the most important aspect.

**Comment by stuarteberg** [comment]
Thanks!  Typing the title manually isn't a problem.  In fact, I'd much prefer to control it myself.

Thanks again, this will really help me for some of my use-cases.
