### ISSUE TITLE
Read/Write Neuroglancer State in an iframe with onMessage

### ISSUE THREAD

**Issue by unidesigner** [google/neuroglancer#324]
Hi!

I'd like to understand if it is possible to read/set neuroglancer state via the postMessage/onMessage listeners when a neuroglancer instance is embedded via iframes? [If read this code correctly,](https://github.com/google/neuroglancer/blob/8432f531c4d8eb421556ec36926a29d9064c2d3c/src/neuroglancer/python_integration/server_connection.ts#L139) this is already what is used when communicating with a local Python server instance. And also, if this would still work a cross-sites?

Thanks, Stephan

**Comment by jbms** [comment]
The Python code communicates via sockjs, which is unrelated to postMessage/onMessage.

Currently there is no postMessage-based API for communicating with Neuroglancer in an iframe, and for security reasons it would likely never be supported cross-origin.  However, to avoid cross-origin issues, you can instead just host your own copy of the Neuroglancer client on the same origin as the one that embeds it.

Within the same origin, though, you can control Neuroglancer to some extent via its internal JavaScript API: the `Viewer` object is exposed as the global `viewer` object on the iframe's window.  You can use, for example, viewer.state.toJSON() and viewer.state.restoreState.  Unfortunately there is currently no stability guarantee on the internal JavaScript API, so you may have to update your code when you update to a newer version of Neuroglancer, depending on which APIs you access.  Additionally, while you can access properties and methods via the viewer object, it is not really possible to access functions defined at module scope.

There are a few other projects you might also look at:

If you are using react, you might look at: https://github.com/neuroglancerhub/react-neuroglancer created by Janelia FlyEM

There is also this extension created by the Seung Lab: https://github.com/seung-lab/ng-extend

**Comment by unidesigner** [comment]
Yes, I am using react. Thank you for your answer, I will look further into the different options. I already had a look at react-neuroglancer, and was just wondering for "simpler" use cases (like changing the location, adding/removing segments and changing their colors), a solution with iframes and updating state, either via the `viewer` object or by changing the hash in the url, might be simpler.

I am also trying to understand the pros/cons of the different approaches of developing UI components/widgets together with Neuroglancer. Just created another issue for this topic as it is unrelated to this one, #326.

**Comment by unidesigner** [comment]
As the related discussion followed in #326 I close this issue for now.
