### ISSUE TITLE
NGAuth permissions by group membership

### ISSUE THREAD

**Issue by chrisroat** [google/neuroglancer#325]
The [limitations setting up NGAuth](https://github.com/google/neuroglancer/tree/master/ngauth_server#limitations) indicate group membership cannot be used in **most** cases.  In what cases could it be possible?

> In most cases it is *not* possible for ngauth to resolve permissions granted to a user indirectly via group membership. Instead, users must be listed directly in the bucket or project IAM policy.

**Comment by jbms** [comment]
I have not tested it, but what I was told is that it can work if you are using gsuite/google workspaces and in the gsuite admin console for gsuite groups, you grant the service account used by ngauth domain wide delegation and groups readonly app access.

**Comment by chrisroat** [comment]
Thanks for the info.  I want to be able to use either workspace or consumer groups, so I'll stick with user enumeration.
