### ISSUE TITLE
DVID Labelmap instance inaccessible

### ISSUE THREAD

**Issue by liammm-lza** [google/neuroglancer#335]
Hi,

I tried to load data through DVID. Images are stored in uintb8blk, while segmentation is stored in labelmap. Images loading are fine. However, the labelmap instance seems invisible to Neuroglancer.  I checked DVID info. Labelmap is within the DVID DataInstance object. I will be really appreciate it if anyone can share their experience on this issue.

**Comment by jbms** [comment]
If you can provide an example that reproduces this on a server I can access, I can try to look into it.

**Comment by liammm-lza** [comment]
> If you can provide an example that reproduces this on a server I can access, I can try to look into it.

It seems it's an issue with the parameter **resolution level**. NeuroGlancer expects a None-zero value, while the default is 0 when creating a labelmap on DVID. After setting it to 2 or 3, it works perfectly. Thanks a lot anyway!
