### ISSUE TITLE
GZIP decoding the precomputed volume

### ISSUE THREAD

**Issue by hash-ir** [google/neuroglancer#336]
Hi,

I am serving precomputed volumes with the encoding set to `"compressed_segmentation"`. As per the [compressed segmentation format](https://github.com/google/neuroglancer/tree/8432f531c4d8eb421556ec36926a29d9064c2d3c/src/neuroglancer/sliceview/compressed_segmentation), one can further compress the data using gzip. To try it out, I set the `Content-encoding` header to `gzip` using tornado's `RequestHandler.set_header`. However, I get the "Error retrieving chunk: Error decoding" in the `chunk_manager`. 

I noticed that neuroglancer supports [gzip decoding](https://github.com/google/neuroglancer/blob/8432f531c4d8eb421556ec36926a29d9064c2d3c/src/neuroglancer/util/gzip.ts) but this module is not used in the `chunk_manager`. Is there something I have to change in the frontend? Or write my own encoding and decoding modules?

Best regards,
Hashir

**Comment by jbms** [comment]
If you set content-encoding: gzip, the browser will actually decode automatically.  Neuroglancer receives it already decoded. However, in addition to setting the header, you must also actually gzip encode the response.

**Comment by hash-ir** [comment]
That helped solve my issue. Thanks a lot @jbms
