### ISSUE TITLE
Missing slice resolution after transform

### ISSUE THREAD

**Issue by Martiantian** [google/neuroglancer#337]
Hi, I was trying to use the transformation matrix to adjust the position, and a strange phenomenon occurred. When changing these values in the matrix, the cross section is left with only one resolution, and the high resolution data seems to be lost. 

![m1](https://user-images.githubusercontent.com/35797239/130379577-f8bc962d-935e-4537-8a32-12d3e4fac546.png)
![m2](https://user-images.githubusercontent.com/35797239/130379583-4419c723-6119-4bae-93f4-7d96c31a3faa.png)

This does not happen when i change this value in the matrix.

![m3](https://user-images.githubusercontent.com/35797239/130379586-b3b9a48b-3e4e-4722-a3c9-693f38b401fd.png)

I tried the same thing with public data and got the same results (https://neurodata.io/data/bock11/), so it shouldn't be my own data.
So how can I adjust the position of the data in neuroglancer and keep the corresponding multi-resolution section?

**Comment by jbms** [comment]
Can you provide an example link that demonstrates the problem?

**Comment by Martiantian** [comment]
[https://viz.neurodata.io/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-8%2C%22m%22%5D%7D%2C%22position%22:%5B65209.7890625%2C62706.3984375%2C3624.313232421875%5D%2C%22crossSectionScale%22:200.3368099747919%2C%22projectionScale%22:130046.7679766735%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://https://open-neurodata.s3.amazonaws.com/bock11/image%22%2C%22tab%22:%22source%22%2C%22name%22:%22bock11%22%7D%5D%2C%22selectedLayer%22:%7B%22layer%22:%22bock11%22%2C%22visible%22:true%7D%2C%22layout%22:%22xy%22%2C%22partialViewport%22:%5B0%2C0%2C1%2C1%5D%7D](url)

**Comment by Martiantian** [comment]
Sorry, our data is temporarily unavailable to the public.This page comes from public data above (https://neurodata.io/data/bock11/),and maybe illustrates the same thing.

[https://viz.neurodata.io/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-8%2C%22m%22%5D%7D%2C%22position%22:%5B65209.7890625%2C62706.3984375%2C3624.313232421875%5D%2C%22crossSectionScale%22:200.3368099747919%2C%22projectionScale%22:130046.7679766735%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://https://open-neurodata.s3.amazonaws.com/bock11/image%22%2C%22name%22:%22bock11%22%7D%5D%2C%22layout%22:%22xy%22%2C%22partialViewport%22:%5B0%2C0%2C1%2C1%5D%7D](url)

before transformation:  resolution among 4nm-4.1μm
![b1](https://user-images.githubusercontent.com/35797239/130711369-9c994e77-63b8-465e-a564-8c713703945f.png)
![b2](https://user-images.githubusercontent.com/35797239/130711379-be6f77a6-07a0-45aa-af16-28e2914c3437.png)

after transformation:  resolution among 4nm-40nm
![a1](https://user-images.githubusercontent.com/35797239/130711393-bb00b333-b246-4e6d-991c-751a5d937a29.png)
![a2](https://user-images.githubusercontent.com/35797239/130711399-8907c817-d3e5-4bf5-9304-52e52580ebc2.png)

**Comment by jbms** [comment]
Thanks, I have pushed a fix.
