### ISSUE TITLE
Skeleton file format

### ISSUE THREAD

**Issue by austinhoag** [google/neuroglancer#344]
I am trying to make a simple skeleton for a segmentation layer using the instructions here: https://github.com/google/neuroglancer/blob/8432f531c4d8eb421556ec36926a29d9064c2d3c/src/neuroglancer/datasource/precomputed/skeletons.md

I am aware of packages like Kimimaro, but I am first trying to understand how the files need to be laid out by going through a simple example manually. In my simple example, I am trying to make two vertices with a single edge between them. I have a single segment ID (59 in this example) for which I would like to add this skeleton. My python code to create the single skeleton data file is this:
```python
ID = 59 
vertex_positions = np.array([[157.,272.,228.],[170.,288.,228.]],dtype='<f4')
edges = np.array([[0,1]],dtype='<u4')
filename = f"/home/ahoag/ngdemo/demo_bucket/test_skeletons/allen_single_skeleton/skeletons/{ID}"
with open(filename,'wb') as outfile:
    buf = struct.pack('<II', vertex_positions.shape[0], edges.shape[0])
    buf += vertex_positions.tobytes()
    buf += edges.tobytes()
    outfile.write(buf)
```  
I also added an info file here: `/home/ahoag/ngdemo/demo_bucket/test_skeletons/allen_single_skeleton/skeletons/info` with contents:
```
{
	"@type": "neuroglancer_skeletons",
	"transform":[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
}
```
I added a key `"skeletons": "skeletons"` to the main info file for the segmentation layer `allen_single_skeleton`, which is the parent directory to `skeletons`. I can host this volume successfully with cloudvolume and even load the segmentation layer into Neuroglancer without any errors. However, when I select segment 59 I only see a single vertex show up (no edge) and it is at the origin, not either of the vertex_positions. Do you see an issue with how I am making the data file? I don't understand what the `transform` key is for in the info file. I guessed at what this should be (I have also tried all 1s). Maybe that is related to my issue here?

**Comment by jbms** [comment]
The transform key specifies an affine transform from the skeleton coordinate space to xyz nanometer space.

I tried running your code snippet to generate a skeleton file as you describe, and it seems to work fine.  Maybe you are just zoomed out too much to see the edge?

**Comment by austinhoag** [comment]
Got it, thanks!
