### ISSUE TITLE
Feature request: selecting segments by mouse dragging

### ISSUE THREAD

**Issue by tingzhao** [google/neuroglancer#356]
Selecting multiple segments under the path of mouse dragging could be very useful for us to explore some data, but it looks like the implementation will not be straightforward because segment IDs are picked asynchronously. @jbms Do you have any plan to add such a function? If not, any suggestions about how we can implement this by our own will be greatly appreciated.

**Comment by jbms** [comment]
I don't have an immediate plan to implement that functionality but I can see that it would be useful.

IDs are normally picked asynchronously but there is a mechanism to synchronously retrieve the id --- that is used for mouse click actions that require the id.  Also the asynchronous picking may be sufficient anyway as it still happens at a fairly rapid rate --- you could just add a handler to `SegmentSelectionState.changed`.

As for the UI, the simplest thing would be to add this as a "tool" that the user can bind to a shift+letter combination -- do you think that would serve your use case?

**Comment by tingzhao** [comment]
@jbms Thank you for the suggestions! Using the 'tool' binding is a good idea and I'll have a try.

**Comment by tingzhao** [comment]
BTW, since tool binding is user configurable, is there a way to keep a tool binding overwritten by the user? For example, if we set 'shift+A' for selecting bodies, the function will be gone after the user binds 'A' to another function and this can cause confusion.

**Comment by jbms** [comment]
At the moment there is not a way to "lock" tool binding, so that they cannot be changed in the UI, though potentially such a mechanism could be added.

Also note that tool bindings are always specific to a particular layer.

**Comment by tingzhao** [comment]
Tool binding seems work well. Thank you for the suggestions! I also created a pull request (https://github.com/google/neuroglancer/pull/362) in case you found it useful. You can ignore it if it doesn't fit in the current design or let me know any revise needed to make it acceptable.
