### ISSUE TITLE
"toggle-layout" not available for XZ, YZ views

### ISSUE THREAD

**Issue by stuarteberg** [google/neuroglancer#36]
(Feature request.)

The XY view can be maximized via the "toggle-layout" key (spacebar). But as far as I can tell, there's no way to do the same thing for the XZ and YZ views (even if I click inside one of those views before hitting the spacebar).  Providing "toggle-layout" for all three orthoviews would be a nice feature.

cc @alexwweston

**Comment by jbms** [comment]
Currently the toggle layout command is independent of the current selected panel.  Two thoughts:

First, there is a workaround: the "XY" view is actually relative to the current sliceview rotation.  Therefore, if you rotate the sliceview pose using shift arrow keys or shift left mouse drag, you can obtain an arbitrary view.  To get a proper axis-aligned XZ or YZ view, once you get it approximately right, you can press "z" to snap to an axis-aligned pose.

Clearly this workaround is not ideal, though.  Currently there is just a flat list of view layouts, and toggle-layouts just toggles between them.  Can you suggest how it might work better?  Just adding XZ and YZ views to the existing list would make the list of layouts so long that it would be inconvenient to have to cycle through them.

**Comment by stuarteberg** [comment]
I see what you mean.  One possibility is to have the maximized 2D view whichever view most recently had mouse focus.

Currently, the toggle-layout key switches between the following layouts:

- All 4 views
- 2D view (XY)

**Comment by stuarteberg** [comment]
I see what you mean. One possibility is to have the maximized 2D view whichever view most recently had mouse focus.

Currently, the toggle-layout key switches between the following layouts:

- All 4 views
- 2D (XY) view
- 3D+2D (XY) view

I'm proposing this instead:

- All 4 views
- 2D (most recently used) view
- 3D+2D (most recently used) view

**Comment by jbms** [comment]
This took a while because I wanted to get the input event handling refactored first, but this is now supported.

toggle-layout (space) has the effect of "maximizing" whichever panel has focus in the 4-panel or 2-panel layouts, or reverting to the 4panel layout from any single panel layout.
toggle-layout-alternative (shift+space) can be used to switch to the 2-panel (xy/xz/yz-3d) layout.
