### ISSUE TITLE
Neuroglancer segmentation files support - any internal format?

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [google/neuroglancer#364]
Dear all,

As far as I understand, neuroglancer supports several formats directly (e.g. precomputed format, zarr format etc.), and it **does not** convert them to some unified internal format used for the visualization. Is it correct?

Thank you,
Best regards,
Aliaksei

**Comment by jbms** [comment]
Yes that's correct.

**Comment by aliaksei-chareshneu** [comment]
Thanks! Related question: did I get it right that compressed_segmentation encoding cannot be used together with sharded format?

**Comment by jbms** [comment]
No, compressed_segmentation can be used with the precomputed sharded format, and frequently is used with that format.
