### ISSUE TITLE
Question Regarding Volume Rendering

### ISSUE THREAD

**Issue by davidackerman** [google/neuroglancer#385]
Hello,

I've enjoyed using the volume rendering function in neuroglancer and had a couple of questions. I am noticing that when I use the volume rendering, objects in background chunks can cause transparent "holes" to appear in the foreground objects, eg. [here](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B23408.80078125%2C3788.987060546875%2C23086.46484375%5D%2C%22crossSectionOrientation%22:%5B1%2C0%2C0%2C0%5D%2C%22crossSectionScale%22:250.140561391677%2C%22projectionOrientation%22:%5B-0.12988193333148956%2C0.9109659194946289%2C0.2629438638687134%2C-0.29005560278892517%5D%2C%22projectionScale%22:4393.383283931298%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22n5://s3://janelia-cosem-datasets/jrc_macrophage-2/jrc_macrophage-2.n5/labels/mito_pred%22%2C%22tab%22:%22rendering%22%2C%22shader%22:%22#uicontrol%20float%20brightness%20slider%28min=-10%2C%20max=10%2C%20default=0%2C%20step=0.1%29%5Cn#uicontrol%20float%20minValue%20slider%28min=0%2C%20max=255%2C%20default=0%2C%20step=1%29%5Cn#uicontrol%20float%20maxValue%20slider%28min=0%2C%20max=255%2C%20default=255%2C%20step=1%29%5Cn#uicontrol%20vec3%20color%20color%28default=%5C%22green%5C%22%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20float%20x%20=%20float%28getInterpolatedDataValue%28%29.value%29%3B%5Cn%20%20float%20val%20=%20%28x%20-%20minValue%29%20/%20%28maxValue%20-%20minValue%29%3B%5Cn%20%20float%20alpha%3B%5Cn%20%20if%20%28val%20%3C=%200.0%29%20alpha%20=%200.0%3B%5Cn%20%20else%20alpha%20=%20val%3B%5Cn%20%20emitRGBA%28vec4%28color%2C%20alpha%2Aexp%28brightness%29%29%29%3B%5Cn%7D%22%2C%22shaderControls%22:%7B%22color%22:%22#80000d%22%2C%22brightness%22:10%2C%22maxValue%22:128%2C%22minValue%22:127%7D%2C%22volumeRendering%22:true%2C%22name%22:%22mito_pred%22%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22size%22:590%2C%22visible%22:true%2C%22layer%22:%22mito_pred%22%7D%2C%22crossSectionBackgroundColor%22:%22#000000%22%2C%22layout%22:%223d%22%7D).

Similarly, if I just set everything to have alpha=1.0 with a high brightness, the same thing happens:
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/19193291/162887887-1c9d1240-24b2-497f-a12d-d5ec35199bd4.png">
Rather than a solid block, it appears as patched.

Is this the expected behavior or is there a way to prevent this? And what values can alpha have in `emitRGBA`? In the documentation it says [0,1] for pixel values, but it seems that based on brightness and alpha here it can be higher? And what scale level is it retrieving the data from, does it vary based on depth/zoom level, and is there a way to control it manually? Also, is the scale level the reason that things that are clear when zoomed in disappear when zoomed out, like [here](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B8e-9%2C%22m%22%5D%7D%2C%22position%22:%5B4086.528076171875%2C3125.428466796875%2C4095.438232421875%5D%2C%22crossSectionScale%22:0.8672644965275753%2C%22projectionOrientation%22:%5B-0.4582698941230774%2C0.14803244173526764%2C0.5434784889221191%2C0.687536358833313%5D%2C%22projectionScale%22:710.4604971149797%2C%22projectionDepth%22:-0.4240190079976629%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-public-data/flyem_fib-25/image%22%2C%22tab%22:%22source%22%2C%22name%22:%22image%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-public-data/flyem_fib-25/image%22%2C%22tab%22:%22rendering%22%2C%22opacity%22:1%2C%22shader%22:%22#uicontrol%20float%20brightness%20slider%28min=-10%2C%20max=10%2C%20default=0%2C%20step=0.1%29%5Cn#uicontrol%20float%20minValue%20slider%28min=0%2C%20max=255%2C%20default=0%2C%20step=1%29%5Cn#uicontrol%20float%20maxValue%20slider%28min=0%2C%20max=255%2C%20default=255%2C%20step=1%29%5Cn#uicontrol%20vec3%20color%20color%28default=%5C%22green%5C%22%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20float%20x%20=%20float%28getInterpolatedDataValue%28%29.value%29%3B%5Cn%20%20float%20val%20=%20%28x%20-%20minValue%29%20/%20%28maxValue%20-%20minValue%29%3B%5Cn%20%20float%20alpha%3B%5Cn%20%20if%20%28val%20%3C=%200.0%20%7C%7C%20val%20%3E=%201.0%29%20alpha%20=%200.0%3B%5Cn%20%20else%20alpha%20=%20val%3B%5Cn%20%20emitRGBA%28vec4%28color%2C%20alpha%2Aexp%28brightness%29%29%29%3B%5Cn%7D%5Cn%22%2C%22shaderControls%22:%7B%22brightness%22:3.6%2C%22minValue%22:90%2C%22maxValue%22:8%7D%2C%22volumeRendering%22:true%2C%22name%22:%22mito%22%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22size%22:502%2C%22visible%22:true%2C%22layer%22:%22mito%22%7D%2C%22layout%22:%7B%22type%22:%223d%22%2C%22orthographicProjection%22:true%7D%7D)?

Thanks!

**Comment by jbms** [comment]
Unfortunately the volume rendering is currently still rather experimental and has a number of issues as you have observed.  I don't know the cause of this issue --- but I suspect it may have something to do with the accumulation buffer becoming saturated.

For volume rendering there are no specific bounds on the range of alpha values.  In general I haven't figured out the best way to automatically normalize the overall brightness, which is why there is a need for a manual brightness control.

Currently volume rendering always uses 64 depth samples along the camera view direction, and chooses the data resolution so that the voxel size is approximately 1/64 the view frustrum depth.  (Currently only a single resolution is used at a time.)  The "Resolution (3d)" control does not currently have any effect, though it does show the current resolution of data in use.  You can affect which resolution is used by changing the depth of the view frustrum, using alt+mousewheel, but of course that will also have other effects.

**Comment by seankmartin** [comment]
Just in case it's helpful, it is now possible to change the resolution level for 3D data. E.g. [here](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B23408.80078125%2C3788.987060546875%2C23086.46484375%5D%2C%22crossSectionOrientation%22:%5B1%2C0%2C0%2C0%5D%2C%22crossSectionScale%22:250.140561391677%2C%22projectionOrientation%22:%5B-0.8115606904029846%2C0.4365316331386566%2C-0.11984161287546158%2C0.3693878650665283%5D%2C%22projectionScale%22:4393.383283931298%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22n5://s3://janelia-cosem-datasets/jrc_macrophage-2/jrc_macrophage-2.n5/labels/mito_pred%22%2C%22tab%22:%22rendering%22%2C%22shader%22:%22#uicontrol%20float%20brightness%20slider%28min=-10%2C%20max=10%2C%20default=0%2C%20step=0.1%29%5Cn#uicontrol%20float%20minValue%20slider%28min=0%2C%20max=255%2C%20default=0%2C%20step=1%29%5Cn#uicontrol%20float%20maxValue%20slider%28min=0%2C%20max=255%2C%20default=255%2C%20step=1%29%5Cn#uicontrol%20vec3%20color%20color%28default=%5C%22green%5C%22%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20float%20x%20=%20float%28getInterpolatedDataValue%28%29.value%29%3B%5Cn%20%20float%20val%20=%20%28x%20-%20minValue%29%20/%20%28maxValue%20-%20minValue%29%3B%5Cn%20%20float%20alpha%3B%5Cn%20%20if%20%28val%20%3C=%200.0%29%20alpha%20=%200.0%3B%5Cn%20%20else%20alpha%20=%20val%3B%5Cn%20%20emitRGBA%28vec4%28color%2C%20alpha%2Aexp%28brightness%29%29%29%3B%5Cn%7D%22%2C%22shaderControls%22:%7B%22brightness%22:10%2C%22minValue%22:127%2C%22maxValue%22:128%2C%22color%22:%22#80000d%22%7D%2C%22volumeRendering%22:%22on%22%2C%22volumeRenderingDepthSamples%22:1290.1591550923506%2C%22name%22:%22mito_pred%22%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22size%22:590%2C%22visible%22:true%2C%22layer%22:%22mito_pred%22%7D%2C%22crossSectionBackgroundColor%22:%22#000000%22%2C%22layout%22:%223d%22%7D) the resolution slider was changed to match from the level of the first data resolution from the original link in this issue.

The rendering algorithm was also changed, so the `alpha = 1.0` case should show a solid block as [here](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B17348.287109375%2C3161.3623046875%2C19202.8671875%5D%2C%22crossSectionOrientation%22:%5B1%2C0%2C0%2C0%5D%2C%22crossSectionScale%22:250.140561391677%2C%22projectionOrientation%22:%5B-0.8252109885215759%2C0.15674301981925964%2C-0.00035153431235812604%2C0.5426400899887085%5D%2C%22projectionScale%22:48429.03884653712%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22n5://s3://janelia-cosem-datasets/jrc_macrophage-2/jrc_macrophage-2.n5/labels/mito_pred%22%2C%22tab%22:%22rendering%22%2C%22shader%22:%22#uicontrol%20float%20brightness%20slider%28min=-10%2C%20max=10%2C%20default=0%2C%20step=0.1%29%5Cn#uicontrol%20float%20minValue%20slider%28min=0%2C%20max=255%2C%20default=0%2C%20step=1%29%5Cn#uicontrol%20float%20maxValue%20slider%28min=0%2C%20max=255%2C%20default=255%2C%20step=1%29%5Cn#uicontrol%20vec3%20color%20color%28default=%5C%22green%5C%22%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20float%20x%20=%20float%28getInterpolatedDataValue%28%29.value%29%3B%5Cn%20%20float%20val%20=%20%28x%20-%20minValue%29%20/%20%28maxValue%20-%20minValue%29%3B%5Cn%20%20float%20alpha%3B%5Cn%20%20if%20%28val%20%3C=%200.0%29%20alpha%20=%200.0%3B%5Cn%20%20else%20alpha%20=%20val%3B%5Cn%20%20alpha%20=%201.0%3B%5Cn%20%20emitRGBA%28vec4%28color%2C%20alpha%2Aexp%28brightness%29%29%29%3B%5Cn%7D%22%2C%22shaderControls%22:%7B%22brightness%22:10%2C%22minValue%22:127%2C%22maxValue%22:128%2C%22color%22:%22#80000d%22%7D%2C%22volumeRendering%22:%22on%22%2C%22volumeRenderingDepthSamples%22:1290.1591550923506%2C%22name%22:%22mito_pred%22%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22size%22:590%2C%22visible%22:true%2C%22layer%22:%22mito_pred%22%7D%2C%22crossSectionBackgroundColor%22:%22#000000%22%2C%22layout%22:%223d%22%7D).

**Comment by davidackerman** [comment]
This looks great, thanks!
