### ISSUE TITLE
Zarr chunk key ordering

### ISSUE THREAD

**Issue by normanrz** [google/neuroglancer#393]
I was trying to load [a Zarr dataset](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22d1%22:%5B1%2C%22%22%5D%2C%22d2%22:%5B1%2C%22%22%5D%2C%22d3%22:%5B1%2C%22%22%5D%7D%2C%22position%22:%5B2816.5%2C4256.5%2C1728.5%5D%2C%22crossSectionScale%22:1%2C%22projectionScale%22:16384%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr://https://static.webknossos.org/data/l4dense_motta_et_al_demo_zarr/color/1/%22%2C%22transform%22:%7B%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22d1%22:%5B1%2C%22%22%5D%2C%22d2%22:%5B1%2C%22%22%5D%2C%22d3%22:%5B1%2C%22%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%221%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%221%22%7D%2C%22layout%22:%224panel%22%7D) that happens to use "F" order. The dimensions are `c,x,y,z`. I noticed that Neuroglancer tries to load the chunks with reversed components in the chunk key, i.e. `{z}.{y}.{x}.{c}`. This is different from how zarr-python creates the data. See these Python and bash scripts:
```python
import zarr
import numpy as np

a = zarr.open_array("test_f.zarr", shape=(1,100,200,300), chunks=(1,50,50,50), order="F")
a[:,:,:,:] = np.arange(0,6000000).reshape((1,100,200,300))
```

```bash
tree test_f.zarr
test_f.zarr
├── 0.0.0.0
├── 0.0.0.1
├── 0.0.0.2
├── 0.0.0.3
├── 0.0.0.4
├── 0.0.0.5
├── 0.0.1.0
├── 0.0.1.1
├── 0.0.1.2
├── 0.0.1.3
├── 0.0.1.4
├── 0.0.1.5
├── 0.0.2.0
├── 0.0.2.1
├── 0.0.2.2
├── 0.0.2.3
├── 0.0.2.4
├── 0.0.2.5
├── 0.0.3.0
├── 0.0.3.1
├── 0.0.3.2
├── 0.0.3.3
├── 0.0.3.4
├── 0.0.3.5
├── 0.1.0.0
├── 0.1.0.1
├── 0.1.0.2
├── 0.1.0.3
├── 0.1.0.4
├── 0.1.0.5
├── 0.1.1.0
├── 0.1.1.1
├── 0.1.1.2
├── 0.1.1.3
├── 0.1.1.4
├── 0.1.1.5
├── 0.1.2.0
├── 0.1.2.1
├── 0.1.2.2
├── 0.1.2.3
├── 0.1.2.4
├── 0.1.2.5
├── 0.1.3.0
├── 0.1.3.1
├── 0.1.3.2
├── 0.1.3.3
├── 0.1.3.4
└── 0.1.3.5
```

**Comment by normanrz** [comment]
I opened a discussion about the correct chunk key component ordering in the zarr gitter channel: https://gitter.im/zarr-developers/community?at=628788657df86c141e9479c0

**Comment by jbms** [comment]
With the zarr v2 spec, the chunk keys should indeed be independent of the `order`.

**Comment by normanrz** [comment]
Wow. Thanks for the quick fix!
