### ISSUE TITLE
Callback Function on Neuroglancer State Change

### ISSUE THREAD

**Issue by unidesigner** [google/neuroglancer#400]
Where can I register/add a call back function in the Neuroglancer source code that gets called whenever any of the neuroglancer state changes (e.g. when changing the position etc.)? I would like to add a simple way to communicate with a parent window when Neuroglancer is embedded as an iframe, i.e. I would call something like `window.parent.postMessage('state_change', '*');` in the callback.

**Comment by jbms** [comment]
You can take a look at `src/neuroglancer/ui/default_viewer_setup.ts` and `src/neuroglancer/ui/url_hash_binding.ts`.

The `Viewer` class has a `state` member that has a `changed` member which is a `Signal`.  You can use `viewer.state.changed.add(callback)` to register `callback` to be invoked every time the state changes.

**Comment by unidesigner** [comment]
Thank you!
