### ISSUE TITLE
is there a way to adjust/set rendering options across layers? 

### ISSUE THREAD

**Issue by satra** [google/neuroglancer#402]
i'm rendering multiple layers in neuroglancer and would like to be able to adjust the rendering function parameters simultaneously across all the layers. is this possible? 

in the example below there are 10 layers corresponding to overlapped images. i can interactively adjust each layer individually, but it would be great if i could modify all layers simultaneously or even better for this use case set a single function for all layers.

Example link: [LEC+11](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22%3A%20%7B%22t%22%3A%20%5B1%2C%20%22s%22%5D%2C%20%22z%22%3A%20%5B2.285e-06%2C%20%22m%22%5D%2C%20%22y%22%3A%20%5B3.2309999999999996e-06%2C%20%22m%22%5D%2C%20%22x%22%3A%20%5B2.285e-06%2C%20%22m%22%5D%7D%2C%20%22displayDimensions%22%3A%20%5B%22z%22%2C%20%22y%22%2C%20%22x%22%5D%2C%20%22crossSectionScale%22%3A%2050%2C%20%22projectionScale%22%3A%20500000%2C%20%22layers%22%3A%20%5B%7B%22source%22%3A%20%22zarr%3A//https%3A//dandiarchive.s3.amazonaws.com/zarr/b7093b2e-d75a-4091-bf5a-482265873a3e/%22%2C%20%22type%22%3A%20%22image%22%2C%20%22shader%22%3A%20%22%5Cn%23uicontrol%20float%20brightness%20slider%28min%3D0.0%2C%20max%3D100.0%2C%20default%3D10.000000%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20float%20x%20%3D%20clamp%28toNormalized%28getDataValue%28%29%29%20%2A%20brightness%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20float%20angle%20%3D%202.0%20%2A%203.1415926%20%2A%20%284.0%20/%203.0%20%2B%20x%29%3B%5Cn%20%20%20%20float%20amp%20%3D%20x%20%2A%20%281.0%20-%20x%29%20/%202.0%3B%5Cn%20%20%20%20vec3%20result%3B%5Cn%20%20%20%20float%20cosangle%20%3D%20cos%28angle%29%3B%5Cn%20%20%20%20float%20sinangle%20%3D%20sin%28angle%29%3B%5Cn%20%20%20%20result.r%20%3D%20-0.14861%20%2A%20cosangle%20%2B%201.78277%20%2A%20sinangle%3B%5Cn%20%20%20%20result.g%20%3D%20-0.29227%20%2A%20cosangle%20%2B%20-0.90649%20%2A%20sinangle%3B%5Cn%20%20%20%20result.b%20%3D%201.97294%20%2A%20cosangle%3B%5Cn%20%20%20%20result%20%3D%20clamp%28x%20%2B%20amp%20%2A%20result%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20emitRGB%28result%29%3B%5Cn%7D%5Cn%22%2C%20%22name%22%3A%20%2259-01%22%7D%2C%20%7B%22source%22%3A%20%22zarr%3A//https%3A//dandiarchive.s3.amazonaws.com/zarr/1292c187-07da-4b11-82ed-f6eef52eca8d/%22%2C%20%22type%22%3A%20%22image%22%2C%20%22shader%22%3A%20%22%5Cn%23uicontrol%20float%20brightness%20slider%28min%3D0.0%2C%20max%3D100.0%2C%20default%3D10.000000%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20float%20x%20%3D%20clamp%28toNormalized%28getDataValue%28%29%29%20%2A%20brightness%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20float%20angle%20%3D%202.0%20%2A%203.1415926%20%2A%20%284.0%20/%203.0%20%2B%20x%29%3B%5Cn%20%20%20%20float%20amp%20%3D%20x%20%2A%20%281.0%20-%20x%29%20/%202.0%3B%5Cn%20%20%20%20vec3%20result%3B%5Cn%20%20%20%20float%20cosangle%20%3D%20cos%28angle%29%3B%5Cn%20%20%20%20float%20sinangle%20%3D%20sin%28angle%29%3B%5Cn%20%20%20%20result.r%20%3D%20-0.14861%20%2A%20cosangle%20%2B%201.78277%20%2A%20sinangle%3B%5Cn%20%20%20%20result.g%20%3D%20-0.29227%20%2A%20cosangle%20%2B%20-0.90649%20%2A%20sinangle%3B%5Cn%20%20%20%20result.b%20%3D%201.97294%20%2A%20cosangle%3B%5Cn%20%20%20%20result%20%3D%20clamp%28x%20%2B%20amp%20%2A%20result%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20emitRGB%28result%29%3B%5Cn%7D%5Cn%22%2C%20%22name%22%3A%20%2259-02%22%7D%2C%20%7B%22source%22%3A%20%22zarr%3A//https%3A//dandiarchive.s3.amazonaws.com/zarr/67bea8ee-d529-48f5-8da6-e11ad5838848/%22%2C%20%22type%22%3A%20%22image%22%2C%20%22shader%22%3A%20%22%5Cn%23uicontrol%20float%20brightness%20slider%28min%3D0.0%2C%20max%3D100.0%2C%20default%3D10.000000%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20float%20x%20%3D%20clamp%28toNormalized%28getDataValue%28%29%29%20%2A%20brightness%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20float%20angle%20%3D%202.0%20%2A%203.1415926%20%2A%20%284.0%20/%203.0%20%2B%20x%29%3B%5Cn%20%20%20%20float%20amp%20%3D%20x%20%2A%20%281.0%20-%20x%29%20/%202.0%3B%5Cn%20%20%20%20vec3%20result%3B%5Cn%20%20%20%20float%20cosangle%20%3D%20cos%28angle%29%3B%5Cn%20%20%20%20float%20sinangle%20%3D%20sin%28angle%29%3B%5Cn%20%20%20%20result.r%20%3D%20-0.14861%20%2A%20cosangle%20%2B%201.78277%20%2A%20sinangle%3B%5Cn%20%20%20%20result.g%20%3D%20-0.29227%20%2A%20cosangle%20%2B%20-0.90649%20%2A%20sinangle%3B%5Cn%20%20%20%20result.b%20%3D%201.97294%20%2A%20cosangle%3B%5Cn%20%20%20%20result%20%3D%20clamp%28x%20%2B%20amp%20%2A%20result%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20emitRGB%28result%29%3B%5Cn%7D%5Cn%22%2C%20%22name%22%3A%20%2259-03%22%7D%2C%20%7B%22source%22%3A%20%22zarr%3A//https%3A//dandiarchive.s3.amazonaws.com/zarr/68c395b7-77ad-4266-af1a-ee960108850b/%22%2C%20%22type%22%3A%20%22image%22%2C%20%22shader%22%3A%20%22%5Cn%23uicontrol%20float%20brightness%20slider%28min%3D0.0%2C%20max%3D100.0%2C%20default%3D10.000000%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20float%20x%20%3D%20clamp%28toNormalized%28getDataValue%28%29%29%20%2A%20brightness%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20float%20angle%20%3D%202.0%20%2A%203.1415926%20%2A%20%284.0%20/%203.0%20%2B%20x%29%3B%5Cn%20%20%20%20float%20amp%20%3D%20x%20%2A%20%281.0%20-%20x%29%20/%202.0%3B%5Cn%20%20%20%20vec3%20result%3B%5Cn%20%20%20%20float%20cosangle%20%3D%20cos%28angle%29%3B%5Cn%20%20%20%20float%20sinangle%20%3D%20sin%28angle%29%3B%5Cn%20%20%20%20result.r%20%3D%20-0.14861%20%2A%20cosangle%20%2B%201.78277%20%2A%20sinangle%3B%5Cn%20%20%20%20result.g%20%3D%20-0.29227%20%2A%20cosangle%20%2B%20-0.90649%20%2A%20sinangle%3B%5Cn%20%20%20%20result.b%20%3D%201.97294%20%2A%20cosangle%3B%5Cn%20%20%20%20result%20%3D%20clamp%28x%20%2B%20amp%20%2A%20result%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20emitRGB%28result%29%3B%5Cn%7D%5Cn%22%2C%20%22name%22%3A%20%2259-04%22%7D%2C%20%7B%22source%22%3A%20%22zarr%3A//https%3A//dandiarchive.s3.amazonaws.com/zarr/35d3b22b-b0c0-42c1-9cf7-45ebde5fe32b/%22%2C%20%22type%22%3A%20%22image%22%2C%20%22shader%22%3A%20%22%5Cn%23uicontrol%20float%20brightness%20slider%28min%3D0.0%2C%20max%3D100.0%2C%20default%3D10.000000%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20float%20x%20%3D%20clamp%28toNormalized%28getDataValue%28%29%29%20%2A%20brightness%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20float%20angle%20%3D%202.0%20%2A%203.1415926%20%2A%20%284.0%20/%203.0%20%2B%20x%29%3B%5Cn%20%20%20%20float%20amp%20%3D%20x%20%2A%20%281.0%20-%20x%29%20/%202.0%3B%5Cn%20%20%20%20vec3%20result%3B%5Cn%20%20%20%20float%20cosangle%20%3D%20cos%28angle%29%3B%5Cn%20%20%20%20float%20sinangle%20%3D%20sin%28angle%29%3B%5Cn%20%20%20%20result.r%20%3D%20-0.14861%20%2A%20cosangle%20%2B%201.78277%20%2A%20sinangle%3B%5Cn%20%20%20%20result.g%20%3D%20-0.29227%20%2A%20cosangle%20%2B%20-0.90649%20%2A%20sinangle%3B%5Cn%20%20%20%20result.b%20%3D%201.97294%20%2A%20cosangle%3B%5Cn%20%20%20%20result%20%3D%20clamp%28x%20%2B%20amp%20%2A%20result%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20emitRGB%28result%29%3B%5Cn%7D%5Cn%22%2C%20%22name%22%3A%20%2259-05%22%7D%2C%20%7B%22source%22%3A%20%22zarr%3A//https%3A//dandiarchive.s3.amazonaws.com/zarr/09eee020-2520-4758-a57b-00b9b8e93ffc/%22%2C%20%22type%22%3A%20%22image%22%2C%20%22shader%22%3A%20%22%5Cn%23uicontrol%20float%20brightness%20slider%28min%3D0.0%2C%20max%3D100.0%2C%20default%3D10.000000%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20float%20x%20%3D%20clamp%28toNormalized%28getDataValue%28%29%29%20%2A%20brightness%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20float%20angle%20%3D%202.0%20%2A%203.1415926%20%2A%20%284.0%20/%203.0%20%2B%20x%29%3B%5Cn%20%20%20%20float%20amp%20%3D%20x%20%2A%20%281.0%20-%20x%29%20/%202.0%3B%5Cn%20%20%20%20vec3%20result%3B%5Cn%20%20%20%20float%20cosangle%20%3D%20cos%28angle%29%3B%5Cn%20%20%20%20float%20sinangle%20%3D%20sin%28angle%29%3B%5Cn%20%20%20%20result.r%20%3D%20-0.14861%20%2A%20cosangle%20%2B%201.78277%20%2A%20sinangle%3B%5Cn%20%20%20%20result.g%20%3D%20-0.29227%20%2A%20cosangle%20%2B%20-0.90649%20%2A%20sinangle%3B%5Cn%20%20%20%20result.b%20%3D%201.97294%20%2A%20cosangle%3B%5Cn%20%20%20%20result%20%3D%20clamp%28x%20%2B%20amp%20%2A%20result%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20emitRGB%28result%29%3B%5Cn%7D%5Cn%22%2C%20%22name%22%3A%20%2259-06%22%7D%2C%20%7B%22source%22%3A%20%22zarr%3A//https%3A//dandiarchive.s3.amazonaws.com/zarr/5f7ff964-3aeb-4070-bd67-d70ecb58c084/%22%2C%20%22type%22%3A%20%22image%22%2C%20%22shader%22%3A%20%22%5Cn%23uicontrol%20float%20brightness%20slider%28min%3D0.0%2C%20max%3D100.0%2C%20default%3D10.000000%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20float%20x%20%3D%20clamp%28toNormalized%28getDataValue%28%29%29%20%2A%20brightness%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20float%20angle%20%3D%202.0%20%2A%203.1415926%20%2A%20%284.0%20/%203.0%20%2B%20x%29%3B%5Cn%20%20%20%20float%20amp%20%3D%20x%20%2A%20%281.0%20-%20x%29%20/%202.0%3B%5Cn%20%20%20%20vec3%20result%3B%5Cn%20%20%20%20float%20cosangle%20%3D%20cos%28angle%29%3B%5Cn%20%20%20%20float%20sinangle%20%3D%20sin%28angle%29%3B%5Cn%20%20%20%20result.r%20%3D%20-0.14861%20%2A%20cosangle%20%2B%201.78277%20%2A%20sinangle%3B%5Cn%20%20%20%20result.g%20%3D%20-0.29227%20%2A%20cosangle%20%2B%20-0.90649%20%2A%20sinangle%3B%5Cn%20%20%20%20result.b%20%3D%201.97294%20%2A%20cosangle%3B%5Cn%20%20%20%20result%20%3D%20clamp%28x%20%2B%20amp%20%2A%20result%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20emitRGB%28result%29%3B%5Cn%7D%5Cn%22%2C%20%22name%22%3A%20%2259-07%22%7D%2C%20%7B%22source%22%3A%20%22zarr%3A//https%3A//dandiarchive.s3.amazonaws.com/zarr/e29554e3-376e-4f26-bebb-b1d60dd61e59/%22%2C%20%22type%22%3A%20%22image%22%2C%20%22shader%22%3A%20%22%5Cn%23uicontrol%20float%20brightness%20slider%28min%3D0.0%2C%20max%3D100.0%2C%20default%3D10.000000%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20float%20x%20%3D%20clamp%28toNormalized%28getDataValue%28%29%29%20%2A%20brightness%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20float%20angle%20%3D%202.0%20%2A%203.1415926%20%2A%20%284.0%20/%203.0%20%2B%20x%29%3B%5Cn%20%20%20%20float%20amp%20%3D%20x%20%2A%20%281.0%20-%20x%29%20/%202.0%3B%5Cn%20%20%20%20vec3%20result%3B%5Cn%20%20%20%20float%20cosangle%20%3D%20cos%28angle%29%3B%5Cn%20%20%20%20float%20sinangle%20%3D%20sin%28angle%29%3B%5Cn%20%20%20%20result.r%20%3D%20-0.14861%20%2A%20cosangle%20%2B%201.78277%20%2A%20sinangle%3B%5Cn%20%20%20%20result.g%20%3D%20-0.29227%20%2A%20cosangle%20%2B%20-0.90649%20%2A%20sinangle%3B%5Cn%20%20%20%20result.b%20%3D%201.97294%20%2A%20cosangle%3B%5Cn%20%20%20%20result%20%3D%20clamp%28x%20%2B%20amp%20%2A%20result%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20emitRGB%28result%29%3B%5Cn%7D%5Cn%22%2C%20%22name%22%3A%20%2259-08%22%7D%2C%20%7B%22source%22%3A%20%22zarr%3A//https%3A//dandiarchive.s3.amazonaws.com/zarr/6f1de8ec-f879-4c32-9c17-4bd7b1d9812b/%22%2C%20%22type%22%3A%20%22image%22%2C%20%22shader%22%3A%20%22%5Cn%23uicontrol%20float%20brightness%20slider%28min%3D0.0%2C%20max%3D100.0%2C%20default%3D10.000000%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20float%20x%20%3D%20clamp%28toNormalized%28getDataValue%28%29%29%20%2A%20brightness%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20float%20angle%20%3D%202.0%20%2A%203.1415926%20%2A%20%284.0%20/%203.0%20%2B%20x%29%3B%5Cn%20%20%20%20float%20amp%20%3D%20x%20%2A%20%281.0%20-%20x%29%20/%202.0%3B%5Cn%20%20%20%20vec3%20result%3B%5Cn%20%20%20%20float%20cosangle%20%3D%20cos%28angle%29%3B%5Cn%20%20%20%20float%20sinangle%20%3D%20sin%28angle%29%3B%5Cn%20%20%20%20result.r%20%3D%20-0.14861%20%2A%20cosangle%20%2B%201.78277%20%2A%20sinangle%3B%5Cn%20%20%20%20result.g%20%3D%20-0.29227%20%2A%20cosangle%20%2B%20-0.90649%20%2A%20sinangle%3B%5Cn%20%20%20%20result.b%20%3D%201.97294%20%2A%20cosangle%3B%5Cn%20%20%20%20result%20%3D%20clamp%28x%20%2B%20amp%20%2A%20result%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20emitRGB%28result%29%3B%5Cn%7D%5Cn%22%2C%20%22name%22%3A%20%2259-09%22%7D%2C%20%7B%22source%22%3A%20%22zarr%3A//https%3A//dandiarchive.s3.amazonaws.com/zarr/dbee0a84-7850-49cb-b996-df0134042592/%22%2C%20%22type%22%3A%20%22image%22%2C%20%22shader%22%3A%20%22%5Cn%23uicontrol%20float%20brightness%20slider%28min%3D0.0%2C%20max%3D100.0%2C%20default%3D10.000000%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20float%20x%20%3D%20clamp%28toNormalized%28getDataValue%28%29%29%20%2A%20brightness%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20float%20angle%20%3D%202.0%20%2A%203.1415926%20%2A%20%284.0%20/%203.0%20%2B%20x%29%3B%5Cn%20%20%20%20float%20amp%20%3D%20x%20%2A%20%281.0%20-%20x%29%20/%202.0%3B%5Cn%20%20%20%20vec3%20result%3B%5Cn%20%20%20%20float%20cosangle%20%3D%20cos%28angle%29%3B%5Cn%20%20%20%20float%20sinangle%20%3D%20sin%28angle%29%3B%5Cn%20%20%20%20result.r%20%3D%20-0.14861%20%2A%20cosangle%20%2B%201.78277%20%2A%20sinangle%3B%5Cn%20%20%20%20result.g%20%3D%20-0.29227%20%2A%20cosangle%20%2B%20-0.90649%20%2A%20sinangle%3B%5Cn%20%20%20%20result.b%20%3D%201.97294%20%2A%20cosangle%3B%5Cn%20%20%20%20result%20%3D%20clamp%28x%20%2B%20amp%20%2A%20result%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20emitRGB%28result%29%3B%5Cn%7D%5Cn%22%2C%20%22name%22%3A%20%2259-10%22%7D%2C%20%7B%22source%22%3A%20%22zarr%3A//https%3A//dandiarchive.s3.amazonaws.com/zarr/7a62267c-c332-49c2-8742-cbeb8edb773b/%22%2C%20%22type%22%3A%20%22image%22%2C%20%22shader%22%3A%20%22%5Cn%23uicontrol%20float%20brightness%20slider%28min%3D0.0%2C%20max%3D100.0%2C%20default%3D10.000000%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20float%20x%20%3D%20clamp%28toNormalized%28getDataValue%28%29%29%20%2A%20brightness%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20float%20angle%20%3D%202.0%20%2A%203.1415926%20%2A%20%284.0%20/%203.0%20%2B%20x%29%3B%5Cn%20%20%20%20float%20amp%20%3D%20x%20%2A%20%281.0%20-%20x%29%20/%202.0%3B%5Cn%20%20%20%20vec3%20result%3B%5Cn%20%20%20%20float%20cosangle%20%3D%20cos%28angle%29%3B%5Cn%20%20%20%20float%20sinangle%20%3D%20sin%28angle%29%3B%5Cn%20%20%20%20result.r%20%3D%20-0.14861%20%2A%20cosangle%20%2B%201.78277%20%2A%20sinangle%3B%5Cn%20%20%20%20result.g%20%3D%20-0.29227%20%2A%20cosangle%20%2B%20-0.90649%20%2A%20sinangle%3B%5Cn%20%20%20%20result.b%20%3D%201.97294%20%2A%20cosangle%3B%5Cn%20%20%20%20result%20%3D%20clamp%28x%20%2B%20amp%20%2A%20result%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20emitRGB%28result%29%3B%5Cn%7D%5Cn%22%2C%20%22name%22%3A%20%2259-11%22%7D%5D%2C%20%22showDefaultAnnotations%22%3A%20false%2C%20%22layout%22%3A%20%22yz%22%7D)

**Comment by jbms** [comment]
For your particular use case, you can instead just add multiple data sources to a single layer, using the "+" button at the bottom of the "Source" tab.

[Example link](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22t%22:%5B1%2C%22s%22%5D%2C%22z%22:%5B0.000002285%2C%22m%22%5D%2C%22y%22:%5B0.0000032309999999999996%2C%22m%22%5D%2C%22x%22:%5B0.000002285%2C%22m%22%5D%7D%2C%22displayDimensions%22:%5B%22z%22%2C%22y%22%2C%22x%22%5D%2C%22position%22:%5B0.5%2C52700.5%2C12641.2021484375%2C25790.212890625%5D%2C%22crossSectionScale%22:33.59989713237945%2C%22projectionScale%22:500000%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%5B%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/b7093b2e-d75a-4091-bf5a-482265873a3e/%22%2C%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/1292c187-07da-4b11-82ed-f6eef52eca8d/%22%2C%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/67bea8ee-d529-48f5-8da6-e11ad5838848/%22%2C%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/68c395b7-77ad-4266-af1a-ee960108850b/%22%2C%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/35d3b22b-b0c0-42c1-9cf7-45ebde5fe32b/%22%2C%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/09eee020-2520-4758-a57b-00b9b8e93ffc/%22%2C%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/5f7ff964-3aeb-4070-bd67-d70ecb58c084/%22%2C%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/e29554e3-376e-4f26-bebb-b1d60dd61e59/%22%2C%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/6f1de8ec-f879-4c32-9c17-4bd7b1d9812b/%22%2C%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/dbee0a84-7850-49cb-b996-df0134042592/%22%2C%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/7a62267c-c332-49c2-8742-cbeb8edb773b/%22%5D%2C%22localDimensions%22:%7B%22c%27%22:%5B1%2C%22%22%5D%7D%2C%22localPosition%22:%5B0.5%5D%2C%22tab%22:%22rendering%22%2C%22shader%22:%22%5Cn#uicontrol%20float%20brightness%20slider%28min=0.0%2C%20max=100.0%2C%20default=10.000000%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20float%20x%20=%20clamp%28toNormalized%28getDataValue%28%29%29%20%2A%20brightness%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20float%20angle%20=%202.0%20%2A%203.1415926%20%2A%20%284.0%20/%203.0%20+%20x%29%3B%5Cn%20%20%20%20float%20amp%20=%20x%20%2A%20%281.0%20-%20x%29%20/%202.0%3B%5Cn%20%20%20%20vec3%20result%3B%5Cn%20%20%20%20float%20cosangle%20=%20cos%28angle%29%3B%5Cn%20%20%20%20float%20sinangle%20=%20sin%28angle%29%3B%5Cn%20%20%20%20result.r%20=%20-0.14861%20%2A%20cosangle%20+%201.78277%20%2A%20sinangle%3B%5Cn%20%20%20%20result.g%20=%20-0.29227%20%2A%20cosangle%20+%20-0.90649%20%2A%20sinangle%3B%5Cn%20%20%20%20result.b%20=%201.97294%20%2A%20cosangle%3B%5Cn%20%20%20%20result%20=%20clamp%28x%20+%20amp%20%2A%20result%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20emitRGB%28result%29%3B%5Cn%7D%5Cn%22%2C%22shaderControls%22:%7B%22brightness%22:15%7D%2C%22name%22:%2259-01%22%7D%5D%2C%22showDefaultAnnotations%22:false%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%2259-01%22%7D%2C%22layout%22:%22yz%22%7D)

More generally, though, the feature you are requesting would certainly be useful --- it just isn't supported yet.

**Comment by satra** [comment]
thanks jeremy. that solves my current problem.
