### ISSUE TITLE
Create Docker Image

### ISSUE THREAD

**Issue by SRoche14** [google/neuroglancer#403]
I would like to create a docker image of this repository to use in a machine learning project, but I am struggling to figure out how to create the proper Dockerfile. I tried forking the repo and created a Dockerfile, but I am unsure what base image to use, what environment variables need to be set up, and what additional dependencies should be included. Does anyone have guidance on how to accomplish this? 

Thanks!

**Comment by jbms** [comment]
What do you want the docker image to do?

**Comment by SRoche14** [comment]
It would allow neuroglancer version 2.23 to be run in a docker container. We have .tiff files that can be viewed with neuroglancer, but we need to create a docker container that can run neuroglancer. This is because it would make using neuroglancer much easier across different environments on various computers in our lab.

**Comment by jbms** [comment]
There is this example from a few years ago:

https://github.com/4QuantOSS/neuroglancer-docker
However you will need to use Python 3 instead.  Still it may be helpful as a reference.

**Comment by SRoche14** [comment]
Yes, that works! I made some modifications to update old dependencies, including: updating to python3, importing npm and nodejs, upgrading to `debian:bullseye` from `debian:jessie`, and using an outdated miniconda installer. For future readers, the Dockerfile I used is here:
`FROM debian:bullseye
LABEL author="Steven Roche"
ENV DEBIAN_FRONTEND noninteractive
ENV CONDA_DIR /opt/conda

# Core installs
RUN apt-get update && \
    apt-get upgrade && \
    apt-get install -y git vim wget build-essential python3 ca-certificates bzip2 libsm6 npm nodejs && \
    apt-get clean

RUN npm install -g npm@latest

RUN mkdir -p ~/miniconda3

# Install miniconda 
RUN echo 'export PATH=$CONDA_DIR/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh && \
    /bin/bash ~/miniconda3/miniconda.sh -b -p $CONDA_DIR && \
    rm -rf ~/miniconda3/miniconda3.sh && \
    $CONDA_DIR/bin/conda install --yes conda


# Create a user
RUN useradd -m -s /bin/bash neuroglancer_user
RUN chown -R neuroglancer_user:neuroglancer_user $CONDA_DIR

# Env vars
USER neuroglancer_user
ENV HOME /home/neuroglancer_user
ENV SHELL /bin/bash
ENV USER neuroglancer_user
ENV PATH $CONDA_DIR/bin:$PATH
WORKDIR $HOME

# setup the rest of the packages
RUN conda install --yes nose numpy pandas matplotlib scipy seaborn numba bokeh pillow ipython
# Install Jupyter notebook to allow for more interactive neuroglancing
RUN conda install --yes -c conda-forge notebook \
    && conda clean -a

# install neuroglancer from github
RUN git clone https://github.com/google/neuroglancer.git
WORKDIR neuroglancer
RUN ls 
RUN python3 setup.py install

ADD docker_demo.py $HOME/docker_demo.py
ADD notebooks $HOME/notebooks
ADD test_data $HOME/test_data
USER root
RUN chown -R neuroglancer_user:neuroglancer_user $HOME/notebooks
RUN chown -R neuroglancer_user:neuroglancer_user $HOME/docker_demo.py

# Open ports for the notebook and the server
EXPOSE 8888
EXPOSE 8989

# run the notebook as a user
USER neuroglancer_user
WORKDIR $HOME
CMD jupyter notebook --ip='0.0.0.0'`
