### ISSUE TITLE
BUG: Sensitive Data exposed on following file "neuroglancer/python/neuroglancer/default_credentials_manager.py"

### ISSUE THREAD

**Issue by aravindb26** [google/neuroglancer#416]
Hi team, hope you all doing well.

I have found a BUG in the following file ```neuroglancer/python/neuroglancer/default_credentials_manager.py```

**Below sensitive credentials were Publicly exposed**
```client_id=u'639403125587-ue3c18dalqidqehs1n1p5rjvgni5f7qu.apps.googleusercontent.com', client_secret=u'kuaqECaVXOKEJ2L6ifZu4Aqt'```

**Impact**
These credentials access a user's Google Ads account without having to handle or store the user's login info.

Reference: https://developers.google.com/adwords/api/docs/guides/authentication

```Client id and client secret are similar to a login and password. They give your application the ability to request the consent of a user to access their data```

It's better to remove the sensitive information ASAP to save it from hackers.

**Comment by jbms** [comment]
These oauth credentials are intentionally made public.  They are not adwords-related.  There is no security vulnerability as far as I am aware.

**Comment by aravindb26** [comment]
> These oauth credentials are intentionally made public. They are not adwords-related. There is no security vulnerability as far as I am aware.

But they are sensitive data and they are verified too, I mean still those credentials can be used. I don't know but hacker might use those in any situations when he needs because they are still working credentials.

**Comment by aravindb26** [comment]
> Every client-side application (including Google Chrome, mobile apps, etc.) that makes requests to Google APIs requires oauth2 client credentials. These are necessarily distributed to users with the client. Sometimes they are obfuscated, but they can still be extracted. For server-side applications it is possible to keep these oauth2 client credentials a secret, but for client-side applications it is not (and therefore they serve no security purpose).
> 
> The only alternative is to require every user of the application to create their own Google Cloud Project and generate their own oauth2 client credentials. This is unfortunately not very practical because creating new oauth2 client credentials cannot be easily automated, and therefore would require manually clicking through stuff on the Google Cloud console.

Auth credentials were like user ID and password. So, it's easy for an attacker to use it on his work purpose. We can't say he might do it automate it because now a days we have tools like turboindruder which checks and sends attacks in request. It's very simple to match the cases. Attacker might be clever than me.

So it has High impact

**Comment by jbms** [comment]
This developer documentation notes:

https://developers.google.com/identity/protocols/oauth2#installed

> The process results in a client ID and, in some cases, a client secret, which you embed in the source code of your application. (In this context, the client secret is obviously not treated as a secret.)
