### ISSUE TITLE
Unable to read data from S3 buckets outside of us-east-1

### ISSUE THREAD

**Issue by danielsf** [google/neuroglancer#418]
I have recently started experimenting with neuroglancer and discovered that I was unable to access data stored in S3 buckets that were not in us-east-1. Based on this line of code

https://github.com/google/neuroglancer/blob/master/src/neuroglancer/util/s3.ts#L41

I believe it is because neuroglancer was not updated to reflect the new URL conventions for S3 buckets outlined, for instance, here

https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

As a test, I have created two buckets. sfd-western-bucket is in us-west-2. sfd-eastern-bucket is in us-east-1. Neuroglancer can see data in sfd-eastern-bucket, but cannot see the data in sfd-western-bucket (the public access permissions and policies are identical between the two buckets).

If I point a generic browser at
https://s3.amazonaws.com/sfd-eastern-bucket?location
as per this line of code
https://github.com/google/neuroglancer/blob/master/src/neuroglancer/util/s3.ts#L35
I see

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"/>
```

If I point a generic browser at
https://s3.amazonaws.com/sfd-western-bucket
I see
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>PermanentRedirect</Code>
<Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message>
<Endpoint>sfd-western-bucket.s3.amazonaws.com</Endpoint>
<Bucket>sfd-western-bucket</Bucket>
<RequestId>SHMFASWB566R4QKM</RequestId>
<HostId>Mus4YovqGjmyl3QN2GFd0hma0LvvhVAfzPDM8NPva4VsbB8FUQs5d+6R2qPgEQbh7riL5GcqQlk=</HostId>
</Error>
```

If I point a generic browser at
https://sfd-western-bucket.s3.amazonaws.com/
I see
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Name>sfd-western-bucket</Name>
<Prefix/>
<Marker/>
<MaxKeys>1000</MaxKeys>
<IsTruncated>false</IsTruncated>
<Contents>
<Key>eg.nii.gz</Key>
<LastModified>2022-10-07T15:54:49.000Z</LastModified>
<ETag>"403c4abf3e43593f9c5b6770ff28e043-5"</ETag>
<Size>84621542</Size>
<Owner>
<ID>74b3413801d80142ce0a6dbc53ce1c318e2161c8f37a1872700ebc4f1ec659c6</ID>
<DisplayName>AWSAdminMultimodalIntegrationQueryPrototyping</DisplayName>
</Owner>
<StorageClass>STANDARD</StorageClass>
</Contents>
</ListBucketResult>
```

Unfortunately
https://sfd-western-bucket.s3.amazonaws.com/?location
still results in an error message.

I'm not sure if the error I am seeing (inability to load data from us-west-2) is because the `?location` query for us-west-2 fails or if it is because all of the `?location` queries in `s3.ts` now fail and the default assumption is that data lives in us-east-1. I will continue to dig as I have time, but I just wanted to point out that this is an issue.

**Comment by jbms** [comment]
Thanks for bringing this to my attention.  It appears that the additional logic to determine the location is unnecessary and was not working, so I have removed it per your suggestion, and I can now successfully access both of your buckets.
