### ISSUE TITLE
setup.py Bug

### ISSUE THREAD

**Issue by Mencu** [google/neuroglancer#420]
Hi, 

I've noticed a possible bug in the latest setup.py [commit](https://github.com/google/neuroglancer/commit/1f4c8a77333acddf2a2469df7968aea056eb4f9c). There is no python package `typying_exceptions` , only `typing_extensions` that uses Literal. 
When trying to freshly install the latest neuroglancer, pip throws an error about this. 

Cheers,
Andrei

**Comment by jbms** [comment]
Thanks for bringing this to my attention!
