### ISSUE TITLE
CORS error while loading N5s via Python Interface

### ISSUE THREAD

**Issue by davidackerman** [google/neuroglancer#423]
Hello,

When I run examples like the code below, `precomputed` datasets including meshes load fine, but any time I use `n5` I get a CORS errors. Is this the expected behavior. If not, how can I fix it? Thanks!

```python
from __future__ import print_function

import argparse

import neuroglancer
import neuroglancer.cli
import time

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    neuroglancer.cli.add_server_arguments(ap)
    args = ap.parse_args()
    neuroglancer.cli.handle_server_arguments(args)
    viewer = neuroglancer.Viewer()
    with viewer.txn() as s:
        s.layers["image"] = neuroglancer.ImageLayer(
            source="precomputed://gs://neuroglancer-public-data/flyem_fib-25/image"
        )
        s.layers["image2"] = neuroglancer.ImageLayer(
            source="n5://s3://janelia-cosem-datasets/jrc_mus-liver/jrc_mus-liver.n5/em/fibsem-uint8"
        )
    print(viewer)
    time.sleep(1000)
```
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/19193291/197592762-955ea7f9-b689-4527-b164-438988a0a429.png">

**Comment by jbms** [comment]
I'm a bit confused --- your example works for me, both via Python and just using the normal web client:

https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B8e-9%2C%22m%22%5D%7D%2C%22position%22:%5B6373.5%2C6364.5%2C4466.5%5D%2C%22crossSectionScale%22:1%2C%22projectionScale%22:16384%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22n5://s3://janelia-cosem-datasets/jrc_mus-liver/jrc_mus-liver.n5/em/fibsem-uint8%22%2C%22tab%22:%22source%22%2C%22name%22:%22fibsem-uint8%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22fibsem-uint8%22%7D%2C%22layout%22:%224panel%22%7D

**Comment by davidackerman** [comment]
Hm I still cannot get it to work via the python-initiated neuroglancer viewer, it still gives a CORS error, but only for the n5. 

I was/can still get it to work via the normal web client. But any time I try to load an n5 using the python-initiated viewer, I get CORS errors. Could it be something about how my machine is set up?

**Comment by jbms** [comment]
You can check Chrome/Firefox developer tools network tab for the failed request to get more information about it.

**Comment by davidackerman** [comment]
If it helps, these are the error messages:
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/19193291/197599903-375d6a06-a52a-4714-9928-bca0b4dc771e.png">

**Comment by jbms** [comment]
The problem is just that you need to upgrade the neuroglancer Python package to a newer version that supports s3

**Comment by davidackerman** [comment]
Yup that did it, thanks! Sorry about the mixup.
