### ISSUE TITLE
Cannot load zarr data from S3 buckets outside of us-east-1

### ISSUE THREAD

**Issue by danielsf** [google/neuroglancer#424]
I suspect this is related to #418. I cannot read zarr data from S3 buckets that are not in us-east-1. I have created two identical buckets: mouse1-small-celltypes, which is in us-west-2 and mouse1-small-celltypes-east, which is in us-east-1. I can visualize data in the bucket in us-east-1, but the bucket in us-west-2 fails with the message `Neither .zarray metadata nor OME multiscale metadata found` in the render panel. Here are URLs pointing to the two visualizations. The data contained in the two buckets should be identical

mouse1-small-celltypes-east URL

https://neuroglancer-demo.appspot.com/#!%7B%22layers%22:%20%5B%7B%22type%22:%20%22image%22%2C%20%22source%22:%20%22zarr://s3://mouse1-small-celltypes-east/classes/NN%22%2C%20%22name%22:%20%22classes/NN%20%28green%29%22%2C%20%22blend%22:%20%22default%22%2C%20%22shader%22:%20%22#uicontrol%20invlerp%20normalized%28range=%5B0%2C%200.1%5D%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20%20%20if%28getDataValue%280%29%3E0.0%29%7B%5Cn%20%20%20%20%20%20%20%20emitRGB%28normalized%28%29%2Avec3%280%2C%201%2C%200%29%29%3B%5Cn%7D%20%20%20%20else%7B%5CnemitRGB%28vec3%280%2C%200%2C%200%29%29%3B%7D%5Cn%7D%22%2C%20%22opacity%22:%201.0%2C%20%22visible%22:%20true%7D%5D%2C%20%22SelectedLayer%22:%20%7B%22visible%22:%20true%2C%20%22layer%22:%20%22new%20layer%22%7D%2C%20%22layout%22:%20%224panel%22%7D

mouse1-small-celltypes URL

https://neuroglancer-demo.appspot.com/#!%7B%22layers%22:%20%5B%7B%22type%22:%20%22image%22%2C%20%22source%22:%20%22zarr://s3://mouse1-small-celltypes/classes/NN%22%2C%20%22name%22:%20%22classes/NN%20%28green%29%22%2C%20%22blend%22:%20%22default%22%2C%20%22shader%22:%20%22#uicontrol%20invlerp%20normalized%28range=%5B0%2C%200.1%5D%29%5Cnvoid%20main%28%29%20%7B%5Cn%20%20%20%20%20%20if%28getDataValue%280%29%3E0.0%29%7B%5Cn%20%20%20%20%20%20%20%20emitRGB%28normalized%28%29%2Avec3%280%2C%201%2C%200%29%29%3B%5Cn%7D%20%20%20%20else%7B%5CnemitRGB%28vec3%280%2C%200%2C%200%29%29%3B%7D%5Cn%7D%22%2C%20%22opacity%22:%201.0%2C%20%22visible%22:%20true%7D%5D%2C%20%22SelectedLayer%22:%20%7B%22visible%22:%20true%2C%20%22layer%22:%20%22new%20layer%22%7D%2C%20%22layout%22:%20%224panel%22%7D

**Comment by jbms** [comment]
Both of these links work for me, both in Chrome and Firefox.

**Comment by danielsf** [comment]
They both work for me now, as well. All I can do is swear on my old Boy Scout handbook that the one wasn't working when I filed this ticket. Sorry for the noise.
