### ISSUE TITLE
Using both zarr and ome-zarr layers

### ISSUE THREAD

**Issue by tathey1** [google/neuroglancer#428]
I am starting to use zarr and ome-zarr with neuroglancer (so cool!) and I have gotten each to work on their own. However, I noticed that when I load an image layer from zarr data, then try to add an image layer from ome-zarr data, the ome-zarr layer does not show anything. The same happens when I reverse the order - I can load an image layer from ome-zarr data, however subsequent layers using zarr data will not show up.

I am using the appspot neuroglancer and all my data is locally served using cors_webserver.py

This is not a problem for me in my work, just an observation I thought I'd share. I'm happy to provide more information on how to replicate or do some code sleuthing, if that'd be useful. 

Thanks for this awesome package.

**Comment by jbms** [comment]
Can you provide a more precise example?  The issue may be that the default dimension names of one volume differ from the default dimension names of the other.

**Comment by tathey1** [comment]
Sure thing, here's some code that writes the data:

```
import numpy as np
import zarr
from ome_zarr.io import parse_url
from ome_zarr.writer import write_image

# Modify base_dir below
base_dir = "/Users/thomasathey/Documents/jovolab/neurodata_infrastructure_tips/ng-zarr-test/" #<path-to-ng-zarr-data>

# Image is cube of zeros with cube of 1's in the middle
data = np.zeros((100, 100, 100))
data[40:60,40:60,40:60] = 1
data = data.astype('uint64')

# Write zarr
z = zarr.open(base_dir + 'test.zarr', mode='w', shape=data.shape, chunks=data.shape, dtype='uint64')
z[:,:,:] = data

# Write ome-zarr
path = base_dir + "test-ome.zarr"
store = parse_url(path, mode="w").store
root = zarr.group(store=store)
write_image(image=data, group=root, axes="zyx", storage_options=dict(chunks=data.shape))
```

Then:

### In neuroglancer directory:

python cors_webserver.py -d "<base_dir>" -p 9010

### Add zarr data image layer:
zarr://http://127.0.0.1:9010/test.zarr/

### Add ome-zarr data image layer:
zarr://http://127.0.0.1:9010/test-ome.zarr/


I can add an image layer from the zarr data:

<img width="2560" alt="zarr" src="https://user-images.githubusercontent.com/18537350/203397689-e4e59ebb-49b6-4a6b-a5bc-ed685c00273f.png">

But adding the ome-zarr data will not show up:

<img width="2560" alt="no-ome" src="https://user-images.githubusercontent.com/18537350/203397709-cb55db26-8f04-47d9-9605-08558910e046.png">

If I add the image layers in the other order, the converse happens (ome will show up, but. normal zarr will not).

**Comment by jbms** [comment]
The issue here is that the zarr volume does not have dimension names so neuroglancer assigns default names of d0, d1, d2.  Then you end up with a 6 dimensional space, x y z d0 d1 d2.  To display them together in a common 3d coordinate space, use the source tab of the zarr layer to change the source dimension scales/units and the output dimension names.

**Comment by tathey1** [comment]
Oh, I see! I did not notice that. Thanks, I understand how to make them both display now.
