### ISSUE TITLE
Decoding a shard filename to XYZ extents

### ISSUE THREAD

**Issue by dxenes1** [google/neuroglancer#432]
Hi, 

I am interested in decoding a shard filename to its chunk index for analytics and usage statistics on our precompute image data. I am sure the process (shard -> X,Y,Z extents) is possible but I'm having difficulty implementing it in Python. From what I understand the image shards are encoded using a compressed Morton code but where I'm struggling is reversing the steps once you  calculate the Morton code for a particular chunk bounding box as shown in the cloud-volume function here:

https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/datasource/precomputed/sharding.py#L141

Not really sure what shard mask and mini-shard mask are doing here so I'm specifically struggling with reversing the application of those masks to the hashed (identity) chunk ID. Please let me know if there is any existing implementation or if you have any tips!

**Comment by jbms** [comment]
You can refer to this code in tensorstore:


https://github.com/google/tensorstore/blob/1a02a91f56e4efd8dd9f04e83cda33da258cd106/tensorstore/driver/neuroglancer_precomputed/metadata.h#L359
https://github.com/google/tensorstore/blob/1a02a91f56e4efd8dd9f04e83cda33da258cd106/tensorstore/driver/neuroglancer_precomputed/metadata.cc#L1387

If you also log the byte ranges you could figure out more precisely which regions are requested.

**Comment by dxenes1** [comment]
Thank you Jeremy! This is exactly what I was looking for.
