### ISSUE TITLE
Opacity 0.99 appears less opaque than expected

### ISSUE THREAD

**Issue by stuarteberg** [google/neuroglancer#441]
I don't have much knowledge of 3D rendering implementations, so this might be a dumb question.  If I set an object's 3D opacity to 0.99, I'd expect it to appear almost fully opaque.  But instead, it looks much more transparent -- almost the same as opacity 0.5.

Here are some test links to conveniently compare different opacity settings:

- [many objects][1]
- [just one object][2]

Is that to be expected?

Here are some example screenshots, for comparison:

<details><summary>Opacity 1.0 screenshot</summary>

<img width="920" alt="image" src="https://user-images.githubusercontent.com/1655821/219975518-72719663-100e-4095-b47c-4cbdf506f1e8.png">

</details>

<details><summary>Opacity 0.99 screenshot</summary>

<img width="955" alt="image" src="https://user-images.githubusercontent.com/1655821/219975530-75d71aa9-d3e6-4205-8d60-19ee5d25e948.png">

</details>

<details><summary>Opacity 0.5 screenshot</summary>

<img width="940" alt="image" src="https://user-images.githubusercontent.com/1655821/219975547-06a0b4e2-1781-400e-a1c0-064ede31d620.png">

</details>

Is that the expected appearance in each case?  To me, it looks like the opacity appears as I would expect only for surfaces which don't occlude other objects.

In addition to the 3D opacity setting, there's also a similar issue with the 3D silhouette setting (i.e. silhouette 0.001 looks very different from silhouette 0.0).

[1]: https://neuroglancer-demo.appspot.com/#!gs://flyem-user-links/short/many-objects-opacity-demo.json

[2]: https://neuroglancer-demo.appspot.com/#!gs://flyem-user-links/short/single-object-opacity-demo.json

**Comment by jbms** [comment]
Neuroglancer uses an approximate transparency rendering method because I don't know how to implement true transparency in an efficient way, especially with the limitations of WebGL.  Unfortunately that does mean that 0.99 opacity is very different from 1.0 opacity.

**Comment by stuarteberg** [comment]
Gotcha.  Thanks for the answer.  Since it's not a bug per se, I'll go ahead and close this.
