### ISSUE TITLE
Problem opening JSON files from Python API

### ISSUE THREAD

**Issue by JoOkuma** [google/neuroglancer#448]
Hi,

I'm having issues opening the data with the Python API. Is there anything I'm doing wrong, or is it a bug?

```python3
import argparse
import webbrowser
import requests
import json

import neuroglancer as ng


if __name__ == "__main__":

    json_url = "https://public.czbiohub.org/royerlab/zebrahub/imaging/single-objective/ZSNS001.json"
    json_data = json.loads(requests.get(json_url).text)

    viewer = ng.Viewer()

    with viewer.txn() as s:
        # DOESNT WORK
        s.layers["image"] = ng.ImageLayer(json_data=json_data)

        # WORKS
        # s.layers["image"] = ng.ImageLayer(source="zarr://https://public.czbiohub.org/royerlab/zebrahub/imaging/single-objective/ZSNS001.ome.zarr")

    print(viewer.state)
    webbrowser.open_new(viewer.get_viewer_url())
```

The JSON doesn't work with the script above, the viewer is just blank.
However, when I print the `viewer.state` everything looks fine -- everything is there.

I noticed that the "layer" "source" state are different between the executions:
- zarr: `"source": [{"url": "zarr://https://public.czbiohub.org/royerlab/zebrahub/imaging/single-objective/ZSNS001.ome.zarr"}`
- json: `"source": "zarr://https://public.czbiohub.org/royerlab/zebrahub/imaging/single-objective/ZSNS001.ome.zarr"`

But even after converting the json "source" to the "zarr" style, it didn't work

Thanks

**Comment by jbms** [comment]
> * zarr: `"source": [{"url": "zarr://https://public.czbiohub.org/royerlab/zebrahub/imaging/single-objective/ZSNS001.ome.zarr"}`
> * json: `"source": "zarr://https://public.czbiohub.org/royerlab/zebrahub/imaging/single-objective/ZSNS001_tail.ome.zarr"`

These are equivalent.

What you have in https://public.czbiohub.org/royerlab/zebrahub/imaging/single-objective/ZSNS001_tail.json is a full neuroglancer ViewerState json representation, not the json representation of a single layer. 

You can instead do:

```
viewer.set_state(json_data)
```

**Comment by jbms** [comment]
The wrapper types like `ImageLayer` allow you to set the json representation directly via `json_data=`, but then they do not validate it.
