### ISSUE TITLE
chrome on mac not loading image data

### ISSUE THREAD

**Issue by davidackerman** [google/neuroglancer#457]
I am currently trying to load some data in neuroglancer using chrome on a mac, and while it seems to load segmentation data or annotations, it does not seem to load image data. The error I am getting for this [link](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B41652.98046875%2C61205.98828125%2C34801.00390625%5D%2C%22crossSectionOrientation%22:%5B0%2C1%2C0%2C0%5D%2C%22crossSectionScale%22:4.864787354476631%2C%22projectionOrientation%22:%5B0%2C1%2C0%2C0%5D%2C%22projectionScale%22:65536%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%7B%22url%22:%22n5://s3://janelia-cosem-datasets/jrc_mus-liver/jrc_mus-liver.n5/labels/ariadne/er_seg%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C30984%5D%2C%5B0%2C1%2C0%2C30912%5D%2C%5B0%2C0%2C1%2C15728%5D%5D%2C%22outputDimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22name%22:%22er_seg_ariadne%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%22n5://s3://janelia-cosem-datasets/jrc_mus-liver/jrc_mus-liver.n5/em/fibsem-uint8%22%2C%22tab%22:%22rendering%22%2C%22opacity%22:0.75%2C%22blend%22:%22additive%22%2C%22shader%22:%22#uicontrol%20invlerp%20normalized%28range=%5B105%2C%20182%5D%2C%20window=%5B0%2C%20255%5D%29%5Cn%20%20%20%20%20%20%20%20%20%20#uicontrol%20int%20invertColormap%20slider%28min=0%2C%20max=1%2C%20step=1%2C%20default=0%29%5Cn%20%20%20%20%20%20%20%20%20%20#uicontrol%20vec3%20color%20color%28default=%5C%22white%5C%22%29%5Cn%20%20%20%20%20%20%20%20%20%20float%20inverter%28float%20val%2C%20int%20invert%29%20%7Breturn%200.5%20+%20%28%282.0%20%2A%20%28-float%28invert%29%20+%200.5%29%29%20%2A%20%28val%20-%200.5%29%29%3B%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20emitRGB%28color%20%2A%20inverter%28normalized%28%29%2C%20invertColormap%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%7D%22%2C%22name%22:%22fibsem-uint8%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22n5://s3://janelia-cosem-datasets/jrc_mus-liver/jrc_mus-liver.n5/labels/mito-mem_seg/%22%2C%22tab%22:%22source%22%2C%22segmentDefaultColor%22:%22#008000%22%2C%22name%22:%22mito-mem_seg%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22fibsem-uint8%22%7D%2C%22crossSectionBackgroundColor%22:%22#000000%22%2C%22layout%22:%224panel%22%7D) seems to be this:
WebGL-0x13401d83f00] GL_INVALID_VALUE: Error: 0x00000501, in ../../third_party/angle/src/libANGLE/renderer/gl/TextureGL.cpp, setImageHelper:271. Internal error: 0x00000501: Unexpected driver error.

Any help you can provide would be great! Thanks.

-David

<img width="1532" alt="image" src="https://user-images.githubusercontent.com/19193291/232572392-a620fe52-d8b6-4e74-a981-aa0198bc5f86.png">

**Comment by jbms** [comment]
I haven't seen that particular error before, but from the description it sounds like a bug in Chrome or in the graphics driver.  Have you tried using a different version of Chrome, or a different browser like Firefox or Safari?

**Comment by davidackerman** [comment]
Yup, upgrading chrome fixed it! And it did work on other browsers.
