### ISSUE TITLE
Channel dimensions bounds regression in v2.36

### ISSUE THREAD

**Issue by blowekamp** [google/neuroglancer#459]
Prior version v2.35 was successful but with v2.36 we are getting the following error when creating a source:

Channel dimension c^ must have lower bound of 0 and positive integer upper bound

The error occurs with when loading multi-scale OME-NGFF ZARR data with XYZCT dimensions and the "C" channel is renamed to "c^" in neuroglancer so that multi-channels can be used in the shader. The sub directory of the zarr array can be loading.

Here is a sample zarr which produces the error message:
[0.zip](https://github.com/google/neuroglancer/files/11346877/0.zip)

**Comment by jbms** [comment]
Thanks for reporting this.  I just pushed a fix.

**Comment by blowekamp** [comment]
Thank you. I tested my data and the problem is resoled 🥳
