### ISSUE TITLE
render data access from neuroglancer

### ISSUE THREAD

**Issue by tnguira** [google/neuroglancer#46]
I want to visualize with Neuroglancer a render project (https://github.com/saalfeldlab/render) that is stored locally on a hard drive.
I have built Neuroglancer successfully. I do not know what link I should provide to access the project. I have tried these links unsuccessfully: 

-http://localhost:8080/render-ws/v1/owner/tahar/project/LMEMproject/stack/v1_align_tps
-localhost:8080/render-ws/v1/owner/tahar/project/LMEMproject/stack/v1_align_tps
-render-ws/v1/owner/tahar/project/LMEMproject/stack/v1_align_tps

Before I take more time trying to decipher the regular expression it is looking for (https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/render/frontend.ts#L321), could maybe someone provide an example of a link used to access a local render project ?
Thanks a lot

**Comment by jbms** [comment]
I believe you use a data source URL of the form:
render://http://localhost:8080/tahar/LMEMproject/v1_align_tps

@alexbaden wrote the render datasource and may be able to provide further assistance.

**Comment by jbms** [comment]
Note also that in order to access http:// resources, neuroglancer itself must also be loaded from an http:// (rather than https://) due to browser restrictions

**Comment by tnguira** [comment]
I tried this link but it still does not match the regular expression in https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/render/frontend.ts#L321
@alexbaden could you help please ? 
Thank you.

**Comment by tnguira** [comment]
It is working now. The correct address to use was indeed

render://http://localhost:8080/tahar/LMEMproject/v1_align_tps 

as suggested by @jbms. I do not understand what went wrong before.
Sorry @alexbaden, it was all good.
Thanks for your help
