### ISSUE TITLE
Zstandard support?

### ISSUE THREAD

**Issue by mkitti** [google/neuroglancer#506]
Hi @jbms . Would it be possible to support Zstandard in neuroglancer?

There are a number of JavaScript ports available:
https://facebook.github.io/zstd/

In particular, these one seems to have been maintained within the last year:
https://www.npmjs.com/package/zstddec
https://www.npmjs.com/package/@oneidentity/zstd-js

At Janelia we're thinking of moving data from N5 to Zarr under Zstandard comrpession.

**Comment by jbms** [comment]
It should already be supported.
