### ISSUE TITLE
N5 now supports Zstandard

### ISSUE THREAD

**Issue by mkitti** [google/neuroglancer#509]
Hi, we've added Zstandard support to N5.
https://github.com/JaneliaSciComp/n5-zstandard
See comments from @axtimwalde below.
https://github.com/JaneliaSciComp/n5-zstandard/pull/1

This is in preparation for n5-zarr Zstandard compatibility:
https://github.com/saalfeldlab/n5-zarr/pull/35

Also note that numcodecs.js has updated to Zstandard 1.5.5 as v0.3.0:
https://github.com/manzt/numcodecs.js/releases/tag/v0.3.0
https://github.com/manzt/numcodecs.js/pull/40

**Comment by jbms** [comment]
What are the parameters?  Just level?

**Comment by mkitti** [comment]
Yes. That is the only serialized parameter.

https://github.com/JaneliaSciComp/n5-zstandard/blob/main/src%2Fmain%2Fjava%2Forg%2Fjanelia%2Fscicomp%2Fn5%2Fzstandard%2FZstandardCompression.java#L79-L80
