### ISSUE TITLE
Set matrix transform for ImageLayer via Python

### ISSUE THREAD

**Issue by blowekamp** [google/neuroglancer#517]
I have been unable to find a Python example which sets the coordinate space transform for any layer. Is there a way that the CoordinateSpaceTransform object can be use to set a the "layers.source.transform" field in the json state?

Currently I am creating a `LocalVolume`from a numpy array and ten adding a ImageLayer with the local volume as the source.

The motivation for this capability, is that I have performed affine registration between two volumes/images. I would like to just set these values to visualized the two images co-registered.

**Comment by jbms** [comment]
I just added an example here: https://github.com/google/neuroglancer/commit/e43ed3c56b9fe6ff7871f71e463f84b738803bf2

**Comment by blowekamp** [comment]
Great thank you. 

Here is what I did with an ImageLayer:
```
 ng_transform = neuroglancer.CoordinateSpaceTransform(output_dimensions=dimensions,
                                                             matrix = [[1.0,0.0,0.0,translation[0]],
                                                                       [0.0,1.0,0.0,translation[1]],
                                                                       [0.0,0.0,1.0,0.0]])
layer = neuroglancer.ImageLayer(
            source=neuroglancer.LayerDataSource(volume, transform=ng_transform),
      )
```
