### ISSUE TITLE
Hiding yellow border for images?

### ISSUE THREAD

**Issue by mikejhuang** [google/neuroglancer#519]
I have [multiple zarr images loaded into neuroglancer.](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%2C%22position%22:%5B4%2C1446.1148681640625%2C-2132.2509765625%5D%2C%22crossSectionScale%22:1.7190287811611409%2C%22projectionScale%22:1024%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr2://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.slabface/QM23.50.001.CX.43.Posterior.CX45.Anterior/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C0%2C1%2C0%2C0%5D%2C%5B0%2C0%2C0%2C-1%2C0%5D%5D%2C%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Afloat%28getDataValue%280%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Afloat%28getDataValue%281%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Afloat%28getDataValue%282%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20threshold%20=%200.0%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28r%3E1.0%29r=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28g%3E1.0%29g=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28b%3E1.0%29b=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28r==threshold%20&&%20g==threshold%20&&%20b==threshold%29%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitTransparent%28%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGB%28vec3%28r%2Cg%2Cb%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22CX.43.Anterior.45.Posterior%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr2://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.slabface/QM23.50.001.CX.44/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C0%2C1%2C0%2C0%5D%2C%5B0%2C0%2C0%2C-1%2C0%5D%5D%2C%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Afloat%28getDataValue%280%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Afloat%28getDataValue%281%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Afloat%28getDataValue%282%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20threshold%20=%200.0%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28r%3E1.0%29r=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28g%3E1.0%29g=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28b%3E1.0%29b=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28r==threshold%20&&%20g==threshold%20&&%20b==threshold%29%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitTransparent%28%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGB%28vec3%28r%2Cg%2Cb%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22QM23.50.001.CX.44%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr2://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.slabface/QM23.50.001.CX.44.SpatialBlockPlan/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C0%2C1%2C0%2C0%5D%2C%5B0%2C0%2C0%2C-1%2C0%5D%5D%2C%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Afloat%28getDataValue%280%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Afloat%28getDataValue%281%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Afloat%28getDataValue%282%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20threshold%20=%200.0%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28r%3E1.0%29r=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28g%3E1.0%29g=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28b%3E1.0%29b=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28r==threshold%20&&%20g==threshold%20&&%20b==threshold%29%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitTransparent%28%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGB%28vec3%28r%2Cg%2Cb%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22SpatialBlockPlan%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr2://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.blockface/QM23.50.001.CX.44.01/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C0%2C-0.42950695%2C0.90306355%2C721.5168699351674%5D%2C%5B0%2C0%2C-0.90306355%2C-0.42950695%2C-1339.5983661098026%5D%5D%2C%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20brightness%20slider%28min=-1.0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20contrast%20slider%28min=0%2C%20max=2.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20saturation%20slider%28min=1.0%2C%20max=3.0%2C%20default=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Acontrast%2Afloat%28getDataValue%280%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Acontrast%2Afloat%28getDataValue%281%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Acontrast%2Afloat%28getDataValue%282%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20a%20=%20float%28getDataValue%283%29.value%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20gray%20=%20%28r+g+b%29/3.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20mix%28gray%2C%20r%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20mix%28gray%2C%20g%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20mix%28gray%2C%20b%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20clamp%28r%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20clamp%28g%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20clamp%28b%2C%200.0%2C%201.0%29%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGBA%28vec4%28r%2Cg%2Cb%2Ca%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22QM23.50.001.CX.44.01%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr2://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.blockface/QM23.50.001.CX.44.02/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C0%2C-0.92011774%2C0.39164185%2C2145.413340553374%5D%2C%5B0%2C0%2C-0.39164185%2C-0.92011774%2C-1904.248183590628%5D%5D%2C%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20brightness%20slider%28min=-1.0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20contrast%20slider%28min=0%2C%20max=2.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20saturation%20slider%28min=1.0%2C%20max=3.0%2C%20default=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Acontrast%2Afloat%28getDataValue%280%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Acontrast%2Afloat%28getDataValue%281%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Acontrast%2Afloat%28getDataValue%282%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20a%20=%20float%28getDataValue%283%29.value%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20gray%20=%20%28r+g+b%29/3.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20mix%28gray%2C%20r%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20mix%28gray%2C%20g%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20mix%28gray%2C%20b%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20clamp%28r%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20clamp%28g%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20clamp%28b%2C%200.0%2C%201.0%29%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGBA%28vec4%28r%2Cg%2Cb%2Ca%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22shaderControls%22:%7B%22brightness%22:-0.02%2C%22contrast%22:1.08%2C%22saturation%22:2.2%2C%22normalization%22:117.3%7D%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22QM23.50.001.CX.44.02%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr2://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.blockface/QM23.50.001.CX.44.03/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C0%2C-0.845384%2C-0.53415905%2C2118.8457653867226%5D%2C%5B0%2C0%2C0.53415905%2C-0.845384%2C-2412.93091596036%5D%5D%2C%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20brightness%20slider%28min=-1.0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20contrast%20slider%28min=0%2C%20max=2.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20saturation%20slider%28min=1.0%2C%20max=3.0%2C%20default=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Acontrast%2Afloat%28getDataValue%280%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Acontrast%2Afloat%28getDataValue%281%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Acontrast%2Afloat%28getDataValue%282%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20a%20=%20float%28getDataValue%283%29.value%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20gray%20=%20%28r+g+b%29/3.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20mix%28gray%2C%20r%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20mix%28gray%2C%20g%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20mix%28gray%2C%20b%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20clamp%28r%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20clamp%28g%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20clamp%28b%2C%200.0%2C%201.0%29%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGBA%28vec4%28r%2Cg%2Cb%2Ca%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22QM23.50.001.CX.44.03%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr2://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.blockface/QM23.50.001.CX.44.04/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C0%2C-0.99984911%2C-0.01707399%2C2150.331569092116%5D%2C%5B0%2C0%2C0.01737088%2C-0.99985423%2C-1499.326215146963%5D%5D%2C%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20brightness%20slider%28min=-1.0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20contrast%20slider%28min=0%2C%20max=2.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20saturation%20slider%28min=1.0%2C%20max=3.0%2C%20default=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Acontrast%2Afloat%28getDataValue%280%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Acontrast%2Afloat%28getDataValue%281%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Acontrast%2Afloat%28getDataValue%282%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20a%20=%20float%28getDataValue%283%29.value%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20gray%20=%20%28r+g+b%29/3.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20mix%28gray%2C%20r%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20mix%28gray%2C%20g%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20mix%28gray%2C%20b%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20clamp%28r%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20clamp%28g%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20clamp%28b%2C%200.0%2C%201.0%29%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGBA%28vec4%28r%2Cg%2Cb%2Ca%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22shaderControls%22:%7B%22green_channel%22:0.49%2C%22brightness%22:0.32%2C%22contrast%22:0.88%2C%22saturation%22:1.88%2C%22normalization%22:160.65%7D%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22QM23.50.001.CX.44.04%22%7D%5D%2C%22showAxisLines%22:false%2C%22selectedLayer%22:%7B%22size%22:603%2C%22visible%22:true%2C%22layer%22:%22QM23.50.001.CX.44.01%22%7D%2C%22layout%22:%22yz%22%2C%22helpPanel%22:%7B%22visible%22:true%7D%2C%22selection%22:%7B%22size%22:603%2C%22position%22:%5B4.000000476837158%2C1188.2904052734375%2C-2570.999755859375%5D%2C%22layers%22:%7B%22CX.43.Anterior.45.Posterior%22:%7B%22value%22:%5B0%2C0%2C0%5D%7D%2C%22QM23.50.001.CX.44%22:%7B%22value%22:%5B0%2C0%2C0%5D%7D%2C%22QM23.50.001.CX.44.01%22:%7B%22value%22:%5B97%2C88%2C71%2C0%5D%7D%2C%22QM23.50.001.CX.44.02%22:%7B%22value%22:%5B95%2C97%2C98%2C0%5D%7D%2C%22QM23.50.001.CX.44.03%22:%7B%22value%22:%5B207%2C162%2C119%2C255%5D%7D%2C%22QM23.50.001.CX.44.04%22:%7B%22value%22:%5B164%2C157%2C128%2C0%5D%7D%7D%7D%7D) Each image has a yellow border. How can this be hidden?

**Comment by xgui3783** [comment]
- click top right `[gear]` icon 
- uncheck  bottom left `show default annotation`

**Comment by mikejhuang** [comment]
> * click top right `[gear]` icon
> * uncheck  bottom left `show default annotation`

worked!

**Comment by stuarteberg** [comment]
To hide it for a single layer, uncheck the `[bounds]` option in the layer's `Source` options.

<img width="352" alt="image" src="https://github.com/google/neuroglancer/assets/1655821/2dcc3b89-841d-4f90-9250-3f0ef8061498">
