### ISSUE TITLE
Spatial dimensions, xy, is rendering in the 'zy' plane instead of the 'xy' plane when using the zarr format

### ISSUE THREAD

**Issue by mikejhuang** [google/neuroglancer#523]
The 'xy' dimensions are being rendered on the 'zy' plane in neuroglancer. Seems that neuroglancer maps the first two spatial dimensions to x, y. However, zarr expects the dimension ordering to be (c, z, y, x).  In this case, z, y, x are the three spatial dimensions and z, y becomes the first two dimensions mapped to the 'xy' plane and x, y is mapped to the 'zy' plane. 

I configured neuroglancer with the ordering of the zarr.
```
  "dimensions": {
    "z": [
      0.001,
      "m"
    ],
    "y": [
      0.00002,
      "m"
    ],
    "x": [
      0.00002,
      "m"
    ]
  },
  ```
  
 and with each layer
 ```
           "outputDimensions": {
            "c^": [
              1,
              ""
            ],
            "z": [
              0.001,
              "m"
            ],
            "y": [
              0.00002,
              "m"
            ],
            "x": [
              0.00002,
              "m"
            ]
          }
```
  
Is there a way to configure neuroglancer to recognize this ordering of the dimensions when rendering in the planes?

[Here's an example](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%2C%22position%22:%5B6%2C1379.0257568359375%2C2218%5D%2C%22crossSectionScale%22:1.338780960890579%2C%22projectionScale%22:1024%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.slabface/QM23.50.001.CX.43.Posterior.CX45.Anterior/%22%2C%22transform%22:%7B%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22rendering%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Afloat%28getDataValue%280%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Afloat%28getDataValue%281%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Afloat%28getDataValue%282%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20threshold%20=%200.0%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28r%3E1.0%29r=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28g%3E1.0%29g=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28b%3E1.0%29b=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28r==threshold%20&&%20g==threshold%20&&%20b==threshold%29%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitTransparent%28%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGB%28vec3%28r%2Cg%2Cb%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22CX.43.Anterior.45.Posterior%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.slabface/QM23.50.001.CX.44/%22%2C%22transform%22:%7B%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22rendering%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Afloat%28getDataValue%280%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Afloat%28getDataValue%281%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Afloat%28getDataValue%282%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20threshold%20=%200.0%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28r%3E1.0%29r=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28g%3E1.0%29g=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28b%3E1.0%29b=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28r==threshold%20&&%20g==threshold%20&&%20b==threshold%29%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitTransparent%28%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGB%28vec3%28r%2Cg%2Cb%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22QM23.50.001.CX.44%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.slabface/QM23.50.001.CX.44.SpatialBlockPlan/%22%2C%22transform%22:%7B%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22rendering%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Afloat%28getDataValue%280%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Afloat%28getDataValue%281%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Afloat%28getDataValue%282%29.value%29/normalization%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20threshold%20=%200.0%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28r%3E1.0%29r=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28g%3E1.0%29g=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28b%3E1.0%29b=1.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28r==threshold%20&&%20g==threshold%20&&%20b==threshold%29%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitTransparent%28%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGB%28vec3%28r%2Cg%2Cb%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22SpatialBlockPlan%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.blockface/QM23.50.001.CX.44.01/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C0%2C-0.42950695%2C0.90306355%2C721.5168699351674%5D%2C%5B0%2C0%2C0.90306355%2C0.42950695%2C1339.5983661098026%5D%5D%2C%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22rendering%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20brightness%20slider%28min=-1.0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20contrast%20slider%28min=0%2C%20max=2.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20saturation%20slider%28min=1.0%2C%20max=3.0%2C%20default=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Acontrast%2Afloat%28getDataValue%280%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Acontrast%2Afloat%28getDataValue%281%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Acontrast%2Afloat%28getDataValue%282%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20a%20=%20float%28getDataValue%283%29.value%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20gray%20=%20%28r+g+b%29/3.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20mix%28gray%2C%20r%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20mix%28gray%2C%20g%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20mix%28gray%2C%20b%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20clamp%28r%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20clamp%28g%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20clamp%28b%2C%200.0%2C%201.0%29%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGBA%28vec4%28r%2Cg%2Cb%2Ca%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22QM23.50.001.CX.44.01%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.blockface/QM23.50.001.CX.44.02/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C0%2C-0.90832338%2C0.41826863%2C2162.957230438247%5D%2C%5B0%2C0%2C0.41826863%2C0.90832338%2C1866.3070933686029%5D%5D%2C%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22rendering%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20brightness%20slider%28min=-1.0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20contrast%20slider%28min=0%2C%20max=2.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20saturation%20slider%28min=1.0%2C%20max=3.0%2C%20default=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Acontrast%2Afloat%28getDataValue%280%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Acontrast%2Afloat%28getDataValue%281%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Acontrast%2Afloat%28getDataValue%282%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20a%20=%20float%28getDataValue%283%29.value%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20gray%20=%20%28r+g+b%29/3.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20mix%28gray%2C%20r%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20mix%28gray%2C%20g%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20mix%28gray%2C%20b%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20clamp%28r%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20clamp%28g%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20clamp%28b%2C%200.0%2C%201.0%29%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGBA%28vec4%28r%2Cg%2Cb%2Ca%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22QM23.50.001.CX.44.02%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.blockface/QM23.50.001.CX.44.03/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C0%2C-0.845384%2C-0.53415905%2C2118.8457653867226%5D%2C%5B0%2C0%2C-0.53415905%2C0.845384%2C2412.93091596036%5D%5D%2C%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22rendering%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20brightness%20slider%28min=-1.0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20contrast%20slider%28min=0%2C%20max=2.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20saturation%20slider%28min=1.0%2C%20max=3.0%2C%20default=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Acontrast%2Afloat%28getDataValue%280%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Acontrast%2Afloat%28getDataValue%281%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Acontrast%2Afloat%28getDataValue%282%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20a%20=%20float%28getDataValue%283%29.value%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20gray%20=%20%28r+g+b%29/3.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20mix%28gray%2C%20r%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20mix%28gray%2C%20g%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20mix%28gray%2C%20b%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20clamp%28r%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20clamp%28g%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20clamp%28b%2C%200.0%2C%201.0%29%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGBA%28vec4%28r%2Cg%2Cb%2Ca%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22QM23.50.001.CX.44.03%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22zarr://https://neuroglancer-hmba.s3.us-west-2.amazonaws.com/QM23.50.001.CX.44.blockface/QM23.50.001.CX.44.04/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%2C0%5D%2C%5B0%2C0%2C-0.99984911%2C-0.01707399%2C2150.331569092116%5D%2C%5B0%2C0%2C-0.01737088%2C0.99985423%2C1499.326215146963%5D%5D%2C%22outputDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%2C%22z%22:%5B0.001%2C%22m%22%5D%2C%22y%22:%5B0.00002%2C%22m%22%5D%2C%22x%22:%5B0.00002%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22rendering%22%2C%22opacity%22:1%2C%22shader%22:%22%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20red_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20green_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20blue_channel%20slider%28min=0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20brightness%20slider%28min=-1.0%2C%20max=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20contrast%20slider%28min=0%2C%20max=2.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20saturation%20slider%28min=1.0%2C%20max=3.0%2C%20default=1.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20#uicontrol%20float%20normalization%20slider%28min=0%2C%20max=255.0%29%5Cn%20%20%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20r%20=%20red_channel%2Acontrast%2Afloat%28getDataValue%280%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20g%20=%20green_channel%2Acontrast%2Afloat%28getDataValue%281%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20b%20=%20blue_channel%2Acontrast%2Afloat%28getDataValue%282%29.value%29/normalization+brightness%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20a%20=%20float%28getDataValue%283%29.value%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20float%20gray%20=%20%28r+g+b%29/3.0%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20mix%28gray%2C%20r%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20mix%28gray%2C%20g%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20mix%28gray%2C%20b%2C%20saturation%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20r%20=%20clamp%28r%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20g%20=%20clamp%28g%2C%200.0%2C%201.0%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%20=%20clamp%28b%2C%200.0%2C%201.0%29%3B%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20emitRGBA%28vec4%28r%2Cg%2Cb%2Ca%29%29%3B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%22%2C%22shaderControls%22:%7B%22normalization%22:122.4%7D%2C%22channelDimensions%22:%7B%22c%5E%22:%5B1%2C%22%22%5D%7D%2C%22name%22:%22QM23.50.001.CX.44.04%22%7D%5D%2C%22showAxisLines%22:false%2C%22showDefaultAnnotations%22:false%2C%22selectedLayer%22:%7B%22size%22:603%7D%2C%22layout%22:%22yz%22%7D)

**Comment by jbms** [comment]
Neuroglancer by default maps the first 3 global dimensions to be the "display dimensions".  You can drag and drop them to reorder them at the top left of the window which will affect the display dimensions.  Or you can explicitly override the display dimensions (click on the vertical red/green/blue "z", "y", "x" at left side of the cross-section panel and type in the desired dimension names).

As far as doing this automatically for OME-zarr, there is currently no way to achieve that with Neuroglancer.  It can be implemented but will require a mechanism to change how data source dimensions are incorporated into the global dimension list.

**Comment by mikejhuang** [comment]
> Neuroglancer by default maps the first 3 global dimensions to be the "display dimensions". You can drag and drop them to reorder them at the top left of the window which will affect the display dimensions. Or you can explicitly override the display dimensions (click on the vertical red/green/blue "z", "y", "x" at left side of the cross-section panel and type in the desired dimension names).
> 
> As far as doing this automatically for OME-zarr, there is currently no way to achieve that with Neuroglancer. It can be implemented but will require a mechanism to change how data source dimensions are incorporated into the global dimension list.

That worked, thanks.
As for doing it automatically, the drag and drop reorder changed the dimensions configuration to:

```
  "dimensions": {
    "x": [
      0.00002,
      "m"
    ],
    "y": [
      0.00002,
      "m"
    ],
    "z": [
      0.001,
      "m"
    ]
  }
```

So it seems that this ordering can be set this way to do it automatically.

**Comment by jbms** [comment]
To be clear, you can certainly configure it in the Neuroglancer state, since everything is specified in the Neuroglancer state.  What you can't do currently is generate an OME-zarr dataset, with dimensions ordered as c, z, y, x, where just adding the dataset to Neuroglancer interactively will result in the desired x, y, z global dimension order.
