### ISSUE TITLE
Loading of precomputed data stalls

### ISSUE THREAD

**Issue by eddyod** [google/neuroglancer#525]
When loading either large full resolution or downsampled precomputed data, the loading often just hangs and never completes the rendering.  Is there any reason the data doesn't load? Here is some further info:
1. Data is sharded precomputed data sent from nginx (we've also used Apache)
2. We use the igneous cloudvolume tools to create 4 MIPS levels for the downsampled data and 7 MIP levels for the full resolution data.
3. The same situation has happened on Mac, Chrome and Firefox. 
4. Our web server has plenty of RAM and CPU.

Thanks!

**Comment by fcollman** [comment]
just some debugging tips for more information... if you open developer tools>network and look at the individual requests are they returning 404 or 500 errors, or some other kind of error? Or all requests are going through with no problem. Usually there is some kind of bottleneck, such as a limited number of uwsgi workers allocated on the web server you are running or something that leads to gateway timeouts or things like this in my experience. 

Sometimes there are actual neuroglancer bugs, but particularly if you are running your own webserver I suspect the issue might be in the configuration of how many parallel requests it can handle.  You can tune the concurrent requests in the gear symbol to see if 'stalling' stops even as overall throughput goes down.

**Comment by eddyod** [comment]
Thanks. The suggestion increasing the concurrent requests sounds like a good idea.
