### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by georgwiese** [google/neuroglancer#53]
The Neuroglancer Python Integration doesn't seem to work properly with python 3. E.g., the `example.py` produces URLs that lead to 404.

Is there any support planned for this?

**Comment by jbms** [comment]
Thanks for reporting this.   Python 3 used to work, but some issues crept in over time.  This is now fixed by f4e1f05aaac82448aa96c38088b8e2149c771fb8.

**Comment by georgwiese** [comment]
Thanks a lot! Are you going to publish the latest version to PyPI?
