### ISSUE TITLE
overly coarse mouseover for OME-Zarr segmentations

### ISSUE THREAD

**Issue by d-v-b** [google/neuroglancer#539]
The label values reported when mousing over our OME-Zarr segmentation images seem to be too coarse, e.g. as if a lower scale level were being used for intersecting the mouse position with the imaging data. See this representative example: ([example](http://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22z%22:%5B2e-9%2C%22m%22%5D%2C%22y%22:%5B2e-9%2C%22m%22%5D%2C%22x%22:%5B2e-9%2C%22m%22%5D%7D%2C%22position%22:%5B1309.4674072265625%2C873.339599609375%2C13347.44140625%5D%2C%22crossSectionScale%22:1.4549914146181995%2C%22projectionScale%22:606804078424.9197%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%22zarr://s3://janelia-cosem-datasets/jrc_hela-2/jrc_hela-2.zarr/recon-1/labels/groundtruth/crop1/all/%22%2C%22tab%22:%22source%22%2C%22crossSectionRenderScale%22:0.09045432734002362%2C%22segments%22:%5B%5D%2C%22name%22:%22all%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22all%22%7D%2C%22layout%22:%224panel%22%7D))

cc @davidackerman

**Comment by davidackerman** [comment]
Commenting on this as it is a continued bug. The information (raw values, segmentation ids etc) displayed based on cursor position can be incorrect for multiscale zarrs. This makes it difficult to select correct ids to view or to know the underlying values.
