### ISSUE TITLE
Unable to serve viewer from pip installation with neuroglancer 2.39.1

### ISSUE THREAD

**Issue by droumis** [google/neuroglancer#542]
## Versions

neuroglancer 2.39.1
python 3.10.13
mac OSX 13.5.2 M1

## Steps to reproduce:

Script:
1. create and activate new conda env with python 3.10
2. `pip install neuroglancer`
3.  from examples dir, run `python -i example.py` -> produces 404 page
  -  ![image](https://github.com/google/neuroglancer/assets/6613202/be8c8fdd-644d-490f-a3ee-52eaf10282b6) 
  - chrome browser console: "Failed to load resource: the server responded with a status of 404 (Not Found)"

5. Tried other examples, same result

Notebook:
1. open and run first few cells in `jupyter-notebook-demo.ipynb` -> link to viewer also produces 404

## Expected:
I should be seeing the neuroglancer app

**Comment by satra** [comment]
seeing the same issue.

```
neuroglancer  2.39.1
osx sonoma      14.4
python        3.12.2
```
