### ISSUE TITLE
Error When Visualizing Local N5 File in Neuroglancer

### ISSUE THREAD

**Issue by bang2003er** [google/neuroglancer#602]
I followed the steps on [this GitHub issue](https://github.com/google/neuroglancer/issues/417) to visualize my local N5 file, but the final result looks like this (referring to the image). What could be the reason for this?
![error](https://github.com/google/neuroglancer/assets/88014545/8c5a4dbe-993c-4227-8f8a-493a24f74d86)

And this is my attributes.json
```
{
    "scales":[[
        128.0,
        128.0,
        128.0
    ]],
    "blockSize": [
        128,
        128,
        64
    ],
    "compression": {
        "level": -1,
        "type": "gzip",
        "useZlib": false
    },
    "dataType": "uint8",
    "dimensions": [
        1275,
        1185,
        1061
    ],
    "pixelResolution": {
        "dimensions": [
            128.0,
            128.0,
            128.0
        ],
        "unit": "nm"
    },
    "transform": {
        "axes": [
            "z",
            "y",
            "x"
        ],
        "order": "C",
        "scale": [
            128.0,
            128.0,
            128.0
        ],
        "translate": [
            60.0,
            60.0,
            60.0
        ],
        "units": [
            "nm",
            "nm",
            "nm"
        ]
    }
}


```

**Comment by xgui3783** [comment]
Try clicking "create an image layer" at bottom right? (In yellow)

**Comment by ZhenbangZhang** [comment]
> Try clicking "create as an image layer" at bottom right? (In yellow)

Thank you very much, I have successfully visualized the 3D structure. Does Neuroglancer provide a feature for high-resolution screenshots?

**Comment by jbms** [comment]
You can do that using the Python module "neuroglancer.tool.screenshot" included in the Python package.
