### ISSUE TITLE
Use coordinates with spatial units

### ISSUE THREAD

**Issue by chourroutm** [google/neuroglancer#603]
This may be either a docs issue or a feature request.

I have successfully applied a transformation to a dataset with a correctly scaled output dimension. Now, I would like to use coordinates with the spatial units instead of voxel-based integer coordinates: is there a way to do so with the main branch of neuroglancer?

Example: https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B0.000025079999999999997%2C%22m%22%5D%2C%22y%22:%5B0.000025079999999999997%2C%22m%22%5D%2C%22z%22:%5B0.000025079999999999997%2C%22m%22%5D%7D%2C%22position%22:%5B2982.5%2C2982.5%2C3495.5%5D%2C%22crossSectionScale%22:1%2C%22projectionOrientation%22:%5B0.3094263970851898%2C0.20628425478935242%2C0%2C-0.9282791018486023%5D%2C%22projectionScale%22:2247.9324614411316%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22n5://gs://ucl-hip-ct-35a68e99feaae8932b1d44da0358940b/LADAF-2020-31/brain/25.08um_complete-organ_bm05/%22%2C%22transform%22:%7B%22matrix%22:%5B%5B0%2C-1%2C0%2C2982%5D%2C%5B-1%2C0%2C0%2C2982%5D%2C%5B0%2C0%2C1%2C-3001%5D%5D%2C%22outputDimensions%22:%7B%22x%22:%5B0.000025079999999999997%2C%22m%22%5D%2C%22y%22:%5B0.000025079999999999997%2C%22m%22%5D%2C%22z%22:%5B0.000025079999999999997%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22source%22%2C%22shaderControls%22:%7B%22normalized%22:%7B%22range%22:%5B15671%2C24381%5D%7D%7D%2C%22name%22:%22LADAF-2020-31_brain_complete-organ_25.08um_bm05%22%7D%5D%2C%22selectedLayer%22:%7B%22size%22:1062%2C%22visible%22:true%2C%22layer%22:%22LADAF-2020-31_brain_complete-organ_25.08um_bm05%22%7D%2C%22layout%22:%224panel%22%7D

(Colleagues who might be interested in the thread: @ucbpclw @balbasty @dstansby)

**Comment by jbms** [comment]
Neuroglancer currently always assumes some global voxel size, which impacts the arrow keys and mouse wheel movement through z, and a few other things.

But you can, for example, double click in the top left of the window on "25.08um" next to "x" and type in "1um" instead.  And do the same for y and z.
