### ISSUE TITLE
Python data source commented out

### ISSUE THREAD

**Issue by LeeKamentsky** [google/neuroglancer#61]
The Python datasource is commented out here: https://github.com/google/neuroglancer/blob/master/config/webpack_helpers.js#L56

The client doesn't allow you to specify a Python datasource with this line commented out. If you uncomment the line and rebuild the webpack server and issue the `npm run dev-server` command, the client can serve Python datasources again.

**Comment by jbms** [comment]
The new version of the python integration is intended to be used with a
python-specific version of the client, built using the targets in
package.json with python in their names.  The python client connects to the
python program with a sockjs connection which enables communication of the
viewer state, configuration and credentials between them.

Does the new version not cover an existing use case?

**Comment by LeeKamentsky** [comment]
I think I didn't understand that part. I was previously starting the client-serving code using `npm run dev-server`. I just tried it with `npm run dev-server-python` and it works correctly. So sorry for the misunderstanding.
