### ISSUE TITLE
Safari Browser does not support polygon propagation

### ISSUE THREAD

**Issue by mm6654** [google/neuroglancer#642]
Safari browser did not allow for polygon propagation. Normally, a new browser requests for access to allow pasting of polygons, but Safari did not display that pop-up. I de-activated pop-up blockers and cleared the cookie history and still could not get the pop-up to display.

**Comment by mm6654** [comment]
This was only an issue on the dk lab computer, but was not an issue on my personal laptop.

**Comment by jbms** [comment]
I think this is intended for a different issue tracker.
