### ISSUE TITLE
viewing Zarr v3 and OME-Zarr

### ISSUE THREAD

**Issue by will-moore** [google/neuroglancer#651]
I'm trying to view Zarr v3 data.

If I enter the OME-Zarr URL:

https://uk1s3.embassy.ebi.ac.uk/idr/share/ome2024-ngff-challenge/0.0.5/6001240.zarr/
I get: "Neithre array nor OME multiscale metadata found":

![Image](https://github.com/user-attachments/assets/8eeba13a-f702-4db0-9e83-041e2f53dea8)

This is understandable as the OME-Zarr spec hasn't been released for Zarr v3 yet.
If I try to load a vanilla zarr v3 array from that image:

https://uk1s3.embassy.ebi.ac.uk/idr/share/ome2024-ngff-challenge/0.0.5/6001240.zarr/0/

It seems to understand the array (dimensions etc), but I don't see any chunks being loaded etc:

![Image](https://github.com/user-attachments/assets/1f911038-6362-4895-8259-934ea4f3389b)

This image has a single shard, but I don't see any failed requests (CORS issues etc related to https://github.com/google/neuroglancer/issues/606)

**Comment by xgui3783** [comment]
Have you tried clicking `Create as image layer` yellow button at bottom right?

**Comment by will-moore** [comment]
Ah - apologies for my lack of basic neuroglancer knowledge!

So this is looking like the same issue as #606 as I'm seeing CORS issues for reading chunks (reading zarr.json is OK):

```
Access to fetch at 'https://uk1s3.embassy.ebi.ac.uk/idr/share/ome2024-ngff-challenge/0.0.5/6001240.zarr/0/c/0/0/0/0' from origin 'https://neuroglancer-demo.appspot.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

However, I know that this image has sufficient CORS settings to be viewable in vizarr: https://hms-dbmi.github.io/vizarr/?source=https://uk1s3.embassy.ebi.ac.uk/idr/share/ome2024-ngff-challenge/0.0.5/6001240.zarr/0/

Checking the difference in request headers in the browser:

Neuroglancer has:
```
range: bytes=-7556
referer: https://neuroglancer-demo.appspot.com/
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
```

Vizarr has a bunch more:

```
accept: */*
accept-encoding: identity
accept-language: en-GB,en-US;q=0.9,en;q=0.8
cache-control: no-cache
connection: keep-alive
host: uk1s3.embassy.ebi.ac.uk
origin: https://hms-dbmi.github.io
pragma: no-cache
range: bytes=24660261-49328077
referer: https://hms-dbmi.github.io/
sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
```

![Image](https://github.com/user-attachments/assets/8116b561-4ff1-4fa1-b688-895039d43734)

I haven't looked at the details how how the requests are being made there, but I do know about loading chunks in the ome-ngff-validator. E.g. Zarr v3 support at preview: https://deploy-preview-36--ome-ngff-validator.netlify.app/?source=https://uk1s3.embassy.ebi.ac.uk/idr/share/ome2024-ngff-challenge/0.0.5/6001240.zarr

HEAD:
```
referer: https://deploy-preview-36--ome-ngff-validator.netlify.app/
sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
```
GET:
```
range: bytes=1653732-3315019
referer: https://deploy-preview-36--ome-ngff-validator.netlify.app/
sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
```

Here the chunks are being loaded with `zarrita.js`:
```
  import * as zarr from "zarrita";
  import { slice } from "@zarrita/indexing";
...
  const store = new zarr.FetchStore(url);
  const arr = await zarr.open(store, { kind: "array" });
  chunk = await zarr.get(arr, slices);
```

**Comment by normanrz** [comment]
I think it would be great, if Neuroglancer could support the 0.5 OME-Zarr metadata for the multiscale. The format is pretty much stable now. https://ngff.openmicroscopy.org/rfc/2/index.html

**Comment by xgui3783** [comment]
I had some time and dug a little deeper, it appears, for whatever reason, requests originating from neuroglancer does not append `Origin` header, yet the web server at https://uk1s3.embassy.ebi.ac.uk/idr/share/ome2024-ngff-challenge/0.0.5/6001240.zarr _needs_ the `Origin` header to append the CORS header, even though it is `*`.

**Comment by jbms** [comment]
The difference between Neuroglancer and vizarr is that Neuroglancer previously attempted a suffixRange request with a `range: bytes=-N` request header to retrieve the last N bytes (in order to retrieve the shard index).  In contrast, vizarr (using zarrita.js) always uses a separate HEAD request to determine the length, and then issues a normal byte range `range: bytes=X-Y` request.  I used a suffixRange request in Neuroglancer to avoid the need for a separate HEAD request to determine the length, but I just learned that these suffixRange byte range requests are not in the CORS safelist and therefore always trigger a preflight OPTIONS request; that negates the benefit of avoiding the HEAD request.

The problem with https://uk1s3.embassy.ebi.ac.uk/ is that it does not respond correctly to the preflight OPTIONS requests.  This issue doesn't come up with vizarr because it does not rigger them, but it does come up with Neuroglancer.

However, as of https://github.com/google/neuroglancer/commit/1255beb992e5ab33932a4ecb6966a022be253803 I have changed Neuroglancer to always just use a separate HEAD request, and zarr v3 sharded datasets served from https://uk1s3.embassy.ebi.ac.uk/ now work.

**Comment by jbms** [comment]
It would still be good for https://uk1s3.embassy.ebi.ac.uk/ to fix their configuration to support the CORS preflight requests.  In Firefox versions earlier than 117 (which includes some still-active long-term support versions), all byte range requests trigger a CORS preflight request and therefore vizarr does not work with https://uk1s3.embassy.ebi.ac.uk/ on Firefox <117 (https://bugzilla.mozilla.org/show_bug.cgi?id=1733981).

**Comment by joshmoore** [comment]
Thanks, @jbms!

**Comment by will-moore** [comment]
Thanks all!
