### ISSUE TITLE
Any way to hide point annotations outside of current viewed section?

### ISSUE THREAD

**Issue by andythai** [google/neuroglancer#657]
I currently have some image sections making up a volume, each section has a corresponding set of point annotations in an annotation layer. However, when I view the annotations, almost all of the point annotations are shown in the visualization (e.g. when looking at section 200, Neuroglancer shows point annotations from section 150-250). Points that are farther away from the current section seem to have a lower opacity, and zooming in seems to make this more so. 

![Image](https://github.com/user-attachments/assets/b3e5757c-7893-4aa0-b15d-e02984b2802c)

Is there a way to hide point annotations whose positions do not match the current section (such that section x only shows point annotations in section x)?

**Comment by jbms** [comment]
You can adjust the depth range for annotations with alt+mousewheel.

**Comment by andythai** [comment]
Ah, thank you! I see you can also set this value as "crossSectionDepth" in the JSON file as well.
