### ISSUE TITLE
Moving axis lines instead of the rendered slices

### ISSUE THREAD

**Issue by hsellik** [google/neuroglancer#660]
Hi

Is there a way to move axis lines instead of the image when inspecting slices?

More specifically, I mean that the axis lines (red/green/blue) seem to be locked in the middle of the screen and when I zoom in one of the images, the other two will move, which is not desirable.

Is something like this possible, which is quite common in other tools? https://niivue.github.io/niivue/features/basic.multiplanar.html

**Comment by jbms** [comment]
Unfortunately that isn't supported.  Potentially it could be implemented.  However, it seems that the behavior you describe would not be compatible with zooming --- the example you provided does not seem to support zooming.

**Comment by hsellik** [comment]
Thank you for getting back. Here is an example that supports panning and zooming: https://niivue.github.io/niivue/features/dragCallback.html

It is more convenient in use cases where the user is not zoomed in too much. If zoomed in very close, then there's not much of a difference. I assume the latter is how the neuroglancer is used most often.

It looks like this wouldn't be worth the effort, so closing the issue.
