### ISSUE TITLE
Library package build missing dataSources

### ISSUE THREAD

**Issue by r2dliu** [google/neuroglancer#667]
When I clone the repo and run via dev-server, everything seems fine. When I build the package via `build-package` and install the locally build lib as a dependency, the same `setupDefaultViewer()` call with no additional configuration renders the viewer just fine but the sidebar is missing the ability to choose any data source other than "local". Dug a bit through the source code but can't seem to find the discrepancy yet. What am I missing here?

**Comment by r2dliu** [comment]
I solved this, it looks like something is oddly configured with the module export during the package build process. I have an inkling as to where it might be fixed but a workaround until I can make a pr or hear preferred direction from the maintainers is something akin to

```
await import('neuroglancer/dist/package/lib/main_module'); // this line was missing and so the enabled frontend datasources import line never ran
const { setupDefaultViewer } = await import('neuroglancer/unstable/ui/default_viewer_setup.js');
viewer = await setupDefaultViewer();
```

**Comment by r2dliu** [comment]
one workaround is to manually do the main module import before calling setupDefaultViewer. might be a cleaner change to the package install itself that would remove this as a necessity. If the maintainers have a preferred direction on this happy to work on a PR for a more holistic change
```
await import("neuroglancer/unstable/main_module.js") // make sure this exists
const { setupDefaultViewer } = await import('neuroglancer/unstable/ui/default_viewer_setup.js');
viewer = await setupDefaultViewer(); // now this will load the dataSourceMap and whatnot properly
```

**Comment by jbms** [comment]
It is indeed intended that you have to `import "neuroglancer";` in order to get all of the data sources registered.  However, clearly some better documentation would be useful.
