### ISSUE TITLE
Vite Example Fails to Load Layers in Dev Mode

### ISSUE THREAD

**Issue by hsellik** [google/neuroglancer#683]
**Description:**  
I tried out the Neuroglancer Vite example, but it fails to load layers with the dev server. I read that this is expected for brainmaps and bossDB data sources, but I'm trying out precomputed gs resource, such as this: `precomputed://gs://neuroglancer-public-data/kasthuri2011/image`

It seems that there are issues loading the javascript into the web worker.  
`GET http://localhost:5173/node_modules/.vite/deps/chunk_worker.bundle.js?worker_file&type=module` gives 404. It works properly in production.

**PS:** 
I replaced the local Neuroglancer dependency with the one from npm in package.json.

I'm guessing this probably breaks the Neuroglancer web worker loading because we don't load the web worker content from the parent project anymore. Still have to investigate a little bit.
```
server: {
    fs: {
      // Allow serving files from parent neuroglancer project, due to the local
      // path reference.  This would not be needed for projects that depend on
      // Neuroglancer normally.
      allow: ["../../.."],
    },
  },
```

It would be nice to have an example for a setup without Neuroglancer source in a parent folder, since I imagine people not wanting to include the entire Neuroglancer source code to their project when they want to integrate it somewhere.

**Browser:**  
Chrome Version 131.0.6778.109 (Official Build) (arm64)

**Comment by jbms** [comment]
I pushed a fix to the example -- unfortunately a lot of implementation details of Neuroglancer need to be exposed in the vite configuration.  Previously, I considered switching Neuroglancer to use vite for its own build, but decided against it because the vite dev server and the vite production build are essentially two entirely different build systems with very different behaviors and limitations.

**Comment by hsellik** [comment]
Forgot to say thank you! Can confirm that this works. Had some `codemirror` errors in console initially, but had to delete `node_modules` and reinstall the dependency to make it work.

Seems like there really is not a good solution to this in esbuild indeed.
https://github.com/evanw/esbuild/issues/312
