### ISSUE TITLE
Suppressing xz and yz views

### ISSUE THREAD

**Issue by hsseung** [google/neuroglancer#8]
It would be great to have the option of suppressing the xz and yz views.  I.e. show only xy and 3D.  Showing three orthogonal views is good for block face data but for serial section EM data it's a waste of screen space.

**Comment by jbms** [comment]
I added this feature (XY and 3D view side-by-side).  If you have any suggestions regarding a more convenient UI for switching between views than just toggling between the options, let me know.

**Comment by hsseung** [comment]
This is great!  Yes other important UI features seem to be missing...will try to post them soon.
