### ISSUE TITLE
Incorrect handling of precomputed subvolume coordinates

### ISSUE THREAD

**Issue by pgunn** [google/neuroglancer#82]
I'm using cloud-volume ( https://github.com/seung-lab/cloud-volume ) to create precomputed segmentation volumes for use in Neuroglancer (from point predictions generated by google-ffn), and as far as I can read the specs for precomputed volumes here: 
https://github.com/google/neuroglancer/tree/master/src/neuroglancer/datasource/precomputed

Neuroglancer appears to be mis-parsing the volume_size field in precomputed JSON, turning it directly into end coordinates for the segmentation volume rather than adding its values to voxel_offset to get that same data.

(I'm spotting this with the version running on neuroglancer-demo.appspot.com)

Here is a precomputed data layer demonstrating the issue:
https://neuroglancer-demo.appspot.com/#!{'layers':{'volumetric-1521214834':{'tab':'annotations'_'selectedAnnotation':'data-bounds'_'source':'precomputed://https://s3.us-east-2.amazonaws.com/megaphragma-neuroglancer/waspem/volumetric-1521214834'_'type':'segmentation'}}_'navigation':{'pose':{'position':{'voxelSize':[8_8_8]_'voxelCoordinates':[3110.885009765625_7685.583984375_3677.552001953125]}}_'zoomFactor':10.798870460608036}_'perspectiveOrientation':[-0.07376252114772797_-0.7471214532852173_0.025685368105769157_0.6600825190544128]_'perspectiveZoom':1669.033507744755_'showSlices':false}

As you can see from the info file here:
https://s3.us-east-2.amazonaws.com/megaphragma-neuroglancer/waspem/volumetric-1521214834/info

The size is 250x250x250, but the bounding box is not cubic and far larger than it should be, stretching back *to* the absolute position 250,250,250 rather than +250,+250,+250 relative to the voxel_offset coordinates. If you left-click on the volume and go to the annotations tab, you'll see that the data bounds align with this interpretation. (The overlay displays fine though)

I have, for the sake of experimentation, generated a layer that plays nice with this bug and has the size in its json file be instead the end coordinates of the cube:
https://neuroglancer-demo.appspot.com/#!{'layers':{'volumetric-1521215128':{'tab':'annotations'_'source':'precomputed://https://s3.us-east-2.amazonaws.com/megaphragma-neuroglancer/waspem/volumetric-1521215128'_'type':'segmentation'}}_'navigation':{'pose':{'position':{'voxelSize':[8_8_8]_'voxelCoordinates':[3110.885009765625_7685.583984375_3677.552001953125]}}_'zoomFactor':10.798870460608036}_'perspectiveOrientation':[-0.07376252114772797_-0.7471214532852173_0.025685368105769157_0.6600825190544128]_'perspectiveZoom':1669.033507744755_'showSlices':false_'selectedLayer':{'layer':'volumetric-1521215128'_'visible':true}}

and

https://s3.us-east-2.amazonaws.com/megaphragma-neuroglancer/waspem/volumetric-1521215128/info

This displays as cubic and has the right annotation values, but it's not following the spec.

**Comment by jbms** [comment]
Thanks for reporting this.  There was a bug in how the bounding boxes used to display the data bounds was being constructed --- the data itself was being displayed properly.  This has now been fixed.
