### ISSUE TITLE
limit z range for mouse scrollwheel

### ISSUE THREAD

**Issue by berl** [google/neuroglancer#85]
Currently neuroglancer will allow you to ctl-scroll in z well outside the range of any image stacks.  I'm working with stacks that are just a few images deep and it's easy to end up far away from the data.  I'd love to see scrollable z range to the z limits of the data (maybe padded with 1 slice to make people feel good about reaching the end).  Thanks!

**Comment by jbms** [comment]
This feature makes sense --- are you interested in trying to implement it?

**Comment by berl** [comment]
This is probably not a good job for me, given that I had to google what .ts is!  From poking around, maybe it could be implemented by adding a check in the SpatialPosition [class](https://github.com/google/neuroglancer/blob/6ead5a974f014a56bbf5fe049328eb2f618bf457/src/neuroglancer/navigation_state.ts#L184) . The validity of the new z position is checked (i.e. is it null?) before updating it and there could be a new method added to the SpatialPosition class to check if it's in the z limits of any current stack.  It's possible such a method could also be useful for annotation tasks and allowing the user to toggle display of annotation objects inside or outside the image data volume.

**Comment by jbms** [comment]
At long last, this has been implemented as part of the general improvements to the handling of coordinate spaces in Neuroglancer.
