### ISSUE TITLE
blend mode state is not properly url encoded

### ISSUE THREAD

**Issue by djkapner** [google/neuroglancer#86]
I am using ndviz with render and my render web service has a default value set of:
```WEB_SERVICE_MAX_TILE_SPECS_TO_RENDER=20```
to speed rendering by rendering only bounding boxes when the FOV is larger than 20.
When I have a multi-layer view, and am zoomed in sufficiently, I can see both layers rendered. My URL looks like:
```http://em-131snb1:8001/#!{'layers':{'12_section_montage_split0':{'type':'image'_'source':'render://http://em-131snb1:8080/danielk/MM2/12_section_montage_split0'}_'split1':{'type':'image'_'source':'render://http://em-131snb1:8080/danielk/MM2/12_section_montage_split1/'_'color':2}}_'navigation':{'pose':{'position':{'voxelSize':[1_1_1]_'voxelCoordinates':[23398.046875_249166.5_1028.5]}}_'zoomFactor':27.11263892065789}_'blend':'additive'}```

Now, if I'd like to zoom out, and want to render more tiles, I manually add in ```maxTilesSpecsToRender```to the URL like this:
```http://em-131snb1:8001/#!{'layers':{'12_section_montage_split0':{'type':'image'_'source':'render://http://em-131snb1:8080/danielk/MM2/12_section_montage_split0?maxTileSpecsToRender=500'}_'split1':{'type':'image'_'source':'render://http://em-131snb1:8080/danielk/MM2/12_section_montage_split1?maxTileSpecsToRender=500/'_'color':2}}_'navigation':{'pose':{'position':{'voxelSize':[1_1_1]_'voxelCoordinates':[23398.046875_249166.5_1028.5]}}_'zoomFactor':27.11263892065789}_'blend':'additive'}```

Once I do this, the 2 layers can't be seen at the same time anymore. I.e. the blending isn't working anymore.

On the other hand, if, when I add the 2nd layer, and add ```?maxTileSpecsToRender=500``` in the dialog html text box before pressing "add layer", then I do get the desired behavior, though, the URL looks basically the same:

```http://em-131snb1:8001/#!{'layers':{'12_section_montage_split0':{'type':'image'_'source':'render://http://em-131snb1:8080/danielk/MM2/12_section_montage_split0?maxTileSpecsToRender=500'}_'split1':{'type':'image'_'source':'render://http://em-131snb1:8080/danielk/MM2/12_section_montage_split1/?maxTileSpecsToRender=500'_'color':2}}_'navigation':{'pose':{'position':{'voxelSize':[1_1_1]_'voxelCoordinates':[62600.31640625_295237.78125_1028.5]}}_'zoomFactor':90.01713130052188}_'blend':'additive'}```

so,it seems like the URL is not fully capturing the blending state, and I can't manually tweak the URL and maintain the correct blending.

**Comment by jbms** [comment]
It looks like the issue is that in the manually edited url there is a /
character at the end, rather than before the ? character.

By the way, in recent versions of neuroglancer there is a built in editor
for editing the URL state as json --- it is the curly brace icon in the top
right.

**Comment by djkapner** [comment]
I did notice that / character was different, but moving it did not change the behavior I'm reporting. 

Thanks for the tip about the json edit. I'm not seeing any curly bracket, I'll check what version I'm running

**Comment by djkapner** [comment]
another easy way to see that it is not encoded entirely is to build up a multi-layer view with blending (no manual URL twiddling), then copy/paste the URL into another browser tab, blending doesn't follow.

**Comment by jbms** [comment]
The JSON editor may not have been merged into ndviz yet.

I noticed that 'blend': 'additive' is being specified in the wrong place.  It should be a per-layer property rather than a global property.  Not sure if this is a neuroglancer/ndviz difference.

**Comment by djkapner** [comment]
ok, I wasn't sure if this was a neuroglanceror ndviz issue. Sounds like ndviz, I'll post over there

**Comment by fcollman** [comment]
@jbms I think the issue here is that the blend mode is not getting attached to the url state of the layer when new layers are getting added. The blend_mode at the top level does successfully cause new layers to get additive blending, but then that isn't encoded in the url, so when dan adds the query parameter to the url, and the browser goes to this 'new' page, the blend mode state is lost.

**Comment by jbms** [comment]
The top-level blend mode is an ndviz-only feature, though.

**Comment by fcollman** [comment]
ah i see... i'm talking to @alexbaden and @perlman about fixing this for ndviz.  Is this feature portable to neuroglancer?  I think the general use case of having a visualization routine which involves changing the default options for new layers is something worth considering how to handle.  for example, having a different default shader for each layer, the blend mode, etc.

**Comment by djkapner** [comment]
fixed in ndviz https://github.com/neurodata/ndviz/issues/181
