### ISSUE TITLE
"keyhole" effect on shear transformations

### ISSUE THREAD

**Issue by fcollman** [google/neuroglancer#87]
When volumes are rotated or sheared with a transformation that rotates them off axis, you get this keyhole effect where you can only see a slice of the data, and you see a smaller and smaller extent of that slice the more you zoom in, and a larger and larger one when you move out.   For example if i use the demo data to shear the data 45 degrees.

```
https://neuroglancer-demo.appspot.com/#!%7B%22layers%22:%7B%22corrected-image%22:%7B%22tab%22:%22transform%22%2C%22transform%22:%5B%5B1%2C0%2C1%2C0%5D%2C%5B0%2C1%2C0%2C0%5D%2C%5B0%2C0%2C1%2C0%5D%2C%5B0%2C0%2C0%2C1%5D%5D%2C%22source%22:%22precomputed://gs://neuroglancer-public-data/kasthuri2011/image_color_corrected%22%2C%22type%22:%22image%22%7D%7D%2C%22navigation%22:%7B%22pose%22:%7B%22position%22:%7B%22voxelSize%22:%5B6%2C6%2C30%5D%2C%22voxelCoordinates%22:%5B12598.5732421875%2C6671.513671875%2C840.3251342773438%5D%7D%7D%2C%22zoomFactor%22:269.63624668241846%7D%2C%22perspectiveOrientation%22:%5B0.0248279869556427%2C-0.8274109959602356%2C-0.5594022870063782%2C-0.04293772205710411%5D%2C%22perspectiveZoom%22:1789.3699851865956%2C%22selectedLayer%22:%7B%22layer%22:%22corrected-image%22%2C%22visible%22:true%7D%7D
```

This would be a useful way to visualize data that was acquired on a light sheet microscope with objectives at 45 degrees relative to stage movement without having to resample the data, but the keyhole effect makes it somewhat unusable.  Is this easy to fix, or are their aspects of data loading or gpu's that make this hard/impossible to fix?

**Comment by jbms** [comment]
You are correct that shear transforms do not currently work.  I don't think there is anything fundamental, but the code was originally written assuming only rotation/reflection/scaling/translation, and some of the geometric calculations likely need to be fixed.

I believe that off-axis rotations already work fine, e.g. see this link:

https://neuroglancer-demo.appspot.com/#!%7B%22layers%22:%7B%22corrected-image%22:%7B%22tab%22:%22transform%22%2C%22transform%22:%5B%5B0.7070000171661377%2C0.7070000171661377%2C0%2C0%5D%2C%5B-0.707099974155426%2C0.7070000171661377%2C0%2C0%5D%2C%5B0%2C0%2C1%2C0%5D%2C%5B0%2C0%2C0%2C1%5D%5D%2C%22source%22:%22precomputed://gs://neuroglancer-public-data/kasthuri2011/image_color_corrected%22%2C%22type%22:%22image%22%7D%7D%2C%22navigation%22:%7B%22pose%22:%7B%22position%22:%7B%22voxelSize%22:%5B6%2C6%2C30%5D%2C%22voxelCoordinates%22:%5B8194.5126953125%2C1684.4766845703125%2C892.2404174804688%5D%7D%7D%2C%22zoomFactor%22:16.852265417651154%7D%2C%22perspectiveOrientation%22:%5B-0.34601518511772156%2C-0.915300726890564%2C-0.20172466337680817%2C-0.04248835891485214%5D%2C%22perspectiveZoom%22:894.6849925932978%2C%22selectedLayer%22:%7B%22layer%22:%22corrected-image%22%2C%22visible%22:true%7D%7D

**Comment by jbms** [comment]
This has finally been fixed.
