### ISSUE TITLE
New feature: click on 3D rendering to center XY(Z) images

### ISSUE THREAD

**Issue by clayreid** [google/neuroglancer#9]
I'm not sure if this is the right place to ask for features. But it would be extremely helpful to be able to command-click on a feature in the 3d rendering and have the image viewers center on it. It could just search for the nearest boundary or mesh-plane "below" the cursor. That way you could quickly look for synapses, for instance.
Thanks

**Comment by jbms** [comment]
I believe exactly this feature already exists, triggered by right clicking.

**Comment by jbms** [comment]
To answer your other question, though, this is a perfectly good place to make feature requests.
