### ISSUE TITLE
In perspective view, cursor hot spot is not centered

### ISSUE THREAD

**Issue by ceesem** [google/neuroglancer#98]
In perspective view, the cursor hot spot is on the left tip of the +, not the center. In slice views, it is in the correct spot. This is on Chrome in OS X.

**Comment by jbms** [comment]
I think this may have been due to an offset in the rendering, and may have been fixed by 775a88347154be96b6af6aaee99655cf9caf2890.  Can you let me know if this problem still exists for you?

**Comment by ceesem** [comment]
It is fixed for me now, thanks!
